{
  "hash": "9ee1769bf90b84cba3226c3fa22f99f3",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n# Análisis de variables categóricas  {#cap4}\n\n\nEn el análisis de encuestas de hogares, uno de los productos más habituales, como explican @HeeringaWestBerglund2017 y @CEPAL2023Diseno, es la estimación de parámetros descriptivos asociados a variables categóricas, los cuales permiten sintetizar las principales características de la población. Estas medidas facilitan una representación clara y comprensible de fenómenos sociales a partir de información recolectada mediante muestras probabilísticas.\n\nEntre los indicadores descriptivos más utilizados para analizar variables categóricas se encuentran, según @HeeringaWestBerglund2017 y @Agresti2019Intro, las frecuencias y las proporciones. Las frecuencias indican cuántas personas u hogares pertenecen a cada categoría, por ejemplo, el número de personas en condición de pobreza, mientras que las proporciones expresan el peso relativo de cada categoría dentro del conjunto poblacional.\n\nAunque el análisis descriptivo de variables categóricas suele apoyarse en estos parámetros básicos, también es posible combinarlas con medidas derivadas de variables numéricas, como cuantiles o indicadores de desigualdad, las cuales se abordaron en el capítulo anterior. No obstante, en este capítulo nos concentraremos exclusivamente en la descripción y estimación de parámetros asociados a variables categóricas, empleando diseños muestrales complejos.\n\nEl análisis comienza con la definición del diseño de muestreo, siguiendo los lineamientos explicados en capítulos anteriores y utilizando la misma base de datos. Este paso es fundamental porque, como señalan @HeeringaWestBerglund2017 y @CEPAL2023Diseno, permite incorporar adecuadamente las características del diseño complejo de la encuesta, tales como los factores de expansión, las unidades primarias de muestreo y los estratos de selección. La correcta especificación de estos elementos garantiza que las estimaciones obtenidas sean representativas de la población objetivo y que las medidas de precisión reflejen apropiadamente la variabilidad introducida por el esquema de muestreo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survey)\nlibrary(srvyr)\n\nsurvey_data <- readRDS(\"../Data/encuesta.rds\")\noptions(survey.lonely.psu = \"adjust\")\n\nsurvey_design <- survey_data %>%\n  as_survey_design(\n    strata = Stratum,\n    ids = PSU,\n    weights = wk,\n    nest = TRUE\n  )\n```\n:::\n\n\nLuego, se generan algunas variables categóricas derivadas de la información original de la encuesta, las cuales serán utilizadas en los ejercicios desarrollados a lo largo de este capítulo. Entre ellas, se construye una variable que identifica si la persona se encuentra o no en condición de pobreza. De manera complementaria, también se crean otras variables categóricas de interés analítico que permitirán realizar desagregaciones y comparaciones entre distintos grupos de la población:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design <- survey_design %>%\n  mutate(\n    poor = ifelse(Poverty != \"NotPoor\", 1, 0),\n    unemployed = ifelse(Employment == \"Unemployed\", 1, 0),\n    age_18 = case_when(\n      Age < 18 ~ \"< 18 years\",\n      TRUE ~ \">= 18 years\"\n    )\n  )\n```\n:::\n\n\nEn el código anterior se crean nuevas variables derivadas utilizando la función `mutate()` del paquete `dplyr`. Las variables `poor` y `unemployed` se construyen mediante la función `ifelse()`, que evalúa una condición lógica y asigna un valor dependiendo de si esta se cumple o no. En este caso, las variables toman el valor `1` cuando la persona se encuentra en condición de pobreza o desempleo, respectivamente, y `0` en caso contrario. Por su parte, la variable `age_18` se genera mediante la función `case_when()`, la cual permite definir categorías a partir de una o varias condiciones de forma más clara y flexible que `ifelse()`. Esta función resulta especialmente útil cuando se requiere construir variables categóricas con múltiples niveles. En el ejemplo, las personas menores de 18 años se clasifican en la categoría `\"< 18 years\"`, mientras que el resto se agrupa en la categoría `\">= 18 years\"`.\n\nAdemás de lo anterior, se hace necesario generar subgrupos de la población para realizar estimaciones desagregadas. En este capítulo se emplean cuatro subpoblaciones de ejemplo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nurban_subset <- survey_design %>%\n  filter(Zone == \"Urban\")\n\nrural_subset <- survey_design %>%\n  filter(Zone == \"Rural\")\n\nfemale_subset <- survey_design %>%\n  filter(Sex == \"Female\")\n\nmale_subset <- survey_design %>%\n  filter(Sex == \"Male\")\n```\n:::\n\n\n## Estimación del tamaño poblacional {#estimacion-del-tamano-poblacional}\n\nEn el análisis de encuestas de hogares, es fundamental, como destaca @CEPAL2023Diseno, estimar el tamaño de las subpoblaciones, entendido como el número de personas u hogares que pertenecen a categorías específicas y la proporción que representan dentro de la población. Estas estimaciones, basadas en variables categóricas, permiten caracterizar el perfil demográfico y socioeconómico de la población, información clave para orientar la asignación de recursos, diseñar políticas públicas y formular programas sociales. Por ejemplo, estimar cuántas personas se encuentran por debajo de la línea de pobreza, cuántas están desempleadas o cuántas alcanzaron determinado nivel educativo es esencial para identificar brechas y evaluar condiciones de bienestar.\n\nLa estimación del tamaño de una población o subpoblación, de acuerdo con @Gutierrez2016 y @CEPAL2023Diseno, se realiza a partir de variables categóricas, que segmentan a la población en grupos mutuamente excluyentes (particiones). El tamaño poblacional hace referencia al número total de individuos u hogares que, en la base de datos de la encuesta, pertenecen a una categoría determinada. Estas categorías pueden corresponder, por ejemplo, a estados de ocupación o niveles educativos alcanzados. Para obtener estas estimaciones, se combinan las respuestas de los encuestados con los pesos muestrales, que indican cuántas personas u hogares representa cada unidad de la muestra dentro de la población total.\n\nEl estimador del tamaño de la población, siguiendo a @sarndal2003model y @Gutierrez2016, se define como:\n\n$$\n\\hat{N} = \\sum_{h} \\sum_{i} \\sum_{k} w_{hik}\n$$\n\nEn donde, $w_{hik}$ es el peso o factor de expansión de la unidad $k$ en la UPM $i$ del estrato $h$. Asimismo, la estimación del tamaño de una subpoblación sigue, de acuerdo con @Gutierrez2016, el mismo principio, pero se enmarca en un subconjunto definido por una característica específica. Para determinar cuántas personas pertenecen a una categoría particular, se identifica dicho grupo en la base de datos y se suman sus pesos muestrales. Esto permite cuantificar grupos de interés específicos y conocer su tamaño dentro de la población:\n\n$$\n\\hat{N}_d = \\sum_{h} \\sum_{i} \\sum_{k} w_{hik} \\ I(y_{hik}=d)\n$$\n\nEn donde $I(y_{hik}=d)$ es una variable binaria que toma el valor de 1 si la unidad $k$ de la UPM $i$ en el estrato $h$ pertenece a la categoría $d$ de la variable de interés $y$, y 0 en caso contrario. Nótese además, como muestran @DevilleSarndal1992 y @sarndal2003model, que, si $d$ fue utilizada en la calibración de los pesos, el valor de $\\hat{N}_d$ coincidirá con el control externo aplicado.\n\nEn `R`, y utilizando el diseño muestral definido previamente, es posible, generar resúmenes de la información de la encuesta para cada categoría de la variable `Zone`. Para ello, los datos se agrupan según la zona geográfica, lo que permite obtener resultados independientes para cada uno de estos dominios de estudio. A partir de este procedimiento se producen dos tipos principales de resultados. En primer lugar, se calcula el número de observaciones efectivamente recolectadas en la muestra, sin considerar los factores de expansión, lo que corresponde al tamaño muestral disponible en cada zona. En segundo lugar, se estima el tamaño poblacional asociado a cada dominio incorporando la información del diseño de muestreo.\n\nJunto con las estimaciones poblacionales también se obtienen medidas de precisión, como el error estándar y el intervalo de confianza, las cuales permiten evaluar el nivel de incertidumbre asociado a los resultados producidos a partir de la muestra. Los resultados se presentan en la @tbl-tamano-zona. En dicha tabla, `n` representa el número de observaciones de la muestra en cada zona, mientras que `size` corresponde a la estimación del total poblacional de la subpoblación. Por su parte, la función `unweighted()` se utiliza para calcular resúmenes no ponderados directamente a partir de los datos observados en la muestra.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(\n    n = unweighted(n()),\n    size = survey_total(vartype = c(\"se\", \"ci\"))\n  )\n```\n:::\n\n\n\n::: {#tbl-tamano-zona .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por zona geográfica'}\n::: {.cell-output-display}\n\n\n|Zone  |    n|  size| size_se| size_low| size_upp|\n|:-----|----:|-----:|-------:|--------:|--------:|\n|Rural | 1297| 72102|    3062|    66039|    78165|\n|Urban | 1308| 78164|    2847|    72526|    83802|\n\n\n:::\n:::\n\n\n\nEn efecto, el tamaño de muestra fue de 1297 personas en la zona rural y de 1308 en la zona urbana. A partir de estas muestras se estimó una población de 72,102 personas para la zona rural, con un error estándar de 3,062, y de 78,164 personas para la zona urbana, con un error estándar de 2,847. Estos resultados reflejan no solo el tamaño estimado de la población en cada dominio, sino también el nivel de precisión asociado a las estimaciones obtenidas a partir del diseño muestral.\n\nConsiderando un nivel de confianza del 95%, los intervalos de confianza para las estimaciones poblacionales fueron de 66,038.5 a 78,165.4 personas en la zona rural y de 72,526.2 a 83,801.7 personas en la zona urbana. De manera análoga, también es posible estimar el número de personas según los distintos niveles de pobreza, cuyos resultados se presentan en la @tbl-tamano-pobreza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Poverty) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-tamano-pobreza .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Poverty  |  size| size_se| size_low| size_upp|\n|:--------|-----:|-------:|--------:|--------:|\n|NotPoor  | 91398|    4395|    82696|   100101|\n|Extreme  | 21519|    4949|    11719|    31319|\n|Relative | 37349|    3695|    30032|    44666|\n\n\n:::\n:::\n\n\nOtra variable categórica relevante en las encuestas de hogares es el estado de ocupación. A continuación se presenta el código correspondiente, cuyos resultados se muestran en la @tbl-tamano-empleo. En este caso, la información se agrupa según las categorías de la variable `Employment`, lo que permite obtener estimaciones separadas para cada condición de actividad laboral de la población. Mediante el uso de la función `group_by()` es posible desagregar las estimaciones en niveles más detallados, facilitando el análisis comparativo entre los distintos grupos ocupacionales.\n\nAntes de realizar las estimaciones, se excluyen los registros con valores faltantes en la variable de empleo, garantizando que los resultados se calculen únicamente con información válida. Posteriormente, para cada categoría de ocupación se estima el tamaño poblacional utilizando el diseño muestral definido previamente. Además de la estimación puntual, también se calculan medidas de precisión, específicamente el error estándar y los intervalos de confianza, lo que permite evaluar el grado de incertidumbre asociado a cada estimación.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  filter(!is.na(Employment)) %>%\n  group_by(Employment) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-tamano-empleo .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por estado de ocupación'}\n::: {.cell-output-display}\n\n\n|Employment |  size| size_se| size_low| size_upp|\n|:----------|-----:|-------:|--------:|--------:|\n|Unemployed |  4635|     761|     3129|     6141|\n|Inactive   | 41465|    2163|    37183|    45748|\n|Employed   | 61877|    2540|    56847|    66907|\n\n\n:::\n:::\n\n\nA partir de los resultados obtenidos se estima que 4,634.8 personas se encuentran desempleadas, con un intervalo de confianza del 95% entre 3,128.6 y 6,140.9 personas. Asimismo, se estima que 41,465.2 personas pertenecen a la población inactiva, con un intervalo de confianza entre 37,182.6 y 45,747.8. Finalmente, la población ocupada se estimó en 61,877.0 personas, con un intervalo de confianza de 56,847.0 a 66,907.0 personas.\n\nFinalmente, las estimaciones también pueden desagregarse simultáneamente por más de una variable categórica. Por ejemplo, es posible analizar el estado ocupacional según el nivel de pobreza, cuyos resultados se presentan en la @tbl-tamano-empleo-pobreza, de donde se puede concluir, entre otros aspectos, que aproximadamente 44,600.3 personas ocupadas no se encuentran en condición de pobreza, con un intervalo de confianza del 95% entre 39,459.6 y 49,741.0 personas. Asimismo, se estima que 6,421.8 personas inactivas se encuentran en situación de pobreza extrema, con un intervalo de confianza al 95% entre 3,806.6 y 9,037.0 personas.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  filter(!is.na(Employment)) %>%\n  group_by(Employment, Poverty) %>%\n  cascade(\n    size = survey_total(vartype = c(\"se\", \"ci\")),\n    .fill = \"Total\"\n  )\n```\n:::\n\n\n::: {#tbl-tamano-empleo-pobreza .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por estado de ocupación y condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Employment |Poverty  |   size| size_se| size_low| size_upp|\n|:----------|:--------|------:|-------:|--------:|--------:|\n|Unemployed |NotPoor  |   1768|     405|      966|     2571|\n|Unemployed |Extreme  |   1169|     348|      480|     1859|\n|Unemployed |Relative |   1697|     458|      791|     2604|\n|Unemployed |Total    |   4635|     761|     3129|     6141|\n|Inactive   |NotPoor  |  24346|    1736|    20908|    27784|\n|Inactive   |Extreme  |   6422|    1321|     3807|     9037|\n|Inactive   |Relative |  10697|    1460|     7806|    13589|\n|Inactive   |Total    |  41465|    2163|    37183|    45748|\n|Employed   |NotPoor  |  44600|    2596|    39460|    49741|\n|Employed   |Extreme  |   5128|    1122|     2907|     7349|\n|Employed   |Relative |  12149|    1347|     9483|    14816|\n|Employed   |Total    |  61877|    2540|    56847|    66907|\n|Total      |Total    | 107977|    3466|   101115|   114839|\n\n\n:::\n:::\n\n\n\n## Estimación de proporciones {#estimacion-de-proporciones}\n\nLas proporciones permiten, como explican @KornGraubard1999 y @HeeringaWestBerglund2017, expresar el peso relativo que tienen determinados grupos dentro de la población. Por ejemplo, conocer el porcentaje de hogares que se encuentran por debajo de la línea de pobreza es esencial para evaluar desigualdades y caracterizar condiciones de bienestar. Para obtener este tipo de indicadores, se calcula el promedio ponderado de la variable dicotómica, lo que asegura que la estimación represente adecuadamente la distribución poblacional. De acuerdo con estos autores, al convertir las categorías originales en variables indicadoras, la proporción estimada se calcula como:\n\n$$\n\\hat{p}_d = \\frac{\\hat{N}_d}{\\hat{N}} = \\frac{\\displaystyle\\sum_{h} \\sum_{i} \\sum_{k} w_{hik} \\ I(y_{hik}=d)} {\\displaystyle\\sum_{h} \\sum_{i} \\sum_{k} w_{hik}}\n$$\n\nSi bien este estimador es conceptualmente sencillo, corresponde, como muestran @Gutierrez2016 y @HeeringaWestBerglund2017, a una función no lineal de los totales poblacionales. Por esta razón, para derivar sus propiedades estadísticas, particularmente su varianza y error estándar, es necesario recurrir a métodos de aproximación como la linealización de Taylor. En este contexto, se utiliza la función $z_{hik}=I(y_{hik}=d)-\\hat{p}_d$. En la práctica, los programas estadísticos implementan automáticamente estos procedimientos y generan las estimaciones de proporciones junto con sus respectivos errores estándar e intervalos de confianza.\n\nCuando las proporciones toman valores muy cercanos a 0 o a 1, @KornGraubard1999 explican que la precisión de las estimaciones puede verse afectada, por lo que en muchos casos es necesario contar con tamaños muestrales mayores para obtener resultados estables y confiables. Esta situación es especialmente relevante en el análisis de fenómenos poco frecuentes o altamente concentrados, donde pequeñas variaciones en la muestra pueden producir cambios importantes en las estimaciones.\n\nAdicionalmente, @KornGraubard1999 y @Agresti2019Intro advierten que los intervalos de confianza construidos mediante aproximaciones normales pueden presentar límites inferiores menores que 0 o superiores mayores que 1, lo que dificulta su interpretación al tratarse de proporciones. Para evitar este problema, una alternativa ampliamente utilizada consiste en aplicar la transformación logit antes de construir los intervalos de confianza. Este procedimiento garantiza que, al regresar a la escala original, los límites obtenidos permanezcan dentro del rango válido de las proporciones.\n\n$$\nCI(\\hat{p}_d; 1-\\alpha) = \\frac{exp \\left[ln\\left(\\frac{\\hat{p}_d}{1-\\hat{p}_d}\\right) \\pm \\frac{\\widehat{me}}{\\hat{p}_d(1-\\hat{p}_d)}\\right]}{1 + exp \\left[ln\\left(\\frac{\\hat{p}_d}{1-\\hat{p}_d}\\right) \\pm \\frac{\\widehat{me}}{\\hat{p}_d(1-\\hat{p}_d)}\\right]}\n$$\n\nEn donde $\\widehat{me}$ corresponde al margen de error estimado y se obtiene a partir del producto entre el valor crítico de la distribución $t$ de Student y el error estándar estimado de la proporción $\\hat{p}_d$. El término $t_{1-\\alpha/2, df}$ representa el percentil asociado al nivel de confianza seleccionado, considerando $df$ grados de libertad. En el contexto de encuestas complejas, @KornGraubard1999 y @HeeringaWestBerglund2017 explican que estos grados de libertad suelen definirse como la diferencia entre el número de unidades primarias de muestreo (UPM) y el número de estratos presentes en el subgrupo o dominio de análisis.\n\nA diferencia de otros programas estadísticos que presentan los resultados en porcentaje, `R` reporta las proporciones en la escala [0,1]. Las funciones utilizadas permiten calcular directamente las estimaciones, sus errores estándar e intervalos de confianza, lo que facilita el análisis de variables categóricas en encuestas de hogares. A continuación se ilustra cómo obtener la proporción de personas por zona usando el diseño muestral previamente definido, presentada en la @tbl-prop-zona:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(proportion = survey_mean(\n    vartype = c(\"se\", \"ci\"),\n    proportion = TRUE\n  ))\n```\n:::\n\n\n::: {#tbl-prop-zona .cell layout-align=\"center\" tbl-cap='Proporción de personas por zona geográfica'}\n::: {.cell-output-display}\n\n\n|Zone  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|----------:|-------------:|--------------:|--------------:|\n|Rural |       0.48|         0.014|          0.452|          0.508|\n|Urban |       0.52|         0.014|          0.492|          0.548|\n\n\n:::\n:::\n\n\n\nEn este ejemplo, de acuerdo con la documentación de @FreedmanEllis2026, la función `survey_mean()` se utiliza para calcular la estimación de proporciones poblacionales y, mediante el argumento `proportion = TRUE`, se especifica que el interés se centra en estimar la distribución relativa de la población entre las distintas categorías de la variable analizada. Los resultados indican que aproximadamente el 47.9% de las personas reside en la zona rural, con un intervalo de confianza del 95% entre 45.2% y 50.7%, mientras que el 52.0% corresponde a población residente en la zona urbana, con un intervalo de confianza entre 49.2% y 54.7%.\n\nLa librería `srvyr` también dispone de la función `survey_prop()`, diseñada específicamente para la estimación de proporciones en encuestas complejas. Esta función produce resultados equivalentes a los obtenidos con `survey_mean()`, facilitando además una sintaxis más directa e intuitiva cuando el objetivo del análisis es exclusivamente el cálculo de proporciones. Los resultados obtenidos mediante esta alternativa se presentan en la @tbl-prop-zona2.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-zona2 .cell layout-align=\"center\" tbl-cap='Proporción de personas por zona geográfica (función survey_prop)'}\n::: {.cell-output-display}\n\n\n|Zone  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|----------:|-------------:|--------------:|--------------:|\n|Rural |       0.48|         0.014|          0.452|          0.508|\n|Urban |       0.52|         0.014|          0.492|          0.548|\n\n\n:::\n:::\n\n\n\nSi el interés se centra ahora en estimar proporciones para subpoblaciones específicas, por ejemplo, la proporción de hombres y mujeres que residen en la zona urbana, es necesario restringir el análisis a dicho dominio de estudio y posteriormente calcular las estimaciones correspondientes para cada categoría de sexo. El código computacional correspondiente se presenta en la @tbl-prop-sexo-urbano.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nurban_subset %>%\n  group_by(Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-sexo-urbano .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres en zona urbana'}\n::: {.cell-output-display}\n\n\n|Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:------|----------:|-------------:|--------------:|--------------:|\n|Female |      0.537|         0.013|          0.511|          0.563|\n|Male   |      0.463|         0.013|          0.437|          0.489|\n\n\n:::\n:::\n\n\nA partir de estas estimaciones se observa que, en la zona urbana, el 53.6% de la población corresponde a mujeres, con un intervalo de confianza del 95% entre 51.0% y 56.2%, mientras que el 46.4% corresponde a hombres, con un intervalo de confianza entre 43.7% y 48.9%. Estos resultados permiten apreciar no solo la distribución porcentual de la población según sexo, sino también el nivel de precisión asociado a las estimaciones.\n\n\nDe manera análoga, es posible realizar el mismo ejercicio para la población residente en la zona rural, estimando la proporción de hombres y mujeres. Este tipo de desagregación permite comparar la composición poblacional según sexo entre las áreas urbana y rural, proporcionando una visión más detallada de las características demográficas de la población encuestada. Los resultados correspondientes se presentan en la @tbl-prop-sexo-rural.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrural_subset %>%\n  group_by(Sex) %>%\n  summarise(\n    n = unweighted(n()),\n    proportion = survey_prop(vartype = c(\"se\", \"ci\"))\n  )\n```\n:::\n\n\n::: {#tbl-prop-sexo-rural .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres en zona rural'}\n::: {.cell-output-display}\n\n\n|Sex    |   n| proportion| proportion_se| proportion_low| proportion_upp|\n|:------|---:|----------:|-------------:|--------------:|--------------:|\n|Female | 679|      0.516|         0.008|          0.500|          0.533|\n|Male   | 618|      0.484|         0.008|          0.467|          0.500|\n\n\n:::\n:::\n\n\nAhora bien, si el análisis se restringe únicamente a la población masculina incluida en la base de datos y el interés consiste en estimar la distribución porcentual de los hombres según la zona de residencia, es posible calcular la proporción de hombres que viven en áreas urbanas y rurales utilizando el diseño muestral previamente definido. El código computacional correspondiente se presenta en la @tbl-prop-zona-hombre.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_subset %>%\n  group_by(Zone) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-zona-hombre .cell layout-align=\"center\" tbl-cap='Distribución por zona en la subpoblación masculina'}\n::: {.cell-output-display}\n\n\n|Zone  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|----------:|-------------:|--------------:|--------------:|\n|Rural |      0.491|         0.018|          0.455|          0.526|\n|Urban |      0.509|         0.018|          0.474|          0.545|\n\n\n:::\n:::\n\n\n\nSi se desea estimar resultados con varios niveles de desagregación, al igual que en los capítulos anteriores, el uso de la función `group_by()` permite generar distintos niveles de agregación mediante la combinación de dos o más variables categóricas. Por ejemplo, es posible estimar la proporción de hombres según zona de residencia y condición de pobreza de manera simultánea. Este tipo de análisis permite caracterizar con mayor detalle las condiciones socioeconómicas de subpoblaciones específicas. El procedimiento correspondiente se presenta en la @tbl-prop-zona-pobreza-hombre.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_subset %>%\n  group_by(Zone, Poverty) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-zona-pobreza-hombre .cell layout-align=\"center\" tbl-cap='Proporción de hombres por zona y condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Zone  |Poverty  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|:--------|----------:|-------------:|--------------:|--------------:|\n|Rural |NotPoor  |      0.549|         0.063|          0.424|          0.668|\n|Rural |Extreme  |      0.198|         0.067|          0.096|          0.364|\n|Rural |Relative |      0.254|         0.037|          0.187|          0.334|\n|Urban |NotPoor  |      0.660|         0.037|          0.584|          0.728|\n|Urban |Extreme  |      0.113|         0.025|          0.073|          0.171|\n|Urban |Relative |      0.227|         0.026|          0.180|          0.283|\n\n\n:::\n:::\n\n\nA partir de los resultados obtenidos se observa que, en la zona rural, el 19.7% de los hombres se encuentra en situación de pobreza extrema, mientras que en la zona urbana esta proporción corresponde al 11.3%. Aunque las estimaciones puntuales sugieren una mayor incidencia de pobreza extrema en la ruralidad, la superposición de los intervalos de confianza individuales no constituye por sí sola una prueba formal de igualdad; la significación de la diferencia debe evaluarse mediante un contraste que incorpore su error estándar, como explican @KornGraubard1999 y @HeeringaWestBerglund2017.\n\nTambién es posible, como describe @Agresti2019Intro, categorizar variables cuantitativas para facilitar su análisis conjunto con otras variables categóricas. Por ejemplo, la edad puede agruparse en rangos etarios específicos y posteriormente cruzarse con variables relacionadas con la situación en el empleo. Este tipo de procedimiento resulta útil para identificar diferencias en la participación laboral entre distintos grupos de edad.\n\nA continuación, la variable edad se clasifica en dos categorías para la población femenina: mujeres entre 18 y 35 años, y mujeres pertenecientes a otros rangos de edad. Posteriormente, estas categorías se analizan en conjunto con la variable de empleabilidad, permitiendo estimar la distribución de la condición laboral según grupo etario. Los resultados correspondientes se presentan en la @tbl-prop-edad-rango-empleo-mujer.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfemale_subset %>%\n  filter(!is.na(Employment)) %>%\n  mutate(age_range = case_when(\n    Age >= 18 & Age <= 35 ~ \"18 - 35\",\n    TRUE ~ \"Other\"\n  )) %>%\n  group_by(age_range, Employment) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-edad-rango-empleo-mujer .cell layout-align=\"center\" tbl-cap='Proporción de mujeres por rango de edad y estado de ocupación'}\n::: {.cell-output-display}\n\n\n|age_range |Employment | proportion| proportion_se| proportion_low| proportion_upp|\n|:---------|:----------|----------:|-------------:|--------------:|--------------:|\n|18 - 35   |Unemployed |      0.029|         0.009|          0.015|          0.054|\n|18 - 35   |Inactive   |      0.517|         0.038|          0.442|          0.591|\n|18 - 35   |Employed   |      0.455|         0.036|          0.385|          0.526|\n|Other     |Unemployed |      0.016|         0.007|          0.007|          0.036|\n|Other     |Inactive   |      0.571|         0.030|          0.511|          0.629|\n|Other     |Employed   |      0.413|         0.029|          0.356|          0.472|\n\n\n:::\n:::\n\n\n## Contrastes y diferencias de proporciones {#contrastes-y-diferencias-de-proporciones}\n\nSegún @KornGraubard1999 y @HeeringaWestBerglund2017, las proporciones obtenidas en las filas de una tabla de doble entrada pueden interpretarse como estimaciones para distintas subpoblaciones, definidas a partir de los niveles de una variable categórica. En este contexto, no solo resulta relevante estimar las proporciones asociadas a cada grupo, sino también evaluar las diferencias existentes entre ellas mediante contrastes lineales.\n\nPor ejemplo, suponga que el interés está en comparar la proporción de mujeres en condición de pobreza con la proporción de hombres en esta misma situación. Formalmente, siguiendo a @HeeringaWestBerglund2017, este contraste puede expresarse como $\\hat{p}_F - \\hat{p}_M$, donde $\\hat{p}_F$ representa la proporción estimada de mujeres en pobreza y $\\hat{p}_M$ la proporción estimada de hombres en dicha condición. Para construir este contraste, primero se estiman las proporciones de hombres y mujeres en estado de pobreza utilizando el mismo procedimiento descrito en capítulos anteriores. Los resultados correspondientes se presentan en la @tbl-svyby-pobreza-sexo2:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_proportion <- survey_design %>%\n  group_by(Sex) %>%\n  summarise(proportion = survey_mean(poor,\n                                     na.rm = TRUE,\n                                     vartype = c(\"se\", \"ci\")))\n\nsex_poverty_contrast <- svyby(\n  formula = ~poor,\n  by = ~Sex,\n  design = survey_design,\n  FUN = svymean,\n  na.rm = TRUE,\n  covmat = TRUE,\n  vartype = c(\"se\", \"ci\")\n)\n```\n:::\n\n\n\n::: {#tbl-svyby-pobreza-sexo2 .cell layout-align=\"center\" tbl-cap='Proporción en condición de pobreza por sexo'}\n::: {.cell-output-display}\n\n\n|Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:------|----------:|-------------:|--------------:|--------------:|\n|Female |      0.389|         0.032|          0.327|          0.452|\n|Male   |      0.395|         0.037|          0.322|          0.467|\n\n\n:::\n:::\n\n\nUna vez estimadas las proporciones de hombres y mujeres en condición de pobreza, es posible calcular la diferencia entre ambas proporciones junto con su correspondiente error estándar. En este caso, la diferencia estimada se obtiene restando la proporción de hombres en pobreza a la proporción de mujeres en esta misma condición:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n0.3892 - 0.3946\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.0054\n```\n\n\n:::\n:::\n\n\nPara calcular correctamente la variabilidad asociada a esta diferencia, @HeeringaWestBerglund2017 explican que no basta con considerar únicamente las varianzas de cada estimación por separado. También es necesario incorporar la covarianza entre ambas proporciones, dado que las estimaciones provienen de una misma muestra y, por tanto, no son independientes. La matriz de varianzas y covarianzas puede obtenerse mediante la función `vcov`, cuyos resultados se presentan en la @tbl-vcov-sex-pobreza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_vcov <- vcov(sex_poverty_contrast)\n\nsex_poverty_vcov %>%\n  data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Female     Male\nFemale 0.000998 0.000918\nMale   0.000918 0.001342\n```\n\n\n:::\n:::\n\n\n::: {#tbl-vcov-sex-pobreza .cell layout-align=\"center\" tbl-cap='Matriz de varianzas y covarianzas de la proporción de pobreza por sexo'}\n::: {.cell-output-display}\n\n\n|       |   Female|     Male|\n|:------|--------:|--------:|\n|Female | 0.000998| 0.000918|\n|Male   | 0.000918| 0.001342|\n\n\n:::\n:::\n\n\nA partir de esta matriz, el error estándar de la diferencia de proporciones se estima, siguiendo a @KornGraubard1999 y @HeeringaWestBerglund2017, utilizando la expresión general para la varianza de una diferencia entre estimadores, la cual corresponde a la suma de las varianzas de cada estimación menos dos veces la covarianza entre ellas. Para evitar inconsistencias derivadas del redondeo de los valores presentados en la @tbl-vcov-sex-pobreza, la verificación se realiza directamente con las entradas de la matriz estimada:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsqrt(\n  sex_poverty_vcov[\"Female\", \"Female\"] +\n    sex_poverty_vcov[\"Male\", \"Male\"] -\n    2 * sex_poverty_vcov[\"Female\", \"Male\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0224\n```\n\n\n:::\n:::\n\n\nNo obstante, el paquete `survey` permite realizar este procedimiento de forma directa mediante la función `svycontrast`, la cual calcula tanto el contraste lineal como su error estándar asociado. Para obtener la diferencia entre las proporciones de mujeres y hombres en condición de pobreza, se utiliza el siguiente código:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvycontrast(\n  stat = sex_poverty_contrast,\n  contrasts = list(sex_difference = c(1, -1))\n) %>%\n  data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               contrast sex_difference\nsex_difference -0.00532         0.0224\n```\n\n\n:::\n:::\n\n\nDe lo que se concluye que la diferencia estimada entre las proporciones de mujeres y hombres en estado de pobreza es -0.005 (-0.5%), con un error estándar de 0.022. Dada la magnitud del error estándar respecto de la diferencia, la estimación es compatible con una diferencia nula y no debe interpretarse por sí sola como evidencia de una menor proporción de pobreza entre las mujeres.\n\nOtro ejercicio que puede desarrollarse a partir de una encuesta de hogares consiste en estimar la proporción de personas desempleadas según la región de residencia. Para ello, estima las proporciones de desempleo para cada una de las regiones consideradas en el análisis. Los resultados obtenidos se presentan en la @tbl-svyby-desempleo-region:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_unemployment_proportion <- survey_design %>%\n  filter(!is.na(unemployed)) %>%\n  group_by(Region) %>%\n  summarise(proportion = survey_mean(unemployed,\n                                     na.rm = TRUE,\n                                     vartype = c(\"se\", \"ci\")))\n\nregion_unemployment_contrast <- svyby(\n  formula = ~unemployed,\n  by = ~Region,\n  design = survey_design %>%\n    filter(!is.na(unemployed)),\n  FUN = svymean,\n  na.rm = TRUE,\n  covmat = TRUE,\n  vartype = c(\"se\", \"ci\")\n)\n```\n:::\n\n\n\n::: {#tbl-svyby-desempleo-region .cell layout-align=\"center\" tbl-cap='Proporción en condición de desempleo por región'}\n::: {.cell-output-display}\n\n\n|Region    | proportion| proportion_se| proportion_low| proportion_upp|\n|:---------|----------:|-------------:|--------------:|--------------:|\n|Norte     |      0.049|         0.020|          0.009|          0.088|\n|Sur       |      0.066|         0.024|          0.019|          0.113|\n|Centro    |      0.039|         0.012|          0.014|          0.063|\n|Occidente |      0.040|         0.012|          0.016|          0.064|\n|Oriente   |      0.030|         0.013|          0.005|          0.054|\n\n\n:::\n:::\n\n\nUna vez estimadas las proporciones de desempleo por región, el siguiente paso consiste, de acuerdo con @HeeringaWestBerglund2017, en evaluar si existen diferencias estadísticamente significativas entre algunas de estas proporciones mediante contrastes lineales. En particular, el interés se centra en comparar las diferencias entre las proporciones estimadas de desempleo de distintas regiones. Los contrastes considerados corresponden a $\\hat{p}_{Norte} - \\hat{p}_{Centro} = 0.01004$, $\\hat{p}_{Sur} - \\hat{p}_{Centro} = 0.02691$ y $\\hat{p}_{Occidente} - \\hat{p}_{Oriente} = 0.01046$. De manera matricial, estos contrastes entre regiones pueden escribirse así:\n\n$$\n\\left[\\begin{array}{ccccc}\n1 & 0 & -1 & 0 & 0\\\\\n0 & 1 & -1 & 0 & 0\\\\\n0 & 0 & 0 & 1 & -1\n\\end{array}\\right]\n$$\n\nPara calcular los errores estándar asociados a cada uno de los contrastes anteriores, es necesario considerar no solo las varianzas de las estimaciones regionales, sino también las covarianzas entre ellas. Esta información se resume en la matriz de varianzas y covarianzas de las proporciones estimadas de desempleo por región, presentada en la @tbl-vcov-desempleo-region:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_unemployment_vcov <- vcov(region_unemployment_contrast)\n\nregion_unemployment_vcov %>%\n  data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Norte      Sur   Centro Occidente  Oriente\nNorte     0.000401 0.000000 0.000000  0.000000 0.000000\nSur       0.000000 0.000564 0.000000  0.000000 0.000000\nCentro    0.000000 0.000000 0.000154  0.000000 0.000000\nOccidente 0.000000 0.000000 0.000000  0.000151 0.000000\nOriente   0.000000 0.000000 0.000000  0.000000 0.000158\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-vcov-desempleo-region .cell layout-align=\"center\" tbl-cap='Matriz de varianzas y covarianzas de la proporción de desempleo por región'}\n::: {.cell-output-display}\n\n\n|          |    Norte|      Sur|   Centro| Occidente|  Oriente|\n|:---------|--------:|--------:|--------:|---------:|--------:|\n|Norte     | 0.000401| 0.000000| 0.000000|  0.000000| 0.000000|\n|Sur       | 0.000000| 0.000564| 0.000000|  0.000000| 0.000000|\n|Centro    | 0.000000| 0.000000| 0.000154|  0.000000| 0.000000|\n|Occidente | 0.000000| 0.000000| 0.000000|  0.000151| 0.000000|\n|Oriente   | 0.000000| 0.000000| 0.000000|  0.000000| 0.000158|\n\n\n:::\n:::\n\n\nNótese que las covarianzas entre las estimaciones regionales son iguales a cero debido a que las muestras seleccionadas en cada región son independientes entre sí. Por tanto, siguiendo la expresión presentada por @HeeringaWestBerglund2017, el error estándar de cada contraste se obtiene aplicando la expresión de la varianza para la diferencia entre dos estimadores. Para verificar los resultados sin introducir errores de redondeo, los cálculos siguientes toman las varianzas y covarianzas directamente de la matriz presentada en la @tbl-vcov-desempleo-region:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Norte - Centro\nsqrt(\n  region_unemployment_vcov[\"Norte\", \"Norte\"] +\n    region_unemployment_vcov[\"Centro\", \"Centro\"] -\n    2 * region_unemployment_vcov[\"Norte\", \"Centro\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0236\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sur - Centro\nsqrt(\n  region_unemployment_vcov[\"Sur\", \"Sur\"] +\n    region_unemployment_vcov[\"Centro\", \"Centro\"] -\n    2 * region_unemployment_vcov[\"Sur\", \"Centro\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0268\n```\n\n\n:::\n\n```{.r .cell-code}\n# Occidente - Oriente\nsqrt(\n  region_unemployment_vcov[\"Occidente\", \"Occidente\"] +\n    region_unemployment_vcov[\"Oriente\", \"Oriente\"] -\n    2 * region_unemployment_vcov[\"Occidente\", \"Oriente\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0176\n```\n\n\n:::\n:::\n\n\n\nAlternativamente, el paquete `survey` permite calcular estos contrastes de manera directa mediante la función `svycontrast`, la cual obtiene tanto las diferencias estimadas entre proporciones como sus respectivos errores estándar. En este caso, la estimación de los contrastes definidos anteriormente se realiza de la siguiente manera:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvycontrast(\n  stat = region_unemployment_contrast,\n  contrasts = list(\n    north_center = c(1, 0, -1, 0, 0),\n    south_center = c(0, 1, -1, 0, 0),\n    west_east = c(0, 0, 0, 1, -1)\n  )\n) %>%\n  data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             contrast     SE\nnorth_center   0.0100 0.0236\nsouth_center   0.0269 0.0268\nwest_east      0.0105 0.0176\n```\n\n\n:::\n:::\n\n\n## Tablas cruzadas {#tablas-cruzadas}\n\nAdemás de analizar cada variable de manera individual, resulta especialmente relevante, como explican @HeeringaWestBerglund2017 y @Agresti2019Intro, estudiar si existe asociación entre dos variables categóricas. Este tipo de análisis permite identificar patrones y relaciones que aportan información valiosa para la toma de decisiones y la comprensión de fenómenos sociales. Por ejemplo, en el ámbito de las políticas públicas es posible relacionar educación y empleo para diseñar estrategias orientadas al mercado laboral; en la evaluación de programas sociales, analizar diferencias en el acceso a servicios de salud según el nivel de ingresos; y en investigación social, estudiar cómo variables demográficas y condiciones de vida se relacionan entre sí para comprender dinámicas y tendencias de la población.\n\nFormalmente, sean $x$ y $y$ dos variables categóricas con $R$ categorías para las filas y $C$ categorías para las columnas, respectivamente. En el contexto de encuestas por muestreo, @HeeringaWestBerglund2017 señalan que el interés suele centrarse en estimar la distribución conjunta de ambas variables, es decir, la proporción de unidades poblacionales que pertenecen simultáneamente a cada combinación posible de categorías. Para ello, las entradas de una tabla cruzada, también conocida como tabla de contingencia, se estiman mediante frecuencias ponderadas obtenidas a partir de los factores de expansión y del diseño muestral. La estimación del total poblacional asociado a cada celda $(r,c)$ se define como:\n\n$$\n\\hat{N}_{rc} = \\sum_{h} \\sum_{i} \\sum_{k} w_{hik} \\ I(x_{hik}=r,\\ y_{hik}=c),\n$$\n\ndonde $w_{hik}$ representa el factor de expansión asociado al elemento $k$ de la UPM $i$ perteneciente al estrato $h$, mientras que $I(x_{hik}=r,\\ y_{hik}=c)$ corresponde a una función indicadora que toma el valor de uno cuando la unidad observada pertenece simultáneamente a la categoría $r$ de la variable $x$ y a la categoría $c$ de la variable $y$, y toma el valor de cero en cualquier otro caso.\n\nAdemás de las frecuencias conjuntas, @Agresti2019Intro muestra que también es posible estimar los tamaños marginales por filas y columnas, definidos respectivamente como $\\hat{N}_{r+} = \\sum_{c=1}^{C} \\hat{N}_{rc}$ y $\\hat{N}_{+c} = \\sum_{r=1}^{R} \\hat{N}_{rc}$. Mientras que el total general se expresa como $\\hat{N}_{++} = \\sum_{r=1}^{R}\\sum_{c=1}^{C} \\hat{N}_{rc}$. La estructura general de una tabla de contingencia con $R$ filas y $C$ columnas se presenta en la @tbl-estructura-contingencia:\n\n| Variable 2        | Variable 1 |               | $\\cdots$ |               | Marginal fila |\n|-------------------|-------------|---------------|-----------|---------------|----------------|\n|                   | $1$         | $2$           | $\\cdots$  | $C$           |                |\n| $1$               | $\\hat{N}_{11}$ | $\\hat{N}_{12}$ | $\\cdots$ | $\\hat{N}_{1C}$ | $\\hat{N}_{1+}$ |\n| $2$               | $\\hat{N}_{21}$ | $\\hat{N}_{22}$ | $\\cdots$ | $\\hat{N}_{2C}$ | $\\hat{N}_{2+}$ |\n| $\\vdots$          | $\\vdots$    | $\\vdots$      | $\\ddots$ | $\\vdots$      | $\\vdots$       |\n| $R$               | $\\hat{N}_{R1}$ | $\\hat{N}_{R2}$ | $\\cdots$ | $\\hat{N}_{RC}$ | $\\hat{N}_{R+}$ |\n| Marginal columna  | $\\hat{N}_{+1}$ | $\\hat{N}_{+2}$ | $\\cdots$ | $\\hat{N}_{+C}$ | $\\hat{N}_{++}$ |\n\n: Estructura general de una tabla de contingencia con $R$ filas y $C$ columnas {#tbl-estructura-contingencia}\n\nDe manera tradicional, @Agresti2019Intro explica que las tablas de contingencia suelen representarse como arreglos bidimensionales de dimensión $R \\times C$. Sin embargo, también pueden extenderse para incorporar una o más variables adicionales, generando subconjuntos o subtablas que permiten estudiar relaciones más complejas entre variables categóricas. A partir de los tamaños estimados, también pueden estimarse proporciones para cada celda de la tabla de contingencia, de la siguiente manera:\n\n$$\n\\hat{p}_{rc}=\\frac{\\hat{N}_{rc}}{\\hat{N}_{++}}\n$$\n\n\nA continuación, y siguiendo con la base de datos de ejemplo, se estima la distribución porcentual de hombres y mujeres según su condición de pobreza, incorporando además sus respectivos errores estándar e intervalos de confianza. Los resultados se presentan en la @tbl-contingencia-pobreza-sexo. Este tipo de análisis permite describir la composición de la población pobre según sexo y evaluar la precisión de las estimaciones obtenidas a partir del diseño muestral.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_design <- survey_design %>%\n  mutate(poor = factor(\n    poor,\n    levels = 0:1,\n    labels = c(\"Not poor\", \"Poor\")\n  ))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_design %>%\n  group_by(poor, Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-contingencia-pobreza-sexo .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres en condición de pobreza y no pobreza'}\n::: {.cell-output-display}\n\n\n|poor     |Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:--------|:------|----------:|-------------:|--------------:|--------------:|\n|Not poor |Female |      0.529|         0.012|          0.505|          0.554|\n|Not poor |Male   |      0.471|         0.012|          0.446|          0.495|\n|Poor     |Female |      0.524|         0.016|          0.492|          0.555|\n|Poor     |Male   |      0.476|         0.016|          0.445|          0.508|\n\n\n:::\n:::\n\n\nLos resultados indican que el 52.3% de la población en condición de pobreza corresponde a mujeres, mientras que el 47.6% corresponde a hombres. Para las mujeres, el intervalo de confianza al 95% se encuentra entre 49.2% y 55.5%, mientras que para los hombres el intervalo correspondiente se ubica entre 44.5% y 50.7%. Estas estimaciones permiten observar la distribución relativa de la pobreza según sexo, considerando además la incertidumbre inherente al proceso de muestreo.\n\nCon el mismo enfoque de `srvyr` también puede estimarse la tabla de contingencia mediante `group_by()` y `summarise()`. En el siguiente ejemplo se estima la distribución de la condición de pobreza según sexo, obteniendo además medidas de precisión como errores estándar e intervalos de confianza. El código correspondiente y sus resultados se presentan en la @tbl-svyby-pobreza-sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_poverty_proportion <- poverty_design %>%\n  group_by(poor, Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-svyby-pobreza-sexo .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres por condición de pobreza '}\n::: {.cell-output-display}\n\n\n|poor     |Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:--------|:------|----------:|-------------:|--------------:|--------------:|\n|Not poor |Female |      0.529|         0.012|          0.505|          0.554|\n|Not poor |Male   |      0.471|         0.012|          0.446|          0.495|\n|Poor     |Female |      0.524|         0.016|          0.492|          0.555|\n|Poor     |Male   |      0.476|         0.016|          0.445|          0.508|\n\n\n:::\n:::\n\n\nLos intervalos de confianza ya fueron calculados por `survey_prop(vartype = c(\"se\", \"ci\"))`. El siguiente código no vuelve a estimarlos mediante `confint()`; utiliza `select()` para extraer las columnas que contienen sus límites inferior y superior. Los resultados se presentan en la @tbl-confint-sexo-pobreza y coinciden, por construcción, con los generados anteriormente.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_poverty_proportion %>%\n  dplyr::select(poor, Sex, proportion_low, proportion_upp)\n```\n:::\n\n\n\n::: {#tbl-confint-sexo-pobreza .cell layout-align=\"center\" tbl-cap='Intervalos de confianza para la proporción por sexo y pobreza'}\n::: {.cell-output-display}\n\n\n|poor     |Sex    | proportion_low| proportion_upp|\n|:--------|:------|--------------:|--------------:|\n|Not poor |Female |          0.505|          0.554|\n|Not poor |Male   |          0.446|          0.495|\n|Poor     |Female |          0.492|          0.555|\n|Poor     |Male   |          0.445|          0.508|\n\n\n:::\n:::\n\n\nOtro análisis de interés relacionado con tablas de doble entrada en encuestas de hogares consiste en estimar el porcentaje de personas desempleadas según sexo. El procedimiento correspondiente y sus resultados se presentan en la @tbl-svyby-empleo-sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_employment_proportion <- survey_design %>%\n  filter(!is.na(Employment)) %>%\n  group_by(Employment, Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-svyby-empleo-sexo .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres por estado de ocupación '}\n::: {.cell-output-display}\n\n\n|Employment |Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:----------|:------|----------:|-------------:|--------------:|--------------:|\n|Unemployed |Female |      0.273|         0.054|          0.180|          0.390|\n|Unemployed |Male   |      0.727|         0.054|          0.610|          0.820|\n|Inactive   |Female |      0.770|         0.023|          0.721|          0.813|\n|Inactive   |Male   |      0.230|         0.023|          0.187|          0.279|\n|Employed   |Female |      0.405|         0.019|          0.369|          0.442|\n|Employed   |Male   |      0.595|         0.019|          0.558|          0.631|\n\n\n:::\n:::\n\n\nDe la anterior salida se puede observar que el 27.2% de las personas desempleadas son mujeres y el 72.7% son hombres, con errores estándar de 5.3 puntos porcentuales para ambas estimaciones. Los intervalos de confianza correspondientes se presentan en la @tbl-confint-empleo-sexo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_employment_proportion %>%\n  dplyr::select(Employment, Sex, proportion_low, proportion_upp)\n```\n:::\n\n\n::: {#tbl-confint-empleo-sexo .cell layout-align=\"center\" tbl-cap='Intervalos de confianza para la proporción por sexo y ocupación'}\n::: {.cell-output-display}\n\n\n|Employment |Sex    | proportion_low| proportion_upp|\n|:----------|:------|--------------:|--------------:|\n|Unemployed |Female |          0.180|          0.390|\n|Unemployed |Male   |          0.610|          0.820|\n|Inactive   |Female |          0.721|          0.813|\n|Inactive   |Male   |          0.187|          0.279|\n|Employed   |Female |          0.369|          0.442|\n|Employed   |Male   |          0.558|          0.631|\n\n\n:::\n:::\n\n\n\nSi ahora el objetivo es estimar la pobreza por región, se utiliza la variable numérica `poor` dentro de un flujo `srvyr`, como se muestra en la @tbl-svyby-region-pobreza.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_poverty_proportion <- survey_design %>%\n  group_by(Region, poor) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-svyby-region-pobreza .cell layout-align=\"center\" tbl-cap='Proporción en condición de pobreza por región'}\n::: {.cell-output-display}\n\n\n|Region    | poor| proportion| proportion_se| proportion_low| proportion_upp|\n|:---------|----:|----------:|-------------:|--------------:|--------------:|\n|Norte     |    0|      0.641|         0.055|          0.526|          0.742|\n|Norte     |    1|      0.359|         0.055|          0.258|          0.474|\n|Sur       |    0|      0.656|         0.043|          0.566|          0.737|\n|Sur       |    1|      0.344|         0.043|          0.263|          0.434|\n|Centro    |    0|      0.635|         0.079|          0.470|          0.773|\n|Centro    |    1|      0.365|         0.079|          0.227|          0.530|\n|Occidente |    0|      0.599|         0.047|          0.504|          0.687|\n|Occidente |    1|      0.401|         0.047|          0.313|          0.496|\n|Oriente   |    0|      0.548|         0.088|          0.374|          0.711|\n|Oriente   |    1|      0.452|         0.088|          0.289|          0.626|\n\n\n:::\n:::\n\n\nDe lo anterior se puede concluir que, en la región Norte, el 35% de las personas están en estado de pobreza, mientras que en el Sur la proporción es del 34%. La proporción estimada más alta se observa en la región Oriente, con un 45%. Los errores estándar reportados permiten evaluar la precisión de estas estimaciones.\n\n## La razón de *odds* {#la-razon-de-odds}\n\nLa razón de *odds* es, de acuerdo con @DiazMoralesLeon2018 y @Agresti2019Intro, una medida ampliamente utilizada para estudiar la asociación entre dos variables categóricas, especialmente cuando el interés se centra en comparar la probabilidad de ocurrencia de un evento entre distintos grupos poblacionales. Su interpretación se basa en comparar las ventajas relativas (*odds*) de ocurrencia de un evento entre dos categorías de análisis.\n\nEn este sentido, @HeeringaWestBerglund2017 señalan que este parámetro permite evaluar cómo cambia dicha ventaja entre diferentes grupos de interés y constituye una herramienta fundamental en estudios sociales, económicos y de salud; además, esta medida también puede utilizarse para cuantificar la relación entre los niveles de una variable y un factor categórico, comparando las ventajas relativas de ocurrencia del evento en cada grupo.\n\nPor ejemplo, suponga que se desea estudiar la asociación entre el sexo de las personas y la condición de pobreza. En particular, interesa evaluar si la ventaja relativa de pertenecer al grupo de personas no pobres frente al grupo de personas pobres es diferente entre mujeres y hombres. Para ello, siguiendo la definición de @Agresti2019Intro, puede expresarse la siguiente razón de *odds*:\n\n$$\n\\mathit{OR} =\n\\frac{\nP(\\text{pobreza}=0 \\mid \\text{Sex}=\\text{Female})\n\\big/\nP(\\text{pobreza}=1 \\mid \\text{Sex}=\\text{Female})\n}{\nP(\\text{pobreza}=0 \\mid \\text{Sex}=\\text{Male})\n\\big/\nP(\\text{pobreza}=1 \\mid \\text{Sex}=\\text{Male})\n}\n$$\n\nLa expresión del numerador representa, entre las mujeres, la ventaja relativa de encontrarse en condición de no pobreza respecto de encontrarse en pobreza. De manera análoga, el denominador representa esa misma ventaja entre los hombres. Por tanto, la razón de odds compara ambas ventajas relativas y permite cuantificar si la asociación entre sexo y pobreza favorece más a un grupo que a otro.\n\nUn valor igual a uno, como explican @DiazMoralesLeon2018 y @Agresti2019Intro, indicaría ausencia de asociación entre las variables, es decir, que la relación entre sexo y condición de pobreza es similar para hombres y mujeres. Valores superiores a uno indicarían una mayor ventaja relativa para las mujeres en comparación con los hombres, mientras que valores inferiores a uno sugerirían una mayor ventaja relativa para los hombres. En el contexto de encuestas de hogares, este tipo de medidas resulta especialmente útil para estudiar desigualdades sociodemográficas y brechas en condiciones de bienestar entre distintos grupos poblacionales.\n\nEl procedimiento para realizarlo en `R` sería primero estimar las proporciones de la tabla cruzada entre las variables sexo y pobreza, presentada en la @tbl-interaccion-sexo-pobreza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_interaction_proportion <- survey_design %>%\n  group_by(Sex, poor) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n\nsex_poverty_odds_contrast <- svymean(x = ~interaction(Sex, poor),\n                                     design = survey_design,\n                                     se = TRUE, na.rm = TRUE, ci = TRUE,\n                                     keep.vars = TRUE)\n```\n:::\n\n\n\n::: {#tbl-interaccion-sexo-pobreza .cell layout-align=\"center\" tbl-cap='Proporciones conjuntas de sexo y condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Sex    | poor| proportion| proportion_se| proportion_low| proportion_upp|\n|:------|----:|----------:|-------------:|--------------:|--------------:|\n|Female |    0|      0.611|         0.032|          0.547|          0.671|\n|Female |    1|      0.389|         0.032|          0.329|          0.453|\n|Male   |    0|      0.605|         0.037|          0.531|          0.675|\n|Male   |    1|      0.395|         0.037|          0.325|          0.469|\n\n\n:::\n:::\n\n\nLuego, la función `svycontrast()` realiza el contraste dividiendo cada uno de los elementos de la expresión mostrada anteriormente:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nodds_ratio <- quote(\n (`interaction(Sex, poor)Female.0` /\n  `interaction(Sex, poor)Female.1`) /\n (`interaction(Sex, poor)Male.0` /\n  `interaction(Sex, poor)Male.1`)\n)\n\nsvycontrast(\n  stat = sex_poverty_odds_contrast,\n  contrasts = odds_ratio\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         nlcon  SE\ncontrast  1.02 0.1\n```\n\n\n:::\n:::\n\n\nObteniendo que el *odds* estimado de que una mujer no se encuentre en situación de pobreza, en comparación con un hombre, es igual a 1.02. Esto significa que, sin considerar otras variables de la encuesta, las mujeres presentan una razón de probabilidades de no estar en pobreza aproximadamente 2% mayor que la observada en los hombres. En otras palabras, la probabilidad relativa de no encontrarse en condición de pobreza es ligeramente superior para las mujeres respecto a los hombres.\n\n## Prueba de independencia $\\chi^{2}$ {#prueba-de-independencia-chi}\n\nComo se introdujo en los capítulos anteriores, una prueba de hipótesis es, de acuerdo con @Agresti2019Intro, un procedimiento estadístico utilizado para evaluar si la evidencia observada en una muestra es compatible con una afirmación acerca de la población. En el contexto de tablas de contingencia, las pruebas de independencia permiten analizar si existe asociación entre dos variables categóricas.\n\nEn este caso, la hipótesis nula ($H_{0}$), en la formulación presentada por @HeeringaWestBerglund2017 y @Agresti2019Intro, establece que ambas variables son independientes; es decir, que la distribución de una variable no depende de las categorías de la otra. Bajo este supuesto, las diferencias observadas en la muestra se atribuyen únicamente a la variabilidad muestral y no a una relación real entre las variables en la población. Matemáticamente, esta hipótesis puede expresarse como:\n\n$$\nH_0: p_{rc}^0 = p_{r+} \\times p_{+c}, \\quad \\text{para todo } r = 1,\\ldots,R \\text{ y } c = 1,\\ldots,C\n$$\n\nEn donde $p_{rc}^0$ representa la proporción esperada en la celda $(r,c)$ bajo el supuesto de independencia, mientras que $P_{r+}$ y $P_{+c}$ corresponden a las proporciones marginales de las filas y columnas, respectivamente. Bajo esta formulación, la hipótesis de independencia implica que la probabilidad conjunta de cada celda puede expresarse como el producto de sus probabilidades marginales.\n\nEn consecuencia, la prueba de independencia consiste en comparar las proporciones observadas o estimadas $\\hat{p}_{rc}$ con las proporciones esperadas $p_{rc}^0$ bajo la hipótesis nula. Cuando las diferencias entre ambas son pequeñas, la evidencia empírica resulta consistente con el supuesto de independencia. Por el contrario, discrepancias suficientemente grandes sugieren la existencia de asociación entre las variables y conducen al rechazo de $H_0$.\n\nComo se ha venido mencionando, @RaoScott1981 y @HeeringaWestBerglund2017 muestran que, en las encuestas de hogares, características propias del diseño muestral complejo, como la estratificación, la selección por conglomerados y el uso de factores de expansión, afectan la variabilidad de los estimadores en comparación con la que se obtendría bajo un muestreo aleatorio simple. Como consecuencia, la prueba clásica de independencia $\\chi^2$ de Pearson no resulta adecuada para analizar tablas de contingencia provenientes de este tipo de diseños, ya que puede subestimar o sobreestimar la variabilidad real de las estimaciones.\n\nCon el propósito de corregir este problema, @fay1979contingency y @fellegi1980approximate propusieron los primeros ajustes al estadístico chi-cuadrado de Pearson basados en el efecto de diseño generalizado ($GDEFF$). Posteriormente, @RaoScott1981, @rao1984chisquare y @thomas1987chisquare ampliaron y formalizaron el marco teórico de estas correcciones, dando origen a lo que actualmente se conoce como la prueba de Rao-Scott, considerada el procedimiento de referencia para el análisis de datos categóricos obtenidos mediante encuestas complejas.\n\nLa idea central del ajuste de primer orden presentado por @RaoScott1981 y @rao1984chisquare consiste en adaptar la prueba clásica de independencia mediante la incorporación del efecto de diseño generalizado, obteniendo así un estadístico robusto frente a las complejidades del diseño muestral:\n\n$$\n\\chi_{RS}^2 = \\frac{n_{++}}{GDEFF} \\sum_r \\sum_c \\frac{(\\hat{p}_{rc} - p_{rc}^0)^2}{p_{rc}^0}\n$$\n\nEsta expresión resume la corrección de primer orden. La opción `statistic = \"F\"` utilizada más adelante en `svychisq()` corresponde, según @Lumley2026, a la corrección de segundo orden de Rao-Scott expresada mediante una aproximación basada en la distribución $F$; por ello, no debe interpretarse como una aplicación numéricamente idéntica de la fórmula anterior.\n\ndonde $n_{++}$ representa el tamaño total de la muestra, $\\hat{p}_{rc}$ corresponde a la proporción estimada en la celda $(r,c)$ de la tabla de contingencia y $p_{rc}^0$ denota la proporción esperada bajo la hipótesis nula de independencia, calculada a partir del producto de las proporciones marginales de filas y columnas.\n\nPor su parte, @HeeringaWestBerglund2017 explican que el término $GDEFF$ representa el efecto de diseño generalizado y mide cuánto se incrementa o disminuye la variabilidad de las estimaciones como consecuencia del diseño complejo de la encuesta respecto a la variabilidad que se observaría bajo un muestreo aleatorio simple. De esta manera, el ajuste de Rao--Scott permite que las inferencias derivadas de la prueba de independencia reflejen adecuadamente la estructura del diseño muestral.\n\nBajo la hipótesis nula $H_0$, @RaoScott1981 y @rao1984chisquare muestran que el estadístico $\\chi_{RS}^2$ sigue aproximadamente una distribución $\\chi^2$ con $(R-1)(C-1)$ grados de libertad, donde $R$ y $C$ corresponden al número de categorías de las filas y columnas, respectivamente. En situaciones de muestras pequeñas o con pocos grados de libertad, es frecuente utilizar ajustes basados en la distribución $F$, los cuales mejoran la precisión de la inferencia estadística. Según @HeeringaWestBerglund2017, las pruebas de Rao-Scott constituyen el estándar para el análisis de asociación entre variables categóricas en encuestas complejas.\n\nEl paquete `survey` en `R` implementa este tipo de pruebas mediante la función `svychisq()`, la cual incorpora automáticamente los ajustes de Rao-Scott para tener en cuenta las características del diseño muestral complejo. Esta función permite evaluar la existencia de asociación entre dos variables categóricas utilizando tablas de contingencia ponderadas y corrigiendo adecuadamente la variabilidad de los estimadores. A modo de ejemplo, para evaluar si la condición de pobreza es independiente del sexo, se ejecuta el siguiente código:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvychisq(formula = ~Sex + poor, design = survey_design, statistic = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's X^2: Rao & Scott adjustment\n\ndata:  NextMethod()\nF = 0.06, ndf = 1, ddf = 119, p-value = 0.8\n```\n\n\n:::\n:::\n\n\nEn este caso, el argumento `formula` especifica las dos variables categóricas cuya independencia se desea evaluar; `design` corresponde al diseño muestral previamente definido; y `statistic = \"F\"` indica que la prueba se realizará utilizando la versión ajustada basada en la distribución $F$. Si el valor-*p* es superior al 5%, no se rechaza la hipótesis nula $H_0$, concluyendo que no existe evidencia estadística suficiente para afirmar que pobreza y sexo están asociadas. Por el contrario, si el valor-*p* es inferior al 5%, se rechaza $H_0$, lo que sugiere la existencia de dependencia o asociación entre ambas variables categóricas. De manera similar, se pueden evaluar otras relaciones, como desempleo y sexo o pobreza y región.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvychisq(formula = ~Sex + Employment, design = survey_design, statistic = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's X^2: Rao & Scott adjustment\n\ndata:  NextMethod()\nF = 62, ndf = 2, ddf = 201, p-value <0.0000000000000002\n```\n\n\n:::\n:::\n\n\nEn este primer caso, para el contraste de independencia entre las variables `Sex` y `Employment`, el estadístico obtenido fue $F = 62.251$, con un valor-$p$ menor que $2.2\\times10^{-16}$, lo que proporciona evidencia estadísticamente significativa para rechazar la hipótesis nula de independencia entre ambas variables. En consecuencia, los resultados sugieren que existe una asociación significativa entre el sexo y la condición de empleo en la población de estudio.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvychisq(formula = ~Region + poor, design = survey_design, statistic = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's X^2: Rao & Scott adjustment\n\ndata:  NextMethod()\nF = 0.5, ndf = 3, ddf = 358, p-value = 0.7\n```\n\n\n:::\n:::\n\n\nPor otro lado, esta prueba de independencia entre las variables `Region` y `poor`, da como resultado $F = 0.48794$, con un valor-$p = 0.6914$. Dado que este valor-$p$ es considerablemente mayor que niveles de significancia convencionales, no existe evidencia suficiente para rechazar la hipótesis nula de independencia. Por tanto, los resultados sugieren que, bajo el diseño muestral considerado, no se observa una asociación estadísticamente significativa entre la región y la condición de pobreza.\n\n## Visualización de variables categóricas {#viz-categoricas}\n\nLa visualización de variables categóricas es fundamental en el análisis de encuestas de hogares, ya que, como señalan @Wickham2016ggplot2 y @HeeringaWestBerglund2017, permite comunicar de manera clara la distribución de grupos poblacionales y las comparaciones entre ellos. Al igual que en el análisis de variables continuas, los gráficos deben incorporar los pesos muestrales para que la representación visual corresponda a estimaciones válidas a nivel poblacional. Cuando la precisión estadística es relevante, es recomendable acompañar las barras con intervalos de confianza, que comunican tanto el valor central como la incertidumbre asociada al proceso de estimación.\n\nEn esta sección se utiliza el paquete `ggplot2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n### Gráficos de barras {#graficos-de-barras}\n\nLa construcción de gráficos de barras en `R` requiere, como paso previo, obtener las estimaciones que se desean representar visualmente. En el contexto de encuestas complejas, estas estimaciones pueden calcularse mediante las funciones `survey_total()` o `survey_prop()` del paquete `srvyr`, dependiendo de si el interés se centra en totales poblacionales o proporciones.\n\nA continuación, se ilustra este procedimiento utilizando el tamaño poblacional estimado por zona de residencia. Los resultados gráficos correspondientes se presentan en la @fig-barras-zona:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzone_size <- survey_design %>%\n  group_by(Zone) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n\nzone_colors <- c(Urban = \"#48C9B0\", Rural = \"#117864\")\n\nggplot(\n  data = zone_size,\n  aes(\n    x = Zone, y = size,\n    ymax = size_upp, ymin = size_low,\n    fill = Zone\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  scale_fill_manual(values = zone_colors) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barras del tamaño poblacional por zona geográfica](../docs/figures/fig-barras-zona-1.png){#fig-barras-zona fig-align='center' width=70%}\n:::\n:::\n\n\nEl procedimiento anterior también puede aplicarse a variables con más de dos categorías. En estos casos, el gráfico de barras permite comparar de manera sencilla las estimaciones asociadas a cada categoría de la variable de interés. Por ejemplo, a continuación se presenta la distribución estimada de la población según la condición de pobreza, cuyos resultados gráficos se muestran en la @fig-barras-pobreza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_size <- survey_design %>%\n  group_by(Poverty) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n\nggplot(\n  data = poverty_size,\n  aes(\n    x = Poverty, y = size,\n    ymax = size_upp, ymin = size_low,\n    fill = Poverty\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barras del tamaño poblacional por condición de pobreza](../docs/figures/fig-barras-pobreza-1.png){#fig-barras-pobreza fig-align='center' width=70%}\n:::\n:::\n\n\nUna de las ventajas de los gráficos de barras es que pueden extenderse fácilmente a comparaciones entre dos variables categóricas. Por ejemplo, se puede analizar el tamaño poblacional por nivel de pobreza cruzado con el estado de ocupación, presentada en la @fig-barras-empleo-pobreza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemployment_poverty_size <- survey_design %>%\n  group_by(unemployed, Poverty) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\"))) %>%\n  as.data.frame() %>%\n  mutate(\n    unemployed = case_when(\n      unemployed == 0 ~ \"Occupied\",\n      unemployed == 1 ~ \"Unemployed\",\n      is.na(unemployed) ~ \"Not in the Labour Force\"\n    )\n  )\n\nggplot(\n  data = employment_poverty_size,\n  aes(\n    x = Poverty, y = size,\n    ymax = size_upp, ymin = size_low,\n    fill = as.factor(unemployed)\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barras del tamaño poblacional por estado de ocupación y pobreza](../docs/figures/fig-barras-empleo-pobreza-1.png){#fig-barras-empleo-pobreza fig-align='center' width=80%}\n:::\n:::\n\n\nEste tipo de análisis gráfico resulta especialmente útil para identificar intersecciones de vulnerabilidad, al mostrar de manera simultánea dos o más características poblacionales. También es posible presentar proporciones en lugar de conteos. Por ejemplo, la proporción de hombres en condición de pobreza por zona, presentada en la @fig-barras-prop-zona-hombre:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_zone_poverty_proportion <- male_subset %>%\n  group_by(Zone, Poverty) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n\nggplot(\n  data = male_zone_poverty_proportion,\n  aes(\n    x = Poverty, y = proportion,\n    ymax = proportion_upp, ymin = proportion_low,\n    fill = Zone\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  scale_fill_manual(values = zone_colors) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Proporción de hombres en condición de pobreza por zona geográfica](../docs/figures/fig-barras-prop-zona-hombre-1.png){#fig-barras-prop-zona-hombre fig-align='center' width=70%}\n:::\n:::\n\n\nDe forma análoga, se puede graficar la proporción de hombres en condición de pobreza desagregada por región, presentada en la @fig-barras-prop-region-hombre:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_region_poverty_proportion <- male_subset %>%\n  group_by(Region, poor) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\"))) %>%\n  data.frame()\n\nggplot(\n  data = male_region_poverty_proportion,\n  aes(\n    x = Region, y = proportion,\n    ymax = proportion_upp, ymin = proportion_low,\n    fill = as.factor(poor)\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Proporción de hombres en condición de pobreza por región](../docs/figures/fig-barras-prop-region-hombre-1.png){#fig-barras-prop-region-hombre fig-align='center' width=75%}\n:::\n:::\n\n\nEn síntesis, los gráficos de barras junto con sus correspondientes errores estándar o intervalos de confianza permiten una descripción clara de los patrones de pobreza, empleo u otras variables categóricas en la población y, cuando se aplican correctamente, constituyen una herramienta poderosa para comunicar hallazgos de encuestas de hogares manteniendo el rigor estadístico en la representación de los resultados.\n\n\n### Mapas {#viz-mapas}\n\nLos mapas temáticos constituyen, como explica @Tennekes2018tmap, una herramienta de visualización especialmente útil en el análisis de encuestas de hogares, ya que permiten representar la distribución territorial de indicadores sociales y demográficos. En este contexto, las estimaciones de proporciones calculadas en secciones anteriores —como el porcentaje de pobreza o desempleo por región— pueden proyectarse directamente sobre unidades geográficas, facilitando así la identificación de patrones espaciales y desigualdades regionales.\n\nPara construir este tipo de mapas en `R` se requiere información geoespacial en formato *shapefile*, la cual contiene los polígonos asociados a cada unidad geográfica de análisis. En este capítulo se utiliza el archivo `shapeBigCity/BigCity.shp`, cuyas regiones corresponden a las definidas en la base de datos `BigCity`. Los paquetes `sf` y `tmap`, presentados por @Pebesma2018sf y documentados en sus versiones actuales por @sf2026 y @tmap2026, permiten cargar, manipular y visualizar esta información geográfica de manera integrada con los resultados obtenidos a partir de la encuesta.\n\nEl siguiente código carga los paquetes necesarios para trabajar con información geoespacial y visualización cartográfica en `R`. La librería `sf` permite leer y manipular objetos espaciales modernos, mientras que `tmap` proporciona herramientas para elaborar mapas temáticos. La instrucción `tmap_mode(\"plot\")` establece el modo de visualización estática de los mapas, apropiado para documentos y reportes. Finalmente, la función `read_sf()` importa el archivo geográfico `BigCity.shp`, almacenándolo en el objeto `bigcity_shape`, el cual contiene los polígonos correspondientes a las regiones de análisis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(tmap)\ntmap_mode(\"plot\")\nbigcity_shape <- read_sf(\"../Data/shapeBigCity/BigCity.shp\")\n```\n:::\n\n\nCon el shapefile cargado, se puede generar un mapa de las regiones usando `tm_shape()` y `tm_polygons()`, como se muestra en la @fig-mapa-regiones:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntm_shape(bigcity_shape) +\n  tm_polygons(col = \"Region\")\n```\n\n::: {.cell-output-display}\n![Mapa de regiones geográficas de BigCity](../docs/figures/fig-mapa-regiones-1.png){#fig-mapa-regiones fig-align='center' width=70%}\n:::\n:::\n\n\nPor ejemplo, si se desea representar geográficamente la proporción de hombres en condición de pobreza por región, estimada previamente en la @fig-barras-prop-region-hombre, es necesario integrar las estimaciones obtenidas con la información espacial del shapefile. Para ello, el objeto `male_region_poverty_proportion`, que contiene las proporciones estimadas para cada región, se vincula con el archivo geográfico mediante la función `left_join()`. Posteriormente, se filtran únicamente las observaciones correspondientes a la categoría de pobreza (`poor == 1`), de manera que el mapa represente exclusivamente la distribución espacial de la población masculina en condición de pobreza.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshape_region_map <- tm_shape(\n  bigcity_shape %>%\n    left_join(\n      male_region_poverty_proportion %>%\n        filter(poor == 1),\n      by = \"Region\"\n    )\n)\n```\n:::\n\n\nUna vez construido el objeto espacial con las estimaciones de interés, el argumento `breaks` ayuda a definir los puntos de corte que determinarán los intervalos de la escala de color utilizada en el mapa. Posteriormente, se genera el mapa temático, permitiendo visualizar la distribución regional de la proporción de hombres en condición de pobreza, como se presenta en la @fig-mapa-pobreza-hombre.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_breaks <- c(0, 0.2, 0.4, 0.6, 0.8, 1)\nshape_region_map +\n  tm_polygons(\n    col = \"proportion\",\n    breaks = poverty_breaks,\n    title = \"Poverty proportion\",\n    palette = \"YlOrRd\"\n  )\n```\n\n::: {.cell-output-display}\n![Proporción de hombres en condición de pobreza por región](../docs/figures/fig-mapa-pobreza-hombre-1.png){#fig-mapa-pobreza-hombre fig-align='center' width=70%}\n:::\n:::\n\n\nOtro uso de los mapas en encuestas, señalado por @CEPAL2023Diseno, es la visualización de la precisión de las estimaciones. Por ejemplo, usando el coeficiente de variación del ingreso medio por región es posible identificar las áreas donde las estimaciones son menos confiables, como se muestra en la @fig-mapa-cv-ingreso.\n\nEl siguiente código calcula y representa geográficamente el coeficiente de variación del ingreso medio por región. En primer lugar, se estima el ingreso promedio para cada región. El argumento `vartype = \"cv\"` solicita el cálculo del coeficiente de variación de cada estimación. Posteriormente, se definen los intervalos de clasificación de la escala de color mediante el objeto `cv_breaks`, y las estimaciones se integran con la información geográfica del shapefile usando `left_join()`. Finalmente, mediante las funciones `tm_shape()` y `tm_polygons()` del paquete `tmap`, se construye el mapa que representa espacialmente los coeficientes de variación utilizando una escala de colores en blanco y negro y ajustando la proporción del mapa con `tm_layout(asp = 0)`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_mean <- survey_design %>%\n  group_by(Region) %>%\n  summarise(mean = survey_mean(Income,\n                               na.rm = TRUE,\n                               vartype = c(\"cv\")))\n\ncv_breaks <- c(0, 0.1, 0.2, 1)\nshape_cv_map <- tm_shape(\n  bigcity_shape %>%\n    left_join(region_mean, by = \"Region\")\n)\n\nshape_cv_map +\n  tm_polygons(\n    \"mean_cv\",\n    breaks = cv_breaks,\n    title = \"Mean income CV\",\n    palette = c(\"#FFFFFF\", \"#000000\")\n  ) +\n  tm_layout(asp = 0)\n```\n\n::: {.cell-output-display}\n![Coeficiente de variación del ingreso medio por región](../docs/figures/fig-mapa-cv-ingreso-1.png){#fig-mapa-cv-ingreso fig-align='center' width=70%}\n:::\n:::\n\n\nLos polígonos con tonos más oscuros corresponden a regiones donde la estimación del ingreso presenta mayor variabilidad relativa. Como advierte @CEPAL2023Diseno, un coeficiente de variación elevado indica menor precisión relativa, pero no permite atribuirla únicamente a un tamaño muestral insuficiente, pues también puede reflejar la ponderación y otras características del diseño.\n\nCuando se desea representar simultáneamente dos variables —por ejemplo, la proporción de pobreza y su coeficiente de variación— es posible construir un mapa bivariante utilizando `ggplot2` junto con el paquete `biscale`, documentado por @biscale2025, y el paquete `cowplot`, documentado por @cowplot2025. Este tipo de visualización permite identificar regiones con alta pobreza y alta incertidumbre en la estimación de forma conjunta, como se presenta en la @fig-mapa-bivariante. El siguiente código estima la proporción de mujeres en condición de pobreza en zonas rurales para cada región, incorporando además el cálculo del coeficiente de variación de las estimaciones, generando así una base de datos lista para la construcción de un mapa bivariado.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_sex_poverty_proportion <- survey_design %>%\n  group_by(Region, Zone, Sex, poor) %>%\n  summarise(proportion = survey_mean(vartype = \"cv\")) %>%\n  filter(poor == 1, Zone == \"Rural\", Sex == \"Female\")\n```\n:::\n\n\n\nEl siguiente código construye un mapa bivariado que permite visualizar simultáneamente la proporción de pobreza femenina rural y el coeficiente de variación asociado a dicha estimación por región. En primer lugar, se integran las estimaciones contenidas en `region_sex_poverty_proportion` con la información geográfica del shapefile mediante `left_join()`. Posteriormente, utilizando la función `bi_class()` del paquete `biscale`, documentada por @biscale2025, se clasifican conjuntamente las variables `proportion` y `proportion_cv` en una cuadrícula de \\(3 \\times 3\\) categorías (`dim = 3`), empleando el método de clasificación de Fisher (`style = \"fisher\"`). Luego, con `ggplot2` y `geom_sf()`, se genera el mapa temático utilizando colores bivariados definidos por `bi_scale_fill()`, mientras que `bi_theme()` aplica un estilo minimalista y se elimina la leyenda predeterminada.\n\nA continuación, la función `bi_legend()`, documentada por @biscale2025, crea una leyenda especializada que permite interpretar simultáneamente ambas dimensiones del mapa: el coeficiente de variación y la pobreza femenina rural. Finalmente, mediante las funciones `ggdraw()` y `draw_plot()` del paquete `cowplot`, documentadas por @cowplot2025, se combinan el mapa y la leyenda en una única visualización.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(biscale)\nlibrary(cowplot)\n\nbivariate_shape <- bigcity_shape %>%\n  left_join(region_sex_poverty_proportion, by = \"Region\")\n\nk <- 3\nbivariate_data <- bi_class(\n  bivariate_shape,\n  y = proportion,\n  x = proportion_cv,\n  dim = k,\n  style = \"fisher\"\n)\n\nbivariate_map <- ggplot() +\n  geom_sf(\n    data = bivariate_data,\n    aes(fill = bi_class, geometry = geometry),\n    colour = \"white\",\n    size = 0.1\n  ) +\n  bi_scale_fill(pal = \"GrPink\", dim = k) +\n  bi_theme() +\n  theme(legend.position = \"none\")\n\nbivariate_legend <- bi_legend(\n  pal = \"GrPink\",\n  dim = k,\n  xlab = \"Coefficient of variation\",\n  ylab = \"Rural female poverty\",\n  size = 8\n)\n\nggdraw() +\n  draw_plot(bivariate_map, 0, 0, 1, scale = 0.7) +\n  draw_plot(bivariate_legend, 0.75, 0.4, 0.2, 0.2)\n```\n\n::: {.cell-output-display}\n![Mapa bivariante: proporción de pobreza femenina rural y su coeficiente de variación por región](../docs/figures/fig-mapa-bivariante-1.png){#fig-mapa-bivariante fig-align='center' width=80%}\n:::\n:::\n\n\nEn este mapa, cada celda de la leyenda combina un tono de la proporción de pobreza (eje vertical) con un tono del coeficiente de variación (eje horizontal), permitiendo identificar simultáneamente regiones con alta pobreza y alta incertidumbre en la estimación. Este tipo de representación puede ayudar a priorizar una evaluación del diseño y de la precisión en zonas geográficas específicas; por sí solo, sin embargo, no determina automáticamente que deba ampliarse el tamaño muestral.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}