{
  "hash": "5651d7c05aa8b9d3df00fdc32416cda0",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n# Análisis de las variables continuas {#cap3}\n\nEl análisis estadístico de encuestas ha evolucionado de manera constante, impulsado por el desarrollo de nuevas metodologías y enfoques que buscan mejorar la precisión y la representatividad de los resultados [@Lumley2010; @HeeringaWestBerglund2017]. En general, estos avances surgen en el ámbito académico y, con el tiempo, son adoptados por instituciones públicas, empresas privadas y organismos estadísticos, que demandan su incorporación en los principales programas de análisis de datos.\n\nEste capítulo presenta los principales procedimientos para el análisis estadístico de variables continuas utilizando `R`, incorporando adecuadamente las características del diseño muestral, tales como los factores de expansión, así como la estratificación y la conglomeración. A lo largo de este capítulo se presentan métodos para estimar parámetros poblacionales, evaluar la precisión de las estimaciones y realizar inferencias válidas a partir de datos provenientes de encuestas complejas. Asimismo, tanto en este capítulo como en el resto del documento, se introducen de manera gradual las principales funciones y herramientas del paquete `survey`, una de las alternativas más completas y ampliamente utilizadas en `R` para el análisis adecuado de encuestas de hogares.\n\nDe acuerdo con @RCoreSerialization2026, las bases de datos utilizadas en el análisis de encuestas pueden encontrarse en una amplia variedad de formatos, como `xlsx`, `dat`, `csv`, `parquet`, `sas7bdat`, `sav` y `txt`, entre otros. Sin embargo, una buena práctica consiste en importar la información desde cualquiera de estos formatos y guardarla posteriormente en un archivo con extensión `.rds`, un formato nativo de `R` que permite almacenar distintos tipos de objetos, como bases de datos, vectores, matrices o listas. Otro formato nativo de `R` es `.RData`, que permite guardar varios objetos en un mismo archivo. En contraste, los archivos `.rds` almacenan un único objeto, lo que facilita un manejo más controlado, explícito y reproducible de la información. Por esta razón, se recomienda utilizar preferentemente el formato `.rds` al documentar proyectos y desarrollar análisis reproducibles.\n\nPara ilustrar la sintaxis computacional que se utilizará a lo largo del capítulo, se empleará una base de datos proveniente de una encuesta con un diseño de muestreo complejo. A continuación, se muestra cómo cargar el archivo, almacenado en formato `.rds`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_data <- readRDS(\"../Data/encuesta.rds\")\n```\n:::\n\n\nEl objeto `survey_data` carga la infomración desde el archivo `encuesta.rds`, el cual está organizado de manera que cada fila corresponde a una unidad observada, mientras que las columnas contienen tanto las variables de interés como la información necesaria para representar el diseño muestral. Para examinar rápidamente su estructura, puede utilizarse la función `glimpse()`, que presenta el número de observaciones y variables, sus nombres, sus tipos de datos y una muestra de los valores registrados.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndplyr::glimpse(survey_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,605\nColumns: 20\n$ HHID        <chr> \"idHH00031\", \"idHH00031\", \"idHH00031\", \"idHH00031\", \"idHH0…\n$ Stratum     <chr> \"idStrt001\", \"idStrt001\", \"idStrt001\", \"idStrt001\", \"idStr…\n$ NIh         <int> 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9…\n$ nIh         <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…\n$ dI          <dbl> 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5…\n$ PersonID    <chr> \"idPer01\", \"idPer02\", \"idPer03\", \"idPer04\", \"idPer05\", \"id…\n$ PSU         <chr> \"PSU0003\", \"PSU0003\", \"PSU0003\", \"PSU0003\", \"PSU0003\", \"PS…\n$ Zone        <chr> \"Rural\", \"Rural\", \"Rural\", \"Rural\", \"Rural\", \"Rural\", \"Rur…\n$ Sex         <chr> \"Male\", \"Female\", \"Female\", \"Male\", \"Female\", \"Female\", \"F…\n$ Age         <int> 68, 56, 24, 26, 3, 61, 23, 5, 1, 59, 50, 33, 81, 76, 45, 4…\n$ MaritalST   <fct> Married, Married, Married, Married, NA, Widowed, Separated…\n$ Income      <dbl> 409.9, 409.9, 409.9, 409.9, 409.9, 823.8, 823.8, 823.8, 82…\n$ Expenditure <dbl> 346.3, 346.3, 346.3, 346.3, 346.3, 392.2, 392.2, 392.2, 39…\n$ Employment  <fct> Employed, Employed, Employed, Employed, NA, Employed, Inac…\n$ Poverty     <fct> NotPoor, NotPoor, NotPoor, NotPoor, NotPoor, NotPoor, NotP…\n$ dki         <dbl> 8.00, 8.00, 8.00, 8.00, 8.00, 8.00, 8.00, 8.00, 8.00, 8.00…\n$ dk          <dbl> 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 42, 42, 42…\n$ wk          <dbl> 34.5, 33.6, 33.6, 34.5, 33.6, 33.6, 33.6, 34.5, 33.6, 34.5…\n$ Region      <fct> Norte, Norte, Norte, Norte, Norte, Norte, Norte, Norte, No…\n$ CatAge      <ord> Más de 60, 46-60, 16-30, 16-30, 0-5, Más de 60, 16-30, 0-5…\n```\n\n\n:::\n:::\n\n\nLa base contiene 2.605 registros individuales y 20 variables. Cada fila corresponde a una persona, identificada mediante `PersonID`, y se encuentra vinculada con su hogar a través de `HHID`. Además de variables sociodemográficas y económicas, como sexo, edad, estado civil, condición de empleo, ingreso, gasto y situación de pobreza, la base incluye información necesaria para representar el diseño de muestreo complejo, como el estrato (`Stratum`), la unidad primaria de muestreo (`PSU`) y los factores de expansión (`wk`). También incorpora variables de clasificación geográfica y demográfica, como zona, región y grupo de edad.\n\nSegún @ONUDeff [sección 7.8], es fundamental que la estructura del diseño muestral sea tenida en cuenta en el proceso de inferencia al estimar estadísticas oficiales basadas en encuestas de hogares. Como se ha insistido en este documento, ignorar este aspecto puede generar estimaciones sesgadas y errores de muestreo subestimados. En este sentido los programas estadísticos incorporan funcionalidades específicas para manejar datos provenientes de encuestas con diseños complejos.\n\nUna vez cargada la encuesta de hogares en `R`, el siguiente paso es definir el diseño muestral del cual proviene dicha muestra. Para ello se utilizará el paquete `srvyr`, que surge como un complemento del paquete `survey`. Estas librerías permiten definir objetos tipo `survey.design`, a los que se aplican las funciones de estimación y análisis de encuestas, y que pueden ser combinadas con la programación del paquete `tidyverse`. A continuación, se muestra un ejemplo en el que se define un objeto de tipo `survey_design` para la encuesta:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noptions(survey.lonely.psu = \"adjust\")\n\nlibrary(survey)\nlibrary(srvyr)\n\nsurvey_design <- survey_data %>%\n  as_survey_design(\n    strata = Stratum,\n    ids = PSU,\n    weights = wk,\n    nest = TRUE\n  )\n```\n:::\n\n\nComo explica @Lumley2026, la opción `options(survey.lonely.psu = \"adjust\")` define cómo el paquete `survey` debe tratar los estratos que contienen una sola UPM en la muestra. En estos estratos no es posible calcular directamente la variabilidad entre UPM, porque no existe una segunda unidad con la cual realizar la comparación. Con el método `\"adjust\"`, la contribución de la UPM solitaria a la varianza se calcula centrando su estimación en la media general de las UPM de la muestra, en lugar de utilizar la media del propio estrato. Este ajuste evita que la contribución del estrato sea omitida o quede indefinida y suele producir una estimación conservadora de la varianza. La opción no modifica las estimaciones puntuales, sino únicamente sus varianzas, errores estándar e intervalos de confianza. Su aplicación debe distinguirse del caso en el que una UPM sea seleccionada con probabilidad de inclusión uno. En cualquier caso, la contribución a la varianza debe especificarse mediante la información apropiada del diseño.\n\nEn la implementación descrita por @FreedmanEllis2026, `survey_data` corresponde a la base de datos que contiene la muestra seleccionada. A partir de estos datos, la función `as_survey_design()` convierte la información en un objeto de clase `tbl_svy`, el cual almacena todos los elementos necesarios para describir el diseño muestral de la encuesta. Entre ellos se incluyen la variable de estratificación (`strata`), que identifica los estratos definidos en el diseño, junto con la variable que representa las unidades primarias de muestreo (UPM) o conglomerados seleccionados en la primera etapa del muestreo (`ids`). Asimismo, el argumento `weights` define la variable que contiene los factores de expansión asociados a cada observación. Finalmente, la opción `nest = TRUE` vuelve únicos dentro de cada estrato los identificadores de conglomerado que pudieran repetirse entre estratos.\n\n## Estimación de parámetros descriptivos {#estimacion-de-parametros-descriptivos}\n\nEn las encuestas de hogares es común estimar parámetros descriptivos asociados a variables numéricas, tales como totales, medias, razones y desviaciones estándar. Estas medidas permiten caracterizar distintos fenómenos sociales y económicos de la población. En esta sección se presenta la lógica detrás de la sintaxis utilizada para este tipo de estimación, junto con sus correspondientes medidas de precisión.\n\n### Totales {#estimacion-del-total}\n\nComo se ha señalado anteriormente, el total poblacional de una variable de interés puede estimarse de manera aproximadamente insesgada mediante el estimador de calibración [@DevilleSarndal1992], que pondera el valor observado en cada unidad por su correspondiente factor de expansión calibrado. En un diseño de muestreo con estratificación y selección en varias etapas, este estimador se expresa como:\n\n$$\n\\hat{t}_y =\n\\sum_{h}\n\\sum_{i}\n\\sum_{k}\nw_{hik}\\,y_{hik},\n$$\n\ndonde $h$ identifica el estrato, $i$ la unidad primaria de muestreo y $k$ la unidad final observada. El término $y_{hik}$ representa el valor de la variable de interés para la unidad $k$ perteneciente a la unidad primaria $i$ del estrato $h$, mientras que $w_{hik}$ corresponde a su factor de expansión. De este modo, cada unidad de la muestra representa a un determinado número de unidades de la población, y la suma ponderada permite reconstruir el total poblacional. \n\nEn `R`, la función `survey_total()` se utiliza para estimar totales a partir del objeto de diseño. Esta función incorpora automáticamente los factores de expansión y la estructura del diseño, garantizando que las estimaciones reflejen correctamente el modelo de inferencia.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_total(\n  x,\n  na.rm = FALSE,\n  vartype = c(\"se\", \"ci\", \"var\", \"cv\"),\n  level = 0.95,\n  deff = FALSE\n)\n```\n:::\n\n\nLos argumentos principales de la función `survey_total()` son `x`, `na.rm`, `vartype`, `level` y `deff`. El argumento `x` corresponde a la variable sobre la cual se desea calcular el total; también puede dejarse vacío cuando se busca obtener únicamente el total ponderado de casos de la muestra. Por su parte, `na.rm` indica si los valores faltantes (`NA`) deben eliminarse antes de realizar el cálculo, siendo `FALSE` el valor predeterminado.\n\nEl argumento `vartype` permite especificar el tipo de medida de incertidumbre que se desea estimar, pudiendo solicitarse uno o varios resultados simultáneamente, tales como el error estándar (`\"se\"`), el intervalo de confianza (`\"ci\"`), la varianza (`\"var\"`) o el coeficiente de variación (`\"cv\"`). Asimismo, `level` define el nivel de confianza utilizado para el cálculo de los intervalos de confianza, cuyo valor por defecto es 0.95. Por otro lado, el intervalo de confianza puede obtenerse directamente al incluir el argumento `vartype = \"ci\"` dentro de `survey_total()`, o bien utilizando la función `confint()` sobre el objeto resultante, especificando el nivel de confianza requerido. Finalmente, `deff` es un valor lógico que indica si se debe retornar el efecto del diseño (DEFF).\n\nEl siguiente ejemplo presenta cómo estimar totales y sus intervalos de confianza para diferentes variables de interés en `R`, utilizando la función `survey_total()`, cuyos resultados se presentan en la @tbl-total-ingreso:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(\n    total = survey_total(Income, \n                         vartype = c(\"se\", \"ci\"), \n                         deff = TRUE))\n```\n:::\n\n\n::: {#tbl-total-ingreso .cell layout-align=\"center\" tbl-cap='Estimación del total de ingresos de los hogares con intervalo de confianza al 95%'}\n::: {.cell-output-display}\n\n\n|    total| total_se| total_low| total_upp| total_deff|\n|--------:|--------:|---------:|---------:|----------:|\n| 85793667|  4778674|  76331414|  95255920|         11|\n\n\n:::\n:::\n\n\nDe la tabla, se obtiene que la estimación del total poblacional para el ingreso total es de 85.793.667. Este valor corresponde al estimador puntual obtenido a partir de la encuesta, incorporando los factores de expansión y las características del diseño muestral. El error estándar asociado a esta estimación es de 4.778.674, lo que refleja la variabilidad muestral del estimador. A partir de este valor se construye un intervalo de confianza del 95%, cuyos límites inferior y superior son 76.331.414 y 95.255.920, respectivamente. El efecto de diseño (`deff`), en el sentido desarrollado por @kish1965survey, es igual a 11, lo cual sugiere una ligera pérdida de precisión asociada principalmente a las características del diseño complejo. En consecuencia, aunque el tamaño muestral nominal pueda ser grande, el tamaño muestral efectivo resultaría un poco menor debido al efecto combinado de la ponderación, la estratificación y la conglomeración.\n\nPara continuar ilustrando el uso de la función `survey_total()`, estimemos el total de gastos de los hogares, pero ahora calculando el intervalo de confianza al 90%. El siguiente código realiza esta estimación, presentada en la @tbl-total-gasto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(total = survey_total(\n    Expenditure,\n    vartype = \"ci\",\n    level = 0.9,\n    deff = TRUE\n  ))\n```\n:::\n\n\n::: {#tbl-total-gasto .cell layout-align=\"center\" tbl-cap='Estimación del total de gastos de los hogares con intervalo de confianza al 90%'}\n::: {.cell-output-display}\n\n\n|    total| total_low| total_upp| total_deff|\n|--------:|---------:|---------:|----------:|\n| 55677504|  51360469|  59994539|       10.2|\n\n\n:::\n:::\n\n\n\nSi el objetivo es estimar el total de ingresos de los hogares, pero desagregado por sexo, se puede utilizar la función `group_by()` para agrupar por la variable de interés, junto con `cascade()` de la librería `srvyr`, que permite agregar una fila con el total general al final de la tabla. De esta manera, se pueden obtener fácilmente los totales por categoría y el total global dentro del mismo marco de resumen, como se muestra en la @tbl-total-ingreso-sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Sex) %>%\n  cascade(\n    total = survey_total(Income, \n                         vartype = c(\"se\", \"ci\"), \n                         level = 0.95),\n    .fill = \"Total income\")\n```\n:::\n\n\n::: {#tbl-total-ingreso-sexo .cell layout-align=\"center\" tbl-cap='Total de ingresos de los hogares desagregado por sexo'}\n::: {.cell-output-display}\n\n\n|Sex          |    total| total_se| total_low| total_upp|\n|:------------|--------:|--------:|---------:|---------:|\n|Female       | 44153820|  2324452|  39551172|  48756467|\n|Male         | 41639847|  2870194|  35956576|  47323118|\n|Total income | 85793667|  4778674|  76331414|  95255920|\n\n\n:::\n:::\n\n\nComo se observa en los códigos anteriores, una forma práctica de obtener las estimaciones del total, su error estándar y su intervalo de confianza es mediante el argumento `vartype`, especificando las opciones `\"se\"` y `\"ci\"` respectivamente.\n\n### Medias {#estimacion-de-la-media}\n\nSegún @Gutierrez2016, la estimación de la media poblacional ocupa un lugar central en las encuestas de hogares, ya que muchos de los indicadores utilizados para el análisis socioeconómico corresponden a valores promedio, como el ingreso medio del hogar, el gasto per cápita o las horas promedio trabajadas. Este tipo de parámetros permite resumir el comportamiento general de las variables de interés y describir las tendencias centrales de la población objetivo. El estimador de la media poblacional puede expresarse como una razón no lineal entre dos totales poblacionales, los cuales se estiman de la siguiente manera:\n\n$$\n\\hat{\\bar{y}}=  \\frac{\\hat{t}_y}{\\hat{N}}  =  \\frac{\\sum_{h}\\sum_{i}\\sum_{k} w_{h i k} \\ y_{hik}}{\\sum_{h}\\sum_{i}\\sum_{k} w_{h i k}}\n$$\n\nDe acuerdo con @sarndal2003model, dado que $\\hat{\\bar{y}}$ no es una estadística lineal, su varianza suele estimarse mediante una aproximación. Por esta razón, es necesario recurrir a métodos de remuestreo o a la linealización de Taylor para aproximar su varianza. En este caso particular, utilizando series de Taylor, la varianza se define como:\n\n$$\n\\widehat{Var}\\left(\\hat{\\bar{y}}\\right)  \\approx  \\frac{\\widehat{Var}\\left(\\hat{t}_y\\right)+\\hat{\\bar{y}}^{2}\\ \\widehat{Var}\\left(\\hat{N}\\right)-2\\ \\hat{\\bar{y}} \\  \\widehat{Cov}\\left(\\hat{t}_y,\\hat{N}\\right)}{\\hat{N}^{2}}\n$$\n\nComo se puede observar, el cálculo de la varianza de la media poblacional implica componentes analíticos complejos, como la covarianza entre el total estimado y el tamaño poblacional estimado. Sin embargo, el paquete `srvyr` en `R` facilita estos cálculos al incorporar funciones que estiman directamente la media, su error estándar, el intervalo de confianza y el efecto del diseño. A continuación, se presenta la sintaxis para estimar la media de los ingresos de los hogares, junto con su intervalo de confianza al 95%, cuyos resultados se presentan en la @tbl-media-ingreso:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(mean = survey_mean(\n    Income,\n    vartype = c(\"se\", \"ci\"),\n    level = 0.95,\n    deff = TRUE\n  ))\n```\n:::\n\n\n::: {#tbl-media-ingreso .cell layout-align=\"center\" tbl-cap='Estimación de la media de ingresos de los hogares'}\n::: {.cell-output-display}\n\n\n| mean| mean_se| mean_low| mean_upp| mean_deff|\n|----:|-------:|--------:|--------:|---------:|\n|  571|    28.5|      515|      627|      8.82|\n\n\n:::\n:::\n\n\nComo se aprecia, los argumentos utilizados en la función `survey_mean()` son similares a los de `survey_total()`. En este caso, `vartype` permite obtener el error estándar (`\"se\"`) y el intervalo de confianza (`\"ci\"`), mientras que el argumento `deff = TRUE` solicita el cálculo del efecto del diseño. La estimación indica que el ingreso medio de los hogares en la población es de aproximadamente 571 dólares. El error estándar asociado es de 28,5, lo que refleja la incertidumbre muestral de la estimación. El intervalo de confianza, cuyos límites son 515 y 627, para un nivel de confianza del 95%. Además, el efecto de diseño estimado es de 8,82, lo que significa que la varianza de la media bajo el diseño muestral complejo es 8,82 veces mayor que la que se obtendría con un muestreo aleatorio simple de igual tamaño. Este valor evidencia una pérdida considerable de eficiencia, posiblemente asociada con la magnitud de la variabilidad del ingreso  entre las unidades primarias de muestreo.\n\nDe forma análoga, es posible estimar la media de los gastos de los hogares, empleando la misma estructura de código, presentada en la @tbl-media-gasto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(mean = survey_mean(\n    Expenditure,\n    vartype = c(\"se\", \"ci\"),\n    level = 0.95,\n    deff = TRUE\n  ))\n```\n:::\n\n\n\n::: {#tbl-media-gasto .cell layout-align=\"center\" tbl-cap='Estimación de la media de gastos de los hogares'}\n::: {.cell-output-display}\n\n\n| mean| mean_se| mean_low| mean_upp| mean_deff|\n|----:|-------:|--------:|--------:|---------:|\n|  371|    13.3|      344|      397|      6.02|\n\n\n:::\n:::\n\n\nLa media estimada del gasto es de 371 dólares, con un error estándar de 13,3. El intervalo de confianza se extiende entre 344 y 397, mientras que el efecto de diseño de 6,02 indica una alta heterogeneidad entre las UPM de la muestra con respecto al gasto promedio. También se pueden realizar estimaciones de la media por subgrupos siguiendo el mismo esquema mostrado previamente. De manera análoga, se pueden calcular las medias del gasto por zona, las cuales son presentadas en la @tbl-media-gasto-zona:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  cascade(\n    mean = survey_mean(Expenditure,\n                       level = 0.95,\n                       vartype = c(\"se\", \"ci\")),\n    .fill = \"Mean expenditure\")\n```\n:::\n\n\n\n::: {#tbl-media-gasto-zona .cell layout-align=\"center\" tbl-cap='Media de gastos de los hogares desagregada por zona'}\n::: {.cell-output-display}\n\n\n|Zone             | mean| mean_se| mean_low| mean_upp|\n|:----------------|----:|-------:|--------:|--------:|\n|Mean expenditure |  371|    13.3|      344|      397|\n|Rural            |  274|    10.3|      254|      294|\n|Urban            |  460|    22.2|      416|      504|\n\n\n:::\n:::\n\n\nAl desagregar por zona, se observa que los hogares urbanos registran un gasto medio de 460, frente a 274 en los hogares rurales. Aunque los intervalos de confianza muestran mayor incertidumbre en la zona urbana, no se superponen, lo que sugiere una diferencia importante entre ambas zonas. Asimismo, es posible realizar una estimación combinada por zona y región, presentada en la @tbl-media-gasto-zona-reg:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone, Region) %>%\n  cascade(\n    mean = survey_mean(Expenditure, \n                       level = 0.95, \n                       vartype = c(\"se\", \"ci\")),\n    .fill = \"Mean expenditure\")\n```\n:::\n\n\n\n::: {#tbl-media-gasto-zona-reg .cell layout-align=\"center\" tbl-cap='Media de gastos de los hogares desagregada por zona y región'}\n::: {.cell-output-display}\n\n\n|Zone             |Region           | mean| mean_se| mean_low| mean_upp|\n|:----------------|:----------------|----:|-------:|--------:|--------:|\n|Mean expenditure |Mean expenditure |  371|    13.3|      344|      397|\n|Rural            |Norte            |  307|    18.4|      271|      343|\n|Rural            |Sur              |  317|    14.6|      288|      346|\n|Rural            |Centro           |  337|    42.8|      252|      422|\n|Rural            |Occidente        |  242|    11.1|      220|      264|\n|Rural            |Oriente          |  242|    22.8|      197|      287|\n|Rural            |Mean expenditure |  274|    10.3|      254|      294|\n|Urban            |Norte            |  402|    48.0|      307|      497|\n|Urban            |Sur              |  497|    62.5|      373|      621|\n|Urban            |Centro           |  531|    53.1|      426|      636|\n|Urban            |Occidente        |  376|    20.9|      334|      417|\n|Urban            |Oriente          |  466|    45.3|      377|      556|\n|Urban            |Mean expenditure |  460|    22.2|      416|      504|\n\n\n:::\n:::\n\n\nEl gasto medio varía de forma importante según la zona de residencia y la región. En el área rural, los mayores promedios se observan en las regiones Centro, Sur y Norte, mientras que Occidente y Oriente presentan los valores más bajos. En el área urbana, el gasto medio es superior en todas las regiones y alcanza sus niveles más altos en Centro, Sur y Oriente. No obstante, algunas estimaciones regionales, especialmente las de Centro rural y Sur urbano, presentan errores estándar relativamente elevados, por lo que deben interpretarse con mayor cautela.\n\n\n### Razones {#estimacion-de-razones}\n\nLa razón poblacional es un parámetro no lineal definido como el cociente entre los totales de dos variables de interés. Permite cuantificar la relación entre ambas variables y resulta especialmente útil para construir indicadores relativos, comparar grupos y analizar su evolución a lo largo del tiempo. En las encuestas de hogares, este parámetro se utiliza ampliamente para calcular indicadores como el número de hombres por cada mujer, la proporción de personas ocupadas respecto de la población en edad de trabajar y la prevalencia de la subalimentación [@FAO2026PoU].\n\nDado que la razón corresponde al cociente entre dos parámetros (totales) poblacionales desconocidos, tanto el numerador como el denominador deben ser estimados a partir de la muestra.  Siendo $t_y$ el total de la variable $y$ y $t_x$ el total de la variable $x$, la razón poblacional se define como $R = \\frac{t_y}{t_x}$ y su estimador puntual se expresa como:\n\n$$\n\\hat{R} = \\frac{\\hat{t}_y}{\\hat{t}_x}\n= \\frac{\\sum_{h}\\sum_{i}\\sum_{k} w_{hik} \\ y_{hik}}\n       {\\sum_{h}\\sum_{i}\\sum_{k} w_{hik} \\ x_{hik}}\n$$\n\nSin embargo, la estimación de la varianza de una razón requiere procedimientos específicos, entre los que destacan la linealización de Taylor y los métodos de remuestreo. En el contexto de encuestas complejas, la función `survey_ratio()` permite estimar razones poblacionales y obtener sus correspondientes medidas de precisión, incorporando adecuadamente las características del diseño muestral.\n\nComo primer ejemplo de aplicación, se estima la razón entre el número de mujeres y el número de hombres en la población representada por la base de datos. Este indicador permite examinar la composición de la población por sexo y detectar posibles diferencias en la presencia relativa de ambos grupos. Aunque está estrechamente relacionado con el índice de feminidad, en este caso se expresa directamente como una razón y, por tanto, no se multiplica por 100.\n\nUn valor igual a 1 indica que existe el mismo número de mujeres y hombres; un valor superior a 1 refleja una mayor cantidad de mujeres, mientras que un valor inferior a 1 señala una mayor cantidad de hombres. Por ejemplo, una razón de 1,05 indica que existen aproximadamente 1,05 mujeres por cada hombre, lo que equivale a una presencia ligeramente mayor de mujeres en la población. El procedimiento de estimación y los resultados obtenidos se presentan en la @tbl-razon-sexo:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(ratio = survey_ratio(\n    numerator = (Sex == \"Female\"),\n    denominator = (Sex == \"Male\"),\n    level = 0.95,\n    vartype = c(\"se\", \"ci\")\n  ))\n```\n:::\n\n\n::: {#tbl-razon-sexo .cell layout-align=\"center\" tbl-cap='Razón de mujeres por hombre en la población'}\n::: {.cell-output-display}\n\n\n| ratio| ratio_se| ratio_low| ratio_upp|\n|-----:|--------:|---------:|---------:|\n|  1.11|    0.035|      1.04|      1.18|\n\n\n:::\n:::\n\n\nDado que la variable sexo en la base de datos es categórica, fue necesario acudir a variables indicadoras para realizar el cálculo de la razón, utilizando `Sex == \"Female\"` para identificar a las mujeres y `Sex == \"Male\"` para los hombres. Los resultados muestran que en la población analizada hay una mayor cantidad de mujeres que de hombres, obteniéndose una razón estimada de 1.11. Esto indica que, por cada 100 hombres, existen aproximadamente 111 mujeres. Además, el intervalo de confianza al 95% sugiere que esta razón podría variar entre 1.04 y 1.18. La @tbl-razon-sexo-rural presenta la estimación de esta razón en la zona rural. Esta salida se obtuvo con la ejecución del siguiente código:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrural_subset <- survey_design %>%\n  filter(Zone == \"Rural\")\n\nrural_subset %>%\n  summarise(ratio = survey_ratio(\n    numerator = (Sex == \"Female\"),\n    denominator = (Sex == \"Male\"),\n    level = 0.95,\n    vartype = c(\"se\", \"ci\")\n  ))\n```\n:::\n\n\n::: {#tbl-razon-sexo-rural .cell layout-align=\"center\" tbl-cap='Razón de mujeres por hombre en zona rural'}\n::: {.cell-output-display}\n\n\n| ratio| ratio_se| ratio_low| ratio_upp|\n|-----:|--------:|---------:|---------:|\n|  1.07|    0.035|     0.997|      1.14|\n\n\n:::\n:::\n\n\n\nLa razón estimada entre el número de mujeres y el número de hombres en la zona rural es de 1,07, lo que indica que el número de mujeres es cerca de un 7 % mayor que el de hombres. El intervalo de confianza se extiende de 0,997 a 1,14. Dado que el intervalo de confianza incluye el valor 1, no existe evidencia suficiente para concluir que la cantidad de mujeres difiere de la cantidad de hombres en la zona rural. \n\nOtro ejemplo frecuente de estimación de razones en las encuestas de hogares es la razón entre el gasto y el ingreso, la cual permite analizar patrones de consumo y aproximarse a la capacidad de los hogares para sostener sus niveles de gasto [@OECD2013ICW]. A continuación, se muestra cómo estimar este indicador, cuyos resultados se presentan en la @tbl-razon-gasto-ingreso:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(ratio = survey_ratio(\n    numerator = Expenditure,\n    denominator = Income,\n    level = 0.95,\n    vartype = c(\"se\", \"ci\")\n  ))\n```\n:::\n\n\n::: {#tbl-razon-gasto-ingreso .cell layout-align=\"center\" tbl-cap='Razón gasto/ingreso de los hogares'}\n::: {.cell-output-display}\n\n\n| ratio| ratio_se| ratio_low| ratio_upp|\n|-----:|--------:|---------:|---------:|\n| 0.649|    0.023|     0.603|     0.695|\n\n\n:::\n:::\n\n\nEn este caso, se especificaron la variable de gasto como numerador (`numerator`), la variable de ingreso como denominador (`denominator`), el nivel de confianza (`level`) utilizado para la construcción de los intervalos de confianza y las medidas de precisión requeridas mediante el argumento (`vartype`). Como se puede observar, la razón entre el gasto y el ingreso es cercana a 0.65. Esto implica que, por cada 100 dólares que ingresan al hogar, se gastan aproximadamente 65; el intervalo de confianza al 95% va de 0.60 a 0.69.\n\nAhora bien, otro análisis de interés es estimar la razón de gastos en cada una de las regiones. A continuación, se presentan los códigos computacionales, los cuales dan origen a las estimaciones presentadas en la @tbl-razon-gasto-ingreso-reg.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Region) %>%\n  summarise(ratio = survey_ratio(\n    numerator = Expenditure,\n    denominator = Income,\n    level = 0.95,\n    vartype = c(\"se\", \"ci\")\n  ))\n```\n:::\n\n\n\n::: {#tbl-razon-gasto-ingreso-reg .cell layout-align=\"center\" tbl-cap='Razón gasto/ingreso para las regiones'}\n::: {.cell-output-display}\n\n\n|Region    | ratio| ratio_se| ratio_low| ratio_upp|\n|:---------|-----:|--------:|---------:|---------:|\n|Norte     | 0.627|    0.034|     0.559|     0.695|\n|Sur       | 0.674|    0.062|     0.553|     0.796|\n|Centro    | 0.752|    0.043|     0.667|     0.837|\n|Occidente | 0.606|    0.042|     0.522|     0.690|\n|Oriente   | 0.600|    0.054|     0.493|     0.708|\n\n\n:::\n:::\n\n\nLa razón entre el gasto y el ingreso presenta diferencias entre las regiones. No obstante, los intervalos de confianza se superponen ampliamente, por lo que las diferencias observadas entre las regiones no necesariamente representan diferencias estadísticamente significativas. En conjunto, los resultados indican que los hogares destinan, en promedio, entre el 60 % y el 75 % de sus ingresos al gasto, con una mayor proporción en la región Centro.\n\n\n## Estimación de parámetros de distribución y desigualdad {#estimacion-de-parametros-de-distribucion-y-desigualdad}\n\nEl análisis de encuestas de hogares no se limita a la estimación de medidas descriptivas, pues también resulta fundamental describir la dispersión, la posición relativa de las observaciones y el grado de desigualdad de la distribución de las variables. Debido a su naturaleza no lineal, la forma funcional de los estimadores y la cuantificación de su incertidumbre deben tratarse usando procedimientos de linealización de Taylor o los métodos de replicación.\n\n\n### Varianza y desviación estándar {#estimacion-de-la-dispersion}\n\nEn las encuestas de hogares, la estimación de medidas de dispersión es fundamental para evaluar el grado de heterogeneidad de la población respecto de las variables analizadas. @SAS2012StdDev afimra que, ya sea que una encuesta mida el consumo de alcohol en la población adulta o el índice de masa corporal de los niños en edad escolar, una desviación estándar poblacional pequeña indica una mayor homogeneidad en la población, mientras que una desviación estándar grande indica una población más heterogénea.\n\nEn particular, estudiar la variabilidad de los ingresos permite identificar diferencias económicas entre los hogares y aporta información relevante para el diagnóstico de la desigualdad y el diseño de políticas públicas. Una de las medidas de dispersión más utilizadas es la desviación estándar, que cuantifica cuánto se alejan, en promedio, los valores respecto de la media. Una desviación estándar pequeña indica que los ingresos se encuentran relativamente concentrados alrededor del promedio y, por tanto, que la población es más homogénea en términos económicos. Por el contrario, una desviación estándar elevada refleja una mayor dispersión y, en consecuencia, diferencias más marcadas entre los ingresos de los hogares. \n\nDe acuerdo con @HeeringaWestBerglund2017, la desviación estándar poblacional se estima mediante una transformación no lineal del estimador de la varianza poblacional, $\\hat{S}_y^2$. Esta transformación incorpora, además, una corrección por grados de libertad basada en el número de observaciones válidas, denotado por $n$. En consecuencia, el estimador de la desviación estándar poblacional se expresa como:\n\n$$\n\\hat s_y  =\n\\sqrt{\\frac{n}{n-1} \\cdot \\hat{S}^2_y} =  \\sqrt{\\frac{n}{n-1}\\frac{\\sum_{h}\\sum_{i}\\sum_{k} w_{hik} \\ \\left(y_{hik}-\\hat{\\bar{y}}\\right)^{2}}{\\sum_{h}\\sum_{i}\\sum_{k} w_{hik}}}\n$$\n\nEl error estándar de este estimador puede aproximarse mediante linealización de Taylor o, equivalentemente, mediante el método delta [sarndal2003model]. Para estimar la desviación estándar de una variable numérica en encuestas de hogares mediante `R`, se estima primero la varianza poblacional con la función `survey_var()` y, posteriormente, se obtiene su raíz cuadrada. A continuación, se ilustra este procedimiento mediante la estimación de la desviación estándar del ingreso desagregada por zona.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(\n    Var = survey_var(\n      Income,\n      level = 0.95,\n      vartype = c(\"se\", \"ci\"),\n      na.rm = TRUE\n    )\n  ) %>%\n  mutate(\n    Sd     = sqrt(Var),\n    Sd_low = sqrt(Var_low),\n    Sd_upp = sqrt(Var_upp)\n  )\n```\n:::\n\n\n::: {#tbl-sd-ingreso-zona .cell layout-align=\"center\" tbl-cap='Desviación estándar de los ingresos desagregada por zona'}\n::: {.cell-output-display}\n\n\n|Zone  |    Var| Var_se| Var_low| Var_upp|  Sd| Sd_low| Sd_upp|\n|:-----|------:|------:|-------:|-------:|---:|------:|------:|\n|Rural |  96274|  13794|   68960|  123588| 310|    263|    352|\n|Urban | 338628|  81241|  177763|  499494| 582|    422|    707|\n\n\n:::\n:::\n\n\nLos argumentos de la función `survey_var()` son equivalentes a los utilizados previamente para la estimación de medias y totales. Los resultados de la @tbl-sd-ingreso-zona muestran que los ingresos presentan una dispersión considerablemente mayor en la zona urbana que en la rural. En la zona rural, la desviación estándar alcanza 310 dólares, mientras que en la zona rural se eleva a 582 dólares. Además, los intervalos de confianza de las desviaciones estándar no se superponen, lo que proporciona evidencia de que la variabilidad de los ingresos es efectivamente mayor en las áreas urbanas. \n\n### Percentiles y medianas {#estimacion-de-percentiles}\n\nLos percentiles permiten identificar puntos específicos de la distribución de una variable de interés y determinar los valores por debajo de los cuales se encuentra una proporción determinada de la población. En las encuestas de hogares, estas medidas resultan especialmente útiles para caracterizar la distribución de variables económicas y sociales, como el ingreso, el gasto o las horas trabajadas. Por ejemplo, los percentiles de ingreso pueden utilizarse para identificar a la población perteneciente al 10% superior de la distribución con fines tributarios [@UNECE2011Canberra], o para focalizar subsidios dirigidos a los hogares ubicados en los percentiles más bajos. La mediana, correspondinte al valor que divide a la población en dos partes iguales es poco sensible a valores extremos, razón por la cual suele considerarse una medida robusta de tendencia central.\n\nLos percentiles constituyen un caso particular de los cuantiles. En términos generales, el cuantil de orden $q$ (con $0 < q < 1$) es el valor que deja por debajo una proporción $q$ de la población. Cuando esta proporción se expresa en una escala de 0 a 100, el cuantil se denomina percentil. La estimación de cuantiles en encuestas complejas se basa en el uso de estimadores ponderados y en la estimación de la función de distribución acumulada (FDA) de la población [@SchulzeWaltrupKauermann2016]. Para una población finita de tamaño $N$, un estimador de esta distribución está dado por:\n\n$$\n\\hat{F}\\left(x\\right) = \\frac{\\sum_{h} \\sum_{i} \\sum_{k} w_{hik} \\ I\\left(y_{k}\\leq x\\right)}{\\sum_{h}\\sum_{i}\\sum_{k} w_{hik}}\n$$\n\nen donde la función $I\\left(y_{k}\\leq x\\right)$ es una variable indicadora que toma el valor uno si $y_k \\leq x$ y cero en otro caso. Una vez estimada la FDA utilizando los pesos del diseño muestral, el cuantil $q$-ésimo de una variable $y$ se define como el menor valor de $y$ para el cual la FDA es mayor o igual que $q$. En particular, la mediana estimada es el valor donde la FDA estimada es mayor o igual a 0.5. Para la estimación de cuantiles en encuestas complejas, se ordenan las observaciones en orden ascendente (estadísticas de orden) de forma que $y_{(1)} \\leq y_{(2)} \\leq \\ldots \\leq y_{(n)}$ y se identifica el valor de $j$ $(j=1,\\ldots,n)$ tal que:\n\n$$\n\\hat{F}\\left(y_{(j)}\\right)\\leq q\\leq\\hat{F}\\left(y_{(j+1)}\\right)\n$$\n\nBajo esta condición, el estimador del cuantil $q$-ésimo se obtiene mediante interpolación lineal, la cual permite obtener estimaciones más estables y precisas de los cuantiles, especialmente cuando la FDA presenta saltos importantes asociados al uso de pesos muestrales.\n\n@Woodruff1952 propone el método de inversión de la función de distribución acumulada como procedimiento para construir intervalos de confianza de cuantiles. Por su parte, @kovar1988 analiza la estimación de la varianza y la construcción de intervalos de confianza para percentiles y medianas, y muestra que los métodos de replicación presentan un desempeño satisfactorio para estos parámetros no lineales en encuestas con diseños muestrales complejos.\n\nTanto los estimadores de cuantiles como los métodos para estimar sus varianzas se encuentran implementados en `R`. En particular, la función `survey_median()` permite estimar la mediana y obtener, de manera conjunta, su error estándar y su intervalo de confianza. Al igual que otros parámetros poblacionales, la mediana puede estimarse para diferentes dominios de estudio, como la zona geográfica, el sexo o los grupos de edad. A continuación, se presenta la sintaxis empleada para estimar la mediana del gasto de los hogares por zona a partir de la base de datos de ejemplo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(\n    median = survey_median(Expenditure, \n                           level = 0.95, \n                           vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-mediana-gasto-zona .cell layout-align=\"center\" tbl-cap='Estimación de la mediana de los gastos desagregada por zona'}\n::: {.cell-output-display}\n\n\n|Zone  | median| median_se| median_low| median_upp|\n|:-----|------:|---------:|----------:|----------:|\n|Rural |    241|      11.0|        214|        258|\n|Urban |    381|      19.8|        337|        416|\n\n\n:::\n:::\n\n\nA partir de la @tbl-mediana-gasto-zona se concluye que el ingreso mediano presenta una diferencia importante entre zonas. En el área rural, la mediana estimada es de 241 dólares, lo que indica que la mitad de la población rural tiene ingresos inferiores a este valor y la otra mitad registra ingresos superiores. En la zona urbana, la mediana asciende a 381 dólares, es decir, aproximadamente un 58 % más que en la zona rural. Los intervalos de confianza no se superponen, lo que sugiere una diferencia clara en los niveles centrales de ingreso entre ambas zonas. Aunque la estimación urbana presenta un error estándar mayor, los resultados muestran consistentemente que el ingreso mediano es más elevado en las áreas urbanas.\n\nCuando el objetivo es estimar un percentil distinto de la mediana, puede utilizarse la función `survey_quantile()`. De acuerdo con @DorfmanValliant1993, algunos procedimientos para construir intervalos de confianza de cuantiles pueden presentar un desempeño menos satisfactorio que otras alternativas disponibles. En particular, el argumento `interval_type = \"score\"` emplea un método de inversión para determinar los límites del intervalo, en lugar de calcularlos directamente a partir de la función de influencia del percentil. \n\nA modo de ejemplo, a continuación se presenta la sintaxis para estimar el percentil 25 del gasto. Los resultados obtenidos se muestran en la @tbl-cuantil-gasto.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  summarise(\n    quantile = survey_quantile(\n      Expenditure,\n      quantiles = 0.25,\n      level = 0.95,\n      vartype = c(\"se\", \"ci\"),\n      interval_type = \"score\"\n    )\n  )\n```\n:::\n\n\n::: {#tbl-cuantil-gasto .cell layout-align=\"center\" tbl-cap='Estimación del primer cuartil de los gastos de los hogares'}\n::: {.cell-output-display}\n\n\n| quantile_q25| quantile_q25_se| quantile_q25_low| quantile_q25_upp|\n|------------:|---------------:|----------------:|----------------:|\n|          200|            13.8|              163|              218|\n\n\n:::\n:::\n\n\nDe los resultados anteriores, el percentil 25 del gasto se estima en 200 dólares, lo que indica que aproximadamente una cuarta parte de la población presenta niveles de gasto iguales o inferiores a este valor, mientras que el 75 % restante registra gastos superiores. El error estándar de 13,8 dólares refleja la incertidumbre asociada a la estimación.\n\n### El coeficiente de Gini y la curva de Lorenz {#estimacion-del-coeficiente-de-gini}\n\nEl tema sobre desigualdad económica trasciende el ámbito estrictamente estadístico y constituye uno de los temas centrales del análisis social contemporáneo. La desigualdad económica se relaciona con la persistencia de brechas en el acceso a oportunidades, la baja movilidad social y el debilitamiento de la cohesión social. En este contexto, su medición rigurosa resulta fundamental para producir diagnósticos sólidos y orientar el diseño, la implementación y la evaluación de políticas públicas integrales dirigidas a reducir las desigualdades y promover el desarrollo social inclusivo [@CEPAL2025PanoramaSocial, pp. 32-33].\n\nEntre los indicadores más ampliamente utilizados para cuantificar la desigualdad económica se encuentra el coeficiente de Gini ($G$), el cual mide el grado de concentración del ingreso comparando la distribución observada con una situación hipotética de igualdad perfecta. Este coeficiente toma valores entre 0 y 1, donde $G = 0$ representa igualdad perfecta y $G = 1$ corresponde al máximo nivel de desigualdad posible. En consecuencia, cuanto más cercano a uno sea el coeficiente, mayor será la concentración del ingreso en una proporción reducida de la población.\n\nEn el contexto de las encuestas de hogares, la estimación del coeficiente de Gini debe incorporar adecuadamente las características del diseño muestral, incluyendo los factores de expansión, la estratificación y la conglomeración. Siguiendo a @BinderKovacevic1995 y @LangelTille2013, el estimador ponderado del coeficiente de Gini puede expresarse en función de la posición acumulada de cada observación en la distribución del ingreso, así:\n\n$$\n\\hat{G} = \\frac{2\\sum_{h}\\sum_{i}\\sum_{k}w_{hik}^{*}\n\\ \\hat{F}_{hik} \\ y_{hik}}{\\hat{\\bar{y}}}-1\n$$\n\ndonde $w_{hik}^{*}=\\dfrac{w_{hik}}{\\sum_{h}\\sum_{i}\\sum_{k}w_{hik}}$ corresponde al peso muestral normalizado, $\\hat{F}_{hik}$ representa la función de distribución acumulada (FDA) estimada para la observación $k$ dentro del conglomerado $i$ del estrato $h$, y $\\hat{\\bar{y}}$ denota la media ponderada de la variable de ingreso en la población.\n\nCon respecto a la estimación de la varianza, @osier2009variance desarrolla un procedimiento de linealización que aproxima el estimador no lineal mediante una variable linealizada. A partir de este desarrollo, @convey2024 presenta su implementación en `R` mediante la función `svygini()`. Para ello, primero se prepara el diseño muestral mediante `convey_prep()`. Luego, la función `svygini()` calcula el índice de Gini utilizando la variable de ingreso y el diseño de encuesta complejo especificado. \n\nA continuación, se presenta la sintaxis utilizada para estimar el coeficiente de Gini en la base de datos de ejemplo, cuyos resultados se muestran en la @tbl-gini.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(convey)\ngini_design <- convey_prep(survey_design)\ngini <- svygini( ~ Income, design = gini_design)\n\ndata.frame(\n  Gini = coef(gini),\n  standard_error = SE(gini),\n  ci_lower = confint(gini)[1],\n  ci_upper = confint(gini)[2]\n)\n```\n:::\n\n\n\n::: {#tbl-gini .cell layout-align=\"center\" tbl-cap='Estimación del coeficiente de Gini para el ingreso de los hogares'}\n::: {.cell-output-display}\n\n\n|       |  Gini| Income| ci_lower| ci_upper|\n|:------|-----:|------:|--------:|--------:|\n|Income | 0.413|  0.019|    0.377|     0.45|\n\n\n:::\n:::\n\n\nEl coeficiente de Gini estimado indica un grado apreciable de desigualdad en la distribución del ingreso y evidencia una concentración relevante de los ingresos en una parte de la población. \n\nPor su parte, la curva de Lorenz representa gráficamente la distribución del ingreso mediante la relación entre la proporción acumulada de la población, ordenada de menor a mayor ingreso, y la proporción acumulada del ingreso total que le corresponde [@Lorenz1905]. La diagonal de 45 grados representa una situación hipotética de igualdad perfecta, en la que cada proporción acumulada de la población concentra una proporción equivalente del ingreso total. \n\nEl coeficiente de Gini se obtiene como la razón entre el área comprendida entre la curva de Lorenz y la línea de igualdad y el área total situada bajo dicha línea [@Deaton1997]. Dado que esta última área es igual a un medio, el coeficiente también puede expresarse como el doble del área situada entre ambas curvas. En consecuencia, cuanto más próxima se encuentre la curva de Lorenz a la línea de igualdad, más equitativa será la distribución del ingreso; por el contrario, una mayor distancia entre ambas indica un grado más elevado de desigualdad.\n\nEn encuestas con diseños muestrales complejos, la estimación de las ordenadas de la curva de Lorenz y de sus varianzas debe incorporar las ponderaciones y las demás características del diseño muestral [@KovacevicBinder1997]. Para realizar la curva de Lorenz en `R` se utiliza la función `svylorenz()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclorenz <- svylorenz(\n  formula = ~Income,\n  design = gini_design,\n  quantiles = seq(0, 1, .05),\n  alpha = .01,\n  plot = TRUE\n)\n```\n\n::: {.cell-output-display}\n![Curva de Lorenz estimada para el ingreso de los hogares](../figures/fig-lorenz-1.png){#fig-lorenz fig-align='center' width=65%}\n:::\n:::\n\n\nEl argumento `formula = ~Income` especifica la variable de ingreso sobre la cual se calculará la distribución acumulada. El argumento `design = gini_design` indica el objeto de diseño muestral previamente definido, el cual contiene la información relacionada con pesos, estratos y conglomerados de la encuesta. Por su parte, `quantiles = seq(0, 1, .05)` define los puntos de la distribución en los cuales se evaluará la curva de Lorenz, generando percentiles desde 0 hasta 1 en incrementos de 0.05. Finalmente, el argumento `alpha = .01` establece un nivel de significación del 1%, lo que equivale a construir intervalos de confianza del 99% para las estimaciones asociadas a la curva.\n\nA partir de la @fig-lorenz, se observa un grado considerable de desigualdad en la distribución del ingreso per cápita, dado que la curva de Lorenz se sitúa claramente por debajo de la línea de igualdad perfecta. Su marcada curvatura muestra que los grupos ubicados en la parte inferior de la distribución concentran una proporción reducida del ingreso total, mientras que una participación considerable se acumula entre las personas de mayores ingresos. La separación entre ambas líneas se amplía progresivamente hacia los tramos superiores, lo que refleja una mayor concentración del ingreso en estos grupos. Por su parte, la banda sombreada representa la incertidumbre asociada a la estimación de la curva.\n\n### Correlaciones {#estimacion-de-la-correlacion}\n\nEn el estudio de encuestas de hogares, además de describir variables de forma individual, es importante analizar cómo se relacionan dos variables entre sí. Una de las herramientas más utilizadas para este propósito es el coeficiente de correlación de Pearson, el cual mide la fuerza y la dirección de la relación lineal entre dos variables numéricas. Este coeficiente toma valores entre –1 y 1. Un valor positivo indica que ambas variables tienden a aumentar simultáneamente, mientras que un valor negativo señala que cuando una variable aumenta, la otra tiende a disminuir. Por su parte, valores cercanos a cero sugieren la ausencia de una relación lineal fuerte entre las variables analizadas. Por ejemplo, en una encuesta de hogares puede ser de interés estudiar qué tan fuerte es la asociación entre el ingreso de los hogares y su nivel de gasto. Este tipo de análisis permite comprender mejor los patrones económicos y sociales en la población. \n\nSupóngase que se dispone de dos variables numéricas de interés, denotadas por $x$ y $y$, observadas en la encuesta compleja. De acuerdo con @HeeringaWestBerglund2017, la asociación lineal entre ambas variables puede estimarse mediante el coeficiente de correlación de Pearson ponderado, definido como la covarianza ponderada entre $x$ y $y$ dividida por el producto de sus desviaciones estándar ponderadas. Esta estandarización elimina la influencia de las unidades de medida y permite evaluar tanto la dirección como la intensidad de la relación lineal. Si $\\hat{\\bar{x}}$ y $\\hat{\\bar{y}}$ representan las estimaciones de las medias poblacionales de $x$ y $y$, respectivamente, el coeficiente de correlación ponderado se expresa como:\n\n$$\n\\hat{\\rho}_{xy} = \\frac{\\displaystyle \\sum_{h} \\sum_{i} \\sum_{k} w_{hik} (y_{hik} - \\hat{\\bar{y}})(x_{hik} - \\hat{\\bar{x}})} {\\sqrt{\\displaystyle \\sum_{h} \\sum_{i} \\sum_{k} w_{hik} (y_{hik} - \\hat{\\bar{y}})^2} \\sqrt{\\displaystyle \\sum_{h} \\sum_{i} \\sum_{k} w_{hik} (x_{hik} - \\hat{\\bar{x}})^2}}\n$$\n\n\nEl paquete `survey` cuenta con la función `svyvar()` que permite obtener matrices de covarianzas ponderadas, a partir de las cuales se puede calcular la correlación. La @tbl-covarianza presenta un ejemplo de estimación para la matriz de varianzas y covarianzas entre el ingreso y el gasto de los hogares.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncov_matrix <- svyvar(~Income + Expenditure, design = survey_design)\n```\n:::\n\n\n\n\n::: {#tbl-covarianza .cell layout-align=\"center\" tbl-cap='Matriz de varianzas y covarianzas ponderada entre ingreso y gasto'}\n::: {.cell-output-display}\n\n\n|            |Variable    | Income| Expenditure|\n|:-----------|:-----------|------:|-----------:|\n|Income      |Income      | 243719|       98337|\n|Expenditure |Expenditure |  98337|       77887|\n\n\n:::\n:::\n\n\n\nLa función `svyvar` estima la matriz de varianzas y covarianzas considerando el diseño muestral. A partir de dicha matriz puede obtenerse la correlación aplicando las siguientes instrucciones:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncov_xy <- cov_matrix[1, 2]\nsd_x <- sqrt(cov_matrix[1, 1])\nsd_y <- sqrt(cov_matrix[2, 2])\n\nweighted_cor <- cov_xy / (sd_x * sd_y)\nweighted_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.714\n```\n\n\n:::\n:::\n\nSi además se desea realizar inferencia estadística sobre la correlación, por ejemplo obtener errores estándar o intervalos de confianza, pueden utilizarse métodos de replicación (bootstrap/jackknife) compatibles con el paquete `survey`. Otra opción es utilizar la función `svycor()` del paquete `jtools` [@jtools2026] para estimar directamente la correlación:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(jtools)\n\nsvycor(~Income + Expenditure, design = survey_design)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Income Expenditure\nIncome        1.00        0.71\nExpenditure   0.71        1.00\n```\n\n\n:::\n:::\n\n\nLa correlación entre el ingreso y el gasto es relativamente alta, con un coeficiente de Pearson estimado de 0,71. Esto indica que, en términos generales, los hogares con mayores ingresos tienden a registrar también niveles de gasto más elevados. Los valores iguales a 1 en la diagonal corresponden a la correlación de cada variable consigo misma. Finalmente, este resultado refleja una asociación lineal y no debe interpretarse como evidencia de una relación causal.\n\n\n## Pruebas de hipótesis {#pruebas-de-hipotesis}\n\nEn el análisis de datos provenientes de encuestas de hogares no basta con estudiar cada variable de manera aislada, como estimar el ingreso medio de hombres y mujeres en un país. También es fundamental comparar grupos y evaluar si las diferencias observadas entre ellos reflejan desigualdades reales en la población o si podrían explicarse simplemente por el error de muestreo. Por ejemplo, una pregunta frecuente consiste en determinar si existen diferencias estadísticamente significativas en el ingreso medio entre hogares dirigidos por hombres y hogares dirigidos por mujeres. Este tipo de análisis permite identificar brechas sociales y económicas, además de generar evidencia útil para el diseño y evaluación de políticas públicas.\n\nSegún @HeeringaWestBerglund2017, para responder este tipo de interrogantes se utilizan pruebas de hipótesis, es decir, procedimientos estadísticos que permiten contrastar afirmaciones sobre parámetros poblacionales utilizando la información observada en la muestra. En el contexto de encuestas de hogares, estas pruebas deben incorporar adecuadamente las características del diseño muestral con el fin de garantizar inferencias válidas y resultados confiables.\n\nLas pruebas de hipótesis constituyen una herramienta fundamental para evaluar afirmaciones sobre parámetros poblacionales a partir de la información observada en una muestra. En términos generales, toda prueba de hipótesis se basa en el contraste entre dos proposiciones opuestas: la hipótesis nula, denotada por $H_0$, y la hipótesis alternativa, denotada por $H_1$. En el caso más común de una prueba bilateral, estas hipótesis se expresan como:\n\n$$\n\\begin{cases}\nH_{0}: & \\theta = \\theta_0 \\\\\nH_{1}: & \\theta \\neq \\theta_0\n\\end{cases}\n$$\n\ndonde $\\theta$ representa el parámetro poblacional de interés y $\\theta_0$ un valor de referencia especificado bajo la hipótesis nula. Dependiendo del objetivo del análisis, la hipótesis alternativa también puede formularse de manera unilateral, por ejemplo, cuando se desea evaluar si $\\theta > \\theta_0$ o si $\\theta < \\theta_0$. El propósito de la prueba es determinar si la evidencia contenida en la muestra resulta suficientemente fuerte para rechazar la hipótesis nula en favor de la hipótesis alternativa.\n\nSupóngase que $\\bar{y}_1$ y $\\bar{y}_2$ representan las medias poblacionales de una variable $y$ en dos dominios distintos, por ejemplo, el ingreso medio de hogares con jefatura masculina y el ingreso medio de hogares con jefatura femenina. Entonces, el parámetro de interés corresponde a la diferencia:\n\n$$\n\\Delta = \\bar{y}_1 - \\bar{y}_2\n$$\n\nSu estimador muestral se define como:\n\n$$\n\\hat{\\Delta} = \\hat{\\bar{y}}_1 - \\hat{\\bar{y}}_2\n$$\n\nSu error estándar se estima mediante la siguiente expresión:\n\n$$\n\\widehat{se}(\\hat{\\Delta}) =\n\\sqrt{\n\\widehat{Var}(\\hat{\\bar{y}}_1)\n+\n\\widehat{Var}(\\hat{\\bar{y}}_2)\n-\n2\\widehat{Cov}(\\hat{\\bar{y}}_1, \\hat{\\bar{y}}_2)\n}\n$$\n\nLa presencia del término de covarianza es importante porque las estimaciones de ambos dominios suelen provenir de la misma muestra y, por tanto, no necesariamente son independientes. Una vez calculado el estimador y su error estándar, el contraste de hipótesis se realiza utilizando el siguiente estadístico de prueba:\n\n$$\nt =\n\\frac{\\hat{\\Delta}}\n{\\widehat{se}(\\hat{\\Delta})} \\sim t_{df}\n$$\n\nEste estadístico sigue aproximadamente una distribución $t$ de Student con $(df)$ grados de libertad. En la práctica, estos grados de libertad suelen aproximarse mediante $df = n_I - H$, donde $n_I$ representa el número de unidades primarias de muestreo y $H$ el número de estratos. Bajo la hipótesis nula, valores absolutos elevados del estadístico $t$ constituyen evidencia en contra de $H_0$. De manera complementaria, también puede construirse un intervalo de confianza para el parámetro $\\Delta$. Para un nivel de confianza de $(1-\\alpha)100\\%$, dicho intervalo está dado por:\n\n$$\n\\hat{\\Delta}\n\\;\\pm\\;\nt_{(1-\\alpha/2,df)}\n\\,\n\\hat{se}(\\hat{\\Delta}).\n$$\n\nEste intervalo proporciona un rango de valores plausibles para la diferencia poblacional y constituye una herramienta útil para evaluar tanto la magnitud como la significación estadística de las diferencias observadas entre grupos.\n\nEn `R`, estas pruebas pueden implementarse mediante la función `svyttest()` del paquete `survey`, la cual incorpora automáticamente los ajustes asociados al diseño muestral. A partir de los resultados presentados en la @tbl-ttest-sexo puede concluirse que, con un nivel de confianza del 95%, no existe evidencia estadística suficiente para afirmar que los ingresos medios difieren según el sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nttest_sex <- svyttest(Income ~ Sex, design = survey_design, level = 0.95)\n```\n:::\n\n\n\n::: {#tbl-ttest-sexo .cell layout-align=\"center\" tbl-cap='Prueba de diferencia de ingresos medios por sexo (población total)'}\n::: {.cell-output-display}\n\n\n| statistic| p_value|  gl| ci_lower| ci_upper| estimated_difference|\n|---------:|-------:|---:|--------:|--------:|--------------------:|\n|      1.36|   0.176| 118|    -12.8|     69.4|                 28.3|\n\n\n:::\n:::\n\n\nOtra hipótesis de interés consiste en evaluar si los ingresos medios de los hogares difieren según el sexo de la jefatura dentro del área urbana, como se presenta en la @tbl-ttest-sexo-urbano. Los resultados indican que no se rechaza la hipótesis nula $H_0$, por lo que no existe evidencia estadística suficiente para afirmar que los ingresos medios difieren por sexo en la zona urbana.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nurban_subset <- survey_design %>%\n  filter(Zone == \"Urban\")\n\nttest_urban <- svyttest(Income ~ Sex, design = urban_subset, level = 0.95)\n```\n:::\n\n\n\n\n\n::: {#tbl-ttest-sexo-urbano .cell layout-align=\"center\" tbl-cap='Prueba de diferencia de ingresos medios por sexo en zona urbana'}\n::: {.cell-output-display}\n\n\n| statistic| p_value| gl| ci_lower| ci_upper| estimated_difference|\n|---------:|-------:|--:|--------:|--------:|--------------------:|\n|      1.57|   0.122| 63|    -12.3|      102|                 44.7|\n\n\n:::\n:::\n\n\n\nComo plantea @Gutierrez2016, el procedimiento descrito no se limita a las medias, sino que también puede aplicarse a proporciones, totales, razones o cualquier función diferenciable de totales. En todos los casos, el contraste se fundamenta en la estimación puntual, su varianza (incluyendo covarianzas cuando corresponde) y la comparación con la distribución $t$ ajustada al diseño muestral.\n\n## Estimación de contrastes {#estimacion-de-contrastes}\n\nEn el análisis de encuestas de hogares es frecuente que el interés no se limite a comparar únicamente dos poblaciones, sino varias de manera simultánea. Por ejemplo, puede ser necesario comparar los ingresos medios de los hogares entre distintas regiones, áreas geográficas o grupos poblacionales, con el propósito de identificar diferencias y establecer patrones de desigualdad entre ellos. En este tipo de situaciones, las pruebas de diferencia de medias presentadas anteriormente resultan limitadas, ya que están diseñadas para comparar únicamente pares de poblaciones.\n\nSegún @HeeringaWestBerglund2017, para abordar comparaciones más generales se utilizan los contrastes, que constituyen una herramienta flexible para evaluar combinaciones lineales de parámetros poblacionales. En términos generales, un contraste se define como:\n\n$$\nf\\left(\\theta_1,\\theta_2,\\ldots,\\theta_J\\right)\n=\n\\sum_{j=1}^{J} a_j \\theta_j,\n$$\n\ndonde los coeficientes $a_j$ son constantes conocidas y $\\theta_j$ representan los parámetros de interés. Este enfoque permite formular y evaluar una amplia variedad de comparaciones entre grupos, incluyendo diferencias entre medias, comparaciones múltiples y combinaciones más complejas de parámetros.\n\nLos contrastes permiten comparar combinaciones lineales de parámetros estimados en diseños de muestreo complejos. En `R`, estos procedimientos se encuentran disponibles mediante la función `svycontrast()` del paquete `survey`. Por ejemplo, si se quiere comparar los ingresos medios de dos subpoblaciones particulares (las regiones Norte y Sur) se puede usar el contraste $\\bar{y}_{Norte} - \\bar{y}_{Sur}$. Dado que la muestra cubre cinco regiones en total, el contraste debe construirse asignando coeficientes únicamente a las regiones involucradas en la comparación y dejando coeficientes iguales a cero para las demás regiones. De esta manera, el contraste se define como:\n\n$$\n1\\times\\hat{\\bar{y}}_{Norte}+\\left(-1\\right)\\times\\hat{\\bar{y}}_{Sur}+0\\times\\hat{\\bar{y}}_{Centro}+0\\times\\hat{\\bar{y}}_{Occidente}+0\\times\\hat{\\bar{y}}_{Oriente}.\n$$\n\nEsta expresión indica que el contraste corresponde a la diferencia entre las medias estimadas de las regiones Norte y Sur, mientras que las demás regiones no participan en la comparación. De forma matricial, el contraste puede escribirse como:\n\n$$\n \\left[1,\\,-1,\\,0,\\,0,\\,0\\right]\n \\times\n \\left[\\begin{array}{c}\n\\hat{\\bar{y}}_{Norte}\\\\\n\\hat{\\bar{y}}_{Sur}\\\\\n\\hat{\\bar{y}}_{Centro}\\\\\n\\hat{\\bar{y}}_{Occidente}\\\\\n\\hat{\\bar{y}}_{Oriente}\n\\end{array}\\right].\n$$\n\nEn consecuencia, el vector de contraste asociado a esta comparación es $\\left[1,\\,-1,\\,0,\\,0,\\,0\\right]$, donde los coeficientes positivos y negativos indican las poblaciones que se desean comparar y los ceros representan las poblaciones excluidas del contraste. El primer paso consiste en calcular las medias estimadas para cada región mediante `group_by()` y `survey_mean()`, como se presenta en la @tbl-prom-region. El objeto visible de resultados se construye con `srvyr`; adicionalmente se crea un objeto auxiliar con matriz de covarianzas para los contrastes posteriores. Como resultado se obtienen las medias estimadas de los ingresos por región.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_mean <- survey_design %>%\n  group_by(Region) %>%\n  summarise(mean = survey_mean(Income,\n                               na.rm = TRUE,\n                               vartype = c(\"se\", \"ci\")))\n\nregion_mean_contrast <- svyby(formula = ~Income,\n                              by = ~Region,\n                              design = survey_design,\n                              FUN = svymean,\n                              na.rm = TRUE,\n                              covmat = TRUE,\n                              vartype = c(\"se\", \"ci\"))\n```\n:::\n\n\n\n::: {#tbl-prom-region .cell layout-align=\"center\" tbl-cap='Ingreso medio estimado por región'}\n::: {.cell-output-display}\n\n\n|Region    | mean| mean_se| mean_low| mean_upp|\n|:---------|----:|-------:|--------:|--------:|\n|Norte     |  552|    55.4|      443|      662|\n|Sur       |  626|    62.4|      502|      749|\n|Centro    |  651|    61.5|      529|      772|\n|Occidente |  517|    46.2|      425|      609|\n|Oriente   |  542|    71.7|      400|      684|\n\n\n:::\n:::\n\n\nLa función `svycontrast()` devuelve el contraste estimado y su error estándar. Los argumentos de esta función son los promedios de los ingresos estimados (`stat`) y las constantes de contraste (`contrasts`), como se muestra en la @tbl-contraste-ns.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrast_region_ns <- svycontrast(\n  stat = region_mean_contrast,\n  contrasts = list(north_south_difference = c(1, -1, 0, 0, 0))\n)\n```\n:::\n\n\n\n::: {#tbl-contraste-ns .cell layout-align=\"center\" tbl-cap='Contraste de ingresos medios: región Norte menos región Sur'}\n::: {.cell-output-display}\n\n\n|contrast               | estimate| variance| standard_error|\n|:----------------------|--------:|--------:|--------------:|\n|north_south_difference |    -73.4|     6959|           83.4|\n\n\n:::\n:::\n\n\n\nNótese que estos mismos resultados podrían obtenerse realizando explícitamente el proceso de construcción del estimador del contraste y de su varianza estimada. Si se consideran únicamente los ingresos medios estimados de las regiones Norte y Sur, su diferencia es:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Paso 1: diferencia de las estimaciones (Norte - Sur)\nregion_income_mean <- setNames(\n  as.numeric(region_mean_contrast[[\"Income\"]]),\n  region_mean_contrast[[\"Region\"]]\n)\n\nregion_income_mean[\"Norte\"] - region_income_mean[\"Sur\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNorte \n-73.4 \n```\n\n\n:::\n:::\n\n\nEl paso siguiente es calcular la matriz de varianzas y covarianzas y de allí extraer las varianzas y covarianzas de las regiones Norte y Sur, presentada en la @tbl-vcov-region:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Paso 2: matriz de varianzas y covarianzas\nregion_vcov <- vcov(region_mean_contrast)\n```\n:::\n\n\n\n\n::: {#tbl-vcov-region .cell layout-align=\"center\" tbl-cap='Matriz de varianzas y covarianzas de los ingresos medios por región'}\n::: {.cell-output-display}\n\n\n|Region    | Norte|  Sur| Centro| Occidente| Oriente|\n|:---------|-----:|----:|------:|---------:|-------:|\n|Norte     |  3065|    0|      0|         0|       0|\n|Sur       |     0| 3894|      0|         0|       0|\n|Centro    |     0|    0|   3778|         0|       0|\n|Occidente |     0|    0|      0|      2136|       0|\n|Oriente   |     0|    0|      0|         0|    5136|\n\n\n:::\n:::\n\n\nPara calcular el error estándar de la diferencia (contraste) se usarán las propiedades de la varianza, de la siguiente forma:\n\n$$\n\\widehat{se}\\left(\\hat{\\bar{y}}_{Norte}-\\hat{\\bar{y}}_{Sur}\\right)=\\sqrt{\\widehat {Var}\\left(\\hat{\\bar{y}}_{Norte}\\right)+\n\\widehat{Var}\\left(\\hat{\\bar{y}}_{Sur}\\right)-\n2\\, \\widehat{Cov}\\left(\\hat{\\bar{y}}_{Norte},\\hat{\\bar{y}}_{Sur}\\right)}\n$$\n\nPara evitar inconsistencias con valores redondeados, el cálculo se realiza directamente a partir de la matriz estimada:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsqrt(region_vcov[\"Norte\", \"Norte\"] +\n       region_vcov[\"Sur\", \"Sur\"] -\n       2 * region_vcov[\"Norte\", \"Sur\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 83.4\n```\n\n\n:::\n:::\n\n\nEste resultado corresponde al mismo obtenido anteriormente con la función `svycontrast()`. Además de comparar únicamente dos poblaciones, los contrastes permiten evaluar simultáneamente varias comparaciones de interés entre diferentes grupos.\n\nPor otro lado, supóngase que se desea comparar los ingresos medios entre distintas regiones geográficas. En particular, podrían considerarse contrastes como $\\bar{y}_{Norte} - \\bar{y}_{Centro}$, $\\bar{y}_{Sur} - \\bar{y}_{Centro}$ y $\\bar{y}_{Occidente} - \\bar{y}_{Oriente}$. Cada una de estas expresiones representa un contraste lineal específico entre medias regionales. De manera conjunta, dichos contrastes pueden organizarse mediante la siguiente matriz de contrastes:\n\n$$\n\\left[\\begin{array}{ccccc}\n1 & 0 & -1 & 0 & 0\\\\\n0 & 1 & -1 & 0 & 0\\\\\n0 & 0 & 0 & 1 & -1\n\\end{array}\\right]\n$$\n\nEn esta matriz, cada fila define un contraste distinto y cada columna corresponde a una de las regiones consideradas en el análisis. Los coeficientes positivos y negativos indican las medias que participan en cada comparación, mientras que los ceros representan las regiones que no intervienen en el contraste correspondiente. A continuación, se muestra la implementación de los contrastes en `R`, cuyos resultados se presentan en la @tbl-contraste-regiones. A partir de estos resultados, puede concluirse que las regiones Sur y Centro presentan los ingresos medios de los hogares más similares, dado que la diferencia estimada entre ambas regiones es la menor entre los contrastes evaluados.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrast_regions <- svycontrast(\n  stat = region_mean_contrast,\n  contrasts = list(\n    north_south = c(1, 0, -1, 0, 0),\n    south_center = c(0, 1, -1, 0, 0),\n    west_east = c(0, 0, 0, 1, -1)\n  )\n)\n```\n:::\n\n\n\n::: {#tbl-contraste-regiones .cell layout-align=\"center\" tbl-cap='Contrastes de ingresos medios entre regiones'}\n::: {.cell-output-display}\n\n\n|contrast     | estimate| variance| standard_error|\n|:------------|--------:|--------:|--------------:|\n|north_south  |    -98.4|     6843|           82.7|\n|south_center |    -25.0|     7673|           87.6|\n|west_east    |    -24.7|     7272|           85.3|\n\n\n:::\n:::\n\n\n\nTambién es posible construir contrastes entre variables asociadas a diferentes grupos poblacionales, como ocurre al comparar el ingreso medio según el sexo. Siguiendo el mismo procedimiento del ejemplo anterior, el primer paso consiste en estimar el ingreso medio para cada grupo, en este caso hombres y mujeres, como se presenta en la @tbl-prom-sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_mean <- survey_design %>%\n  group_by(Sex) %>%\n  summarise(mean = survey_mean(Income,\n                               na.rm = TRUE,\n                               vartype = c(\"se\", \"ci\")))\n\nsex_mean_contrast <- svyby(formula = ~Income,\n                           by = ~Sex,\n                           design = survey_design,\n                           FUN = svymean,\n                           na.rm = TRUE,\n                           covmat = TRUE,\n                           vartype = c(\"se\", \"ci\"))\n```\n:::\n\n\n\n\n::: {#tbl-prom-sexo .cell layout-align=\"center\" tbl-cap='Ingreso medio estimado por sexo'}\n::: {.cell-output-display}\n\n\n|Sex    | mean| mean_se| mean_low| mean_upp|\n|:------|----:|-------:|--------:|--------:|\n|Female |  558|    25.8|      506|      609|\n|Male   |  586|    34.6|      517|      654|\n\n\n:::\n:::\n\n\nEn este caso, el contraste de interés está dado por $\\bar{y}_{F} - \\bar{y}_{M}$, el cual permite cuantificar la diferencia entre el ingreso medio de las mujeres y el correspondiente a los hombres. A continuación, utilizando la función `svycontrast()` del paquete `survey`, se obtiene la estimación del contraste, cuyos resultados se presentan en la @tbl-contraste-sexo. A partir de estos resultados, se concluye que, en promedio, los hombres perciben 28.3 dólares más que las mujeres, con un error estándar estimado de 20.8 dólares.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrast_sex <- svycontrast(\n  stat = sex_mean_contrast,\n  contrasts = list(sex_difference = c(1, -1))\n)\n```\n:::\n\n\n\n\n::: {#tbl-contraste-sexo .cell layout-align=\"center\" tbl-cap='Contraste de ingresos medios entre mujeres y hombres'}\n::: {.cell-output-display}\n\n\n|contrast       | estimate| variance| standard_error|\n|:--------------|--------:|--------:|--------------:|\n|sex_difference |    -28.3|      431|           20.8|\n\n\n:::\n:::\n\n\n\nDado que los contrastes corresponden a funciones lineales de parámetros, también es posible aplicarlos a estimadores de razón. Un ejemplo de ello consiste en comparar la relación entre ingresos y gastos según el sexo. En este caso, primero se estima la razón ingreso-gasto para cada grupo y posteriormente se construye el contraste entre dichas razones. A continuación, se presentan los códigos computacionales utilizados para realizar este análisis, cuyos resultados se muestran en la @tbl-razon-ingreso-gasto-sexo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_ratio <- survey_design %>%\n  group_by(Sex) %>%\n  summarise(ratio = survey_ratio(Income,\n                                 Expenditure,\n                                 na.rm = TRUE,\n                                 vartype = c(\"se\", \"ci\")))\n\nsex_ratio_contrast <- svyby(formula = ~Income,\n                            by = ~Sex,\n                            denominator = ~Expenditure,\n                            design = survey_design,\n                            FUN = svyratio,\n                            na.rm = TRUE,\n                            covmat = TRUE,\n                            vartype = c(\"se\", \"ci\"))\n```\n:::\n\n\n\n\n::: {#tbl-razon-ingreso-gasto-sexo .cell layout-align=\"center\" tbl-cap='Razón ingreso/gasto desagregada por sexo'}\n::: {.cell-output-display}\n\n\n|Sex    | ratio| ratio_se| ratio_low| ratio_upp|\n|:------|-----:|--------:|---------:|---------:|\n|Female |  1.52|    0.046|      1.43|      1.61|\n|Male   |  1.56|    0.070|      1.42|      1.70|\n\n\n:::\n:::\n\n\nLa función `svycontrast()` no se limita únicamente a la comparación de medias o totales, sino que también permite construir contrastes entre otros parámetros de interés, como razones y proporciones estimadas a partir de diseños de muestreo complejos. A continuación, se presentan los códigos computacionales utilizados para realizar este análisis, cuyos resultados se muestran en la @tbl-contraste-razon-sexo. A partir de dichos resultados, puede concluirse que la diferencia entre las razones estimadas es de 0.046 a favor de los hombres.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrast_sex_ratio <- svycontrast(\n  stat = sex_ratio_contrast,\n  contrasts = list(sex_difference = c(1, -1))\n)\n```\n:::\n\n\n\n\n::: {#tbl-contraste-razon-sexo .cell layout-align=\"center\" tbl-cap='Contraste de la razón ingreso/gasto entre sexos'}\n::: {.cell-output-display}\n\n\n|contrast       | estimate| standard_error| variance|\n|:--------------|--------:|--------------:|--------:|\n|sex_difference |   -0.046|         0.0416|  0.00173|\n\n\n:::\n:::\n\n\n\n## Visualización de variables continuas {#viz-continuas}\n\nSegún @wilkinson2005grammar, la representación gráfica de variables continuas es un componente esencial en el análisis de encuestas de hogares. Los gráficos bien diseñados permiten identificar distribuciones, tendencias y relaciones entre variables, facilitando la interpretación de los hallazgos y su comunicación a distintos públicos. Un aspecto fundamental en este contexto es que los gráficos deben incorporar los pesos muestrales para reflejar la distribución de la población de interés.\n\nDe acuerdo con @patchwork y @ggplot22026, en esta sección se utilizan los paquetes `patchwork` y `ggplot2` para la composición y construcción de gráficos. Estas herramientas se combinan con `survey` y `srvyr`, respectivamente.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(patchwork)\ndata(BigCity, package = \"TeachingSampling\")\n```\n:::\n\n\n### Histogramas {#histogramas}\n\nUn histograma es una representación gráfica de la distribución de una variable numérica continua, construida a partir de rectángulos cuya altura es proporcional a la frecuencia de observaciones dentro de determinados intervalos de clase. En el contexto de encuestas de hogares, los histogramas ponderados permiten aproximar la distribución de la variable en la población, incorporando los factores de expansión asociados al diseño muestral.\n\nA continuación, se presenta el histograma ponderado de la variable `Income`, construido incorporando los pesos muestrales (`wk`) con el fin de representar la distribución estimada del ingreso en la población. Los resultados obtenidos se muestran en la @fig-hist-ingreso-ponde:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweighted_income_hist <- ggplot(\n  data = survey_data,\n  aes(x = Income, weight = wk)) +\n  geom_histogram(aes(y = ..density..)) +\n  ylab(\"\") +\n  ggtitle(\"Histograma ponderado\")\nweighted_income_hist\n```\n\n::: {.cell-output-display}\n![Histograma ponderado del ingreso de los hogares](../figures/fig-hist-ingreso-ponde-1.png){#fig-hist-ingreso-ponde fig-align='center' width=65%}\n:::\n:::\n\n\nEn este código, se inicia la construcción del gráfico utilizando la base de datos `survey_data`. Dentro de `aes()`, el argumento `x = Income` indica que la variable representada en el eje horizontal corresponde al ingreso, mientras que `weight = wk` incorpora los pesos muestrales para construir un histograma ponderado que refleje la distribución estimada en la población. La función `geom_histogram()` genera el histograma y, mediante `aes(y = ..density..)`, la altura de las barras se expresa en términos de densidad en lugar de frecuencias absolutas. Posteriormente, `ylab(\"\")` elimina la etiqueta del eje vertical, y `ggtitle(\"Histograma ponderado\")` agrega un título descriptivo al gráfico.\n\nLos histogramas también permiten comparar visualmente la distribución de una variable entre distintos subgrupos de la población mediante el argumento `fill`, el cual asigna un color diferente a cada categoría. Por ejemplo, es posible comparar la distribución del ingreso entre zonas urbanas y rurales, como se muestra en la @fig-hist-zona:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzone_colors <- c(Urban = \"#48C9B0\", Rural = \"#117864\")\n\nweighted_zone_hist <- ggplot(survey_data, aes(x = Income, weight = wk)) +\n  geom_histogram(\n    aes(y = ..density.., fill = Zone),\n    alpha = 0.5, position = \"identity\") +\n  scale_fill_manual(values = zone_colors) +\n  ylab(\"\") +\n  ggtitle(\"Weighted\")\n\nweighted_zone_hist\n```\n\n::: {.cell-output-display}\n![Histograma ponderado del ingreso por zona geográfica](../figures/fig-hist-zona-1.png){#fig-hist-zona fig-align='center' width=65%}\n:::\n:::\n\n\nEn este código, se construye un histograma ponderado utilizando la base de datos `survey_data`, donde `x = Income` define la variable representada en el eje horizontal y `weight = wk` incorpora los pesos muestrales para reflejar la distribución poblacional del ingreso. La función `geom_histogram()` genera el histograma y, mediante `aes(y = ..density.., fill = Zone)`, representa las barras en términos de densidad y asigna colores diferentes según la variable `Zone`, permitiendo comparar visualmente la distribución del ingreso entre zonas. El argumento `alpha = 0.5` agrega transparencia a las barras para facilitar la superposición de los histogramas, mientras que `position = \"identity\"` permite que las distribuciones se dibujen una encima de otra en lugar de apilarse. Posteriormente, `scale_fill_manual(values = zone_colors)` define manualmente los colores asociados a cada zona. Finalmente, `ylab(\"\")` elimina la etiqueta del eje vertical, `ggtitle(\"Weighted\")` agrega un título al gráfico.\n\nAdicionalmente, es posible superponer curvas de densidad suavizadas mediante la función `geom_density()`, lo que permite visualizar de manera continua la forma de la distribución de la variable analizada. Este tipo de representación facilita la identificación de patrones como asimetrías, concentración de observaciones o la presencia de múltiples modas. Un ejemplo de este tipo de gráfico se presenta en la @fig-densidades:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweighted_income_hist + geom_density(fill = \"blue\", alpha = 0.3) |\n  weighted_zone_hist + geom_density(aes(fill = Zone), alpha = 0.3) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Histogramas con curvas de densidad superpuestas para ingreso y gasto](../figures/fig-densidades-1.png){#fig-densidades fig-align='center' width=90%}\n:::\n:::\n\n\n### Diagramas de caja (*boxplots*) {#diagramas-de-caja-boxplots}\n\nIntroducidos por @Tukey1977EDA, los diagramas de caja (*boxplots*) permiten identificar valores atípicos y evaluar la dispersión de la distribución. Son una representación gráfica que resume una variable mediante estadísticas basadas en cuartiles, permitiendo identificar la mediana, la dispersión de los datos y la presencia de valores atípicos. En el contexto de encuestas de hogares, este tipo de gráfico resulta útil para comparar distribuciones entre distintos grupos poblacionales de manera compacta y visualmente intuitiva.\n\nPara construir *boxplots* ponderados en `ggplot2` se utiliza la función `geom_boxplot()`, como se muestra en la @fig-boxplot-zona-sexo. En este caso, la función `ggplot()` inicia la construcción del gráfico utilizando la base de datos `survey_data`, donde `x = Income` define la variable numérica analizada y `weight = wk` incorpora los pesos muestrales para representar la distribución estimada en la población. Posteriormente, `geom_boxplot()` genera los diagramas de caja y, mediante `aes(fill = Zone)` o `aes(fill = Sex)`, asigna colores diferentes a cada categoría de las variables `Zone` y `Sex`, respectivamente, facilitando la comparación visual entre grupos. La función `coord_flip()` invierte los ejes para presentar los *boxplots* de forma horizontal, mejorando así su legibilidad. Por su parte, `scale_fill_manual()` permite definir manualmente los colores asociados a cada categoría mediante los vectores `zone_colors` y `sex_colors`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweighted_zone_boxplot <- ggplot(survey_data, aes(x = Income, weight = wk)) +\n  geom_boxplot(aes(fill = Zone)) +\n  ggtitle(\"Weighted\") +\n  coord_flip() +\n  scale_fill_manual(values = zone_colors)\n\nsex_colors <- c(Male = \"#5DADE2\", Female = \"#2874A6\")\n\nweighted_sex_boxplot <- ggplot(survey_data, aes(x = Income, weight = wk)) +\n  geom_boxplot(aes(fill = Sex)) +\n  ggtitle(\"Weighted\") +\n  coord_flip() +\n  scale_fill_manual(values = sex_colors)\n\nweighted_zone_boxplot | weighted_sex_boxplot\n```\n\n::: {.cell-output-display}\n![Boxplots ponderados del ingreso por zona y sexo](../figures/fig-boxplot-zona-sexo-1.png){#fig-boxplot-zona-sexo fig-align='center' width=90%}\n:::\n:::\n\n\nAdemás de las herramientas disponibles en `ggplot2`, las funciones especializadas `svyhist()` y `svyboxplot()` del paquete `survey` incorporan directamente las características del diseño muestral complejo en la construcción de los gráficos. Estas funciones permiten obtener representaciones gráficas coherentes con el diseño de la encuesta, facilitando el análisis exploratorio de las variables numéricas. Un ejemplo de su aplicación se presenta en la @fig-svyhist-svybox.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nold_par <- par(no.readonly = TRUE)\npar(mfrow = c(1, 2))\nsvyhist(~Income, survey_design,\n  main = \"Household income\",\n  col  = \"grey80\", xlab = \"Income\",\n  probability = FALSE)\n\nsvyboxplot(Income ~ Zone, survey_design,\n  col  = \"grey80\",\n  ylab = \"Income\", xlab = \"Zone\")\npar(old_par)\n```\n\n::: {.cell-output-display}\n![Histograma y boxplot del ingreso ajustados al diseño muestral complejo](../figures/fig-svyhist-svybox-1.png){#fig-svyhist-svybox fig-align='center' width=80%}\n:::\n:::\n\n\n### Diagramas de dispersión {#diagramas-de-dispersion}\n\nLos diagramas de dispersión permiten explorar visualmente la relación entre dos variables continuas, facilitando la identificación de patrones de asociación, tendencias y posibles valores atípicos. En el contexto de encuestas con diseños muestrales complejos, resulta importante incorporar la información de los pesos de muestreo para que la representación gráfica refleje adecuadamente la contribución relativa de cada observación en la población.\n\nCuando se trabaja con conjuntos de datos de gran tamaño, representar todos los puntos simultáneamente puede generar gráficos difíciles de interpretar debido a la sobreposición de observaciones. Sin embargo, en muestras de tamaño moderado, una estrategia sencilla y efectiva consiste en representar los pesos mediante el tamaño de los símbolos en el gráfico de dispersión. De esta manera, las observaciones con mayor peso poblacional aparecen resaltadas visualmente. Un ejemplo de este tipo de representación se presenta en la @fig-scatter-basico:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweighted_basic_scatter <- ggplot(\n  data = survey_data,\n  aes(y = Income, x = Expenditure)) +\n  geom_point(aes(size = wk), alpha = 0.3)\n\nweighted_basic_scatter\n```\n\n::: {.cell-output-display}\n![Diagrama de dispersión entre ingreso y gasto de los hogares](../figures/fig-scatter-basico-1.png){#fig-scatter-basico fig-align='center' width=65%}\n:::\n:::\n\n\nEn este código, se construye un diagrama de dispersión entre las variables `x = Expenditure` y `y = Income`. La función `geom_point()` agrega los puntos del gráfico y, mediante `aes(size = wk)`, utiliza los pesos muestrales (`wk`) para controlar el tamaño de cada punto, de modo que las observaciones con mayor representación poblacional aparezcan visualmente más destacadas. El argumento `alpha = 0.3` incorpora transparencia a los puntos, reduciendo el problema de sobreposición y facilitando la visualización de áreas con alta concentración de observaciones.\n\nAdicionalmente, es posible incorporar variables de agrupamiento en los diagramas de dispersión mediante los argumentos `shape` y `color`, los cuales permiten diferenciar visualmente las observaciones según categorías específicas de la población. Esto facilita la identificación de patrones diferenciados entre grupos y mejora la interpretación de la relación entre las variables analizadas. Un ejemplo de este tipo de representación se presenta en la @fig-scatter-zona.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nweighted_zone_scatter <- ggplot(\n  data = survey_data,\n  aes(y = Income, x = Expenditure, shape = Zone)) +\n  geom_point(aes(size = wk, color = Zone), alpha = 0.3) +\n  labs(size = \"Peso\") +\n  scale_color_manual(values = zone_colors)\n\nweighted_zone_scatter\n```\n\n::: {.cell-output-display}\n![Diagrama de dispersión entre ingreso y gasto por zona geográfica](../figures/fig-scatter-zona-1.png){#fig-scatter-zona fig-align='center' width=65%}\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}