{
  "hash": "8ac0a3424b3e9edcb07a725723b73b2d",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n# Inferencia en poblaciones finitas {#ap2}\n\nLa inferencia estadística con datos provenientes de encuestas por muestreo requiere reconocer que la aleatoriedad puede tener orígenes distintos. En la inferencia estadística clásica, las observaciones suelen concebirse como realizaciones de un modelo probabilístico que genera los datos. En la teoría de muestreo, en cambio, la población finita se considera fija y la aleatoriedad proviene del mecanismo mediante el cual se seleccionan las unidades que conforman la muestra [@Gutierrez2016]. Esta distinción resulta fundamental cuando se analizan encuestas con diseños complejos.\n\nEste capítulo desarrolla ambos marcos inferenciales y muestra posteriormente cómo pueden integrarse. Primero se presenta la diferencia entre la inferencia basada en modelos y la inferencia basada en el diseño, utilizando ejemplos y simulaciones que permiten identificar las fuentes de aleatoriedad involucradas y observar las consecuencias de ignorar las probabilidades de selección. A continuación, se introduce la idea de inferencia doble, en la cual intervienen simultáneamente el modelo de superpoblación que genera los valores de las variables y el diseño probabilístico que determina cuáles unidades son observadas. Sobre esta base se revisan los principios de máxima verosimilitud y máxima pseudo-verosimilitud, mostrando cómo los pesos de muestreo pueden incorporarse directamente en las ecuaciones de estimación.\n\nLos resultados desarrollados en este capítulo constituyen la base inferencial para el análisis apropiado de modelos estadísticos con datos de encuestas complejas. En particular, permiten comprender por qué la incorporación de los pesos de muestreo y de la estructura del diseño no debe limitarse a la estimación de medias, totales o proporciones, sino extenderse también a modelos de regresión lineal, modelos lineales generalizados y modelos multinivel. La máxima pseudo-verosimilitud proporciona un vínculo natural entre la teoría del muestreo y la estimación de estos modelos, al modificar las contribuciones individuales a las ecuaciones de estimación de acuerdo con las probabilidades de inclusión. Esta perspectiva será fundamental en los capítulos posteriores para desarrollar procedimientos de estimación y de inferencia que sean coherentes tanto con el modelo estadístico como con la forma en que los datos fueron efectivamente seleccionados.\n\n## Dos posibles inferencias {#dos-posibles-inferencias}\n\nSegún @sarndal2003model, en encuestas de hogares conviene distinguir tres objetos. Primero, la población finita, denotada como $U = \\{1,2,\\ldots,N\\}$, la cual contiene todas las unidades de interés. Segundo, la variable de estudio $y_k$, observada o definida para cada unidad $k \\in U$. Tercero, el diseño muestral $p(s)$, que asigna probabilidades a las posibles muestras $s \\subset U$. En la notación utilizada a lo largo de este documento, una unidad puede identificarse como $k$ dentro del conglomerado o UPM $i$, perteneciente al estrato $h$, de modo que los estimadores ponderados suelen escribirse como sumas de la forma\n\n$$\n\\hat{t}_y = \\sum_h \\sum_i \\sum_k w_{hik} \\ y_{hik}\n$$\n\ndonde $w_{hik}$ representa el factor de expansión o peso muestral asociado con la unidad observada. En la teoría de muestreo, los valores $y_k$ se consideran fijos una vez definida la población. La aleatoriedad no está en los valores de la variable, sino en los indicadores de inclusión\n\n$$\nI_k =\n\\begin{cases}\n1, & \\text{si } k \\in s,\\\\\n0, & \\text{si } k \\notin s,\n\\end{cases}\n$$\n\nque inducen la probabilidad de inclusión $\\pi_k = \\Pr_p(I_k=1)$ y, a su vez, el correspondiente peso de muestreo, definido como $w_k = \\frac{1}{\\pi_k}$.\n\nUn estimador que ignora los pesos de muestreo puede no representar adecuadamente a la población objetivo, especialmente cuando la muestra proviene de un diseño complejo. En la inferencia basada en el diseño, la población se considera fija y la fuente de aleatoriedad proviene del mecanismo de selección de la muestra; por ello, sus elementos centrales son las probabilidades de inclusión $\\pi_k$ y los pesos de muestreo $w_k$.\n\nLa inferencia basada en modelos considera que los valores de la variable de interés en toda la población se conciben como realizaciones de un proceso estocástico, usualmente denotado por $\\xi$, y por ende la característica de interés se convierte en una variable aleatoria ($Y_k$). Entonces, en la inferencia basada en los modelos es de interés estudiar propiedades como $E_{\\xi}(Y_k)$ y $Var_{\\xi}(Y_k)$. A diferencia de la inferencia basada en el diseño, que se orienta a incorporar las características del plan muestral en los estimadores. \n\nLa inferencia basada en el diseño garantiza la existencia de estimadores que son exacta o aproximadamente insesgados. En particular, el estimador de Horvitz–Thompson satisface $E_{p}(\\hat{t}_y) = t_y$ bajo probabilidades de inclusión positivas. De acuerdo con @binder2011estimating, esta distinción permite entender por qué, aun cuando exista un modelo razonable para la variable de interés, el diseño muestral debe incorporarse explícitamente si se desea obtener inferencias válidas para la población objetivo. \n\nPara comprender la distinción entre inferencia basada en el modelo e inferencia basada en el diseño, partimos de un ejemplo sencillo. Supóngase que se generan $N=100$ realizaciones independientes de una variable Bernoulli con parámetro $\\theta=0.3$, donde $\\theta$ representa la proporción esperada de personas con una característica particular en una población generada por un modelo $\\xi$. Asumiendo que $Y_k \\sim Bernoulli(\\theta)$, entonces bajo el modelo se tiene que $E_{\\xi}(Y_k) = \\theta$ y además $Var_{\\xi}(Y_k) = \\theta(1-\\theta)$.\n\nEn la literatura especializada, el modelo $\\xi$ recibe el nombre de modelo de superpoblación, pues se asuem que es un proceso generador de poblaciones finitas. De esta forma, para una población finita generada por ese modelo, la media poblacional es $\\bar{Y}_U = \\frac{1}{N}\\sum_{k \\in U}Y_k$. Nótese que, bajo el modelo $\\xi$, esta media es insesgada para $\\theta$, puesto que\n\n$$\nE_{\\xi}(\\bar{Y}_U) =\nE_{\\xi}\\left(\\frac{1}{N}\\sum_{k \\in U}Y_k\\right)\n= \\frac{1}{N}\\sum_{k \\in U}E_{\\xi}(Y_k)\n= \\theta.\n$$\n\nLa siguiente simulación de Monte Carlo reproduce este proceso. En cada repetición se genera una población completa de tamaño $N=100$ y se calcula su media. El promedio de esas medias poblacionales debe aproximarse a $\\theta$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2026)\npopulation_size <- 100\ntheta <- 0.3\nn_sim_model <- 1000\nmodel_estimates <- rep(NA, n_sim_model)\n\nfor (sim in seq_len(n_sim_model)) {\n  outcome <- rbinom(population_size, 1, theta)\n  model_estimates[sim] <- mean(outcome)\n}\n\ncbind(\n  theta,\n  expected_model_mean = mean(model_estimates),\n  bias = mean(model_estimates) - theta\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     theta expected_model_mean    bias\n[1,]   0.3               0.302 0.00225\n```\n\n\n:::\n:::\n\n\nEl código fija una semilla para que el ejercicio sea reproducible. Luego genera `n_sim_model` poblaciones independientes mediante `rbinom()`. La salida reporta el parámetro verdadero `theta`, el promedio de las medias simuladas `expected_model_mean` y el sesgo Monte Carlo. Como se espera bajo el modelo Bernoulli IID, `expected_model_mean` queda muy cerca de 0.3 y el sesgo es cercano a cero. Las pequeñas diferencias se deben a que se usan 1000 simulaciones, no un número infinito de repeticiones.\n\nEn la teoría de muestreo, en cambio, las características de interés son parámetros fijos de la población. \npor ejemplo, si una persona está desempleada, su estado se considera un valor fijo de la población finita. Lo aleatorio es el mecanismo mediante el cual se selecciona la muestra. El total poblacional se define como $t_y = \\sum_{k \\in U} y_k$, mientras que la media poblacional es $\\bar{y}_U = \\frac{t_y}{N}$. Si se observa una muestra $s$, se propone estimar el total como\n\n$$\n\\hat{t}_{y} = \\sum_{k \\in s}\\frac{y_k}{\\pi_k}\n= \\sum_{k \\in s}w_k y_k.\n$$\n\nComo se mencionó en los capítulos anteriores, cuando el tamaño poblacional $N$ es desconocido, la media poblacional puede estimarse mediante el estimador de razón ponderado, definido como\n\n$$\n\\hat{\\bar{y}} =\n\\frac{\\sum_{k \\in s}w_k y_k}\n{\\sum_{k \\in s}w_k}\n$$\n\n\nEstos estimadores incorporan las probabilidades de inclusión en su forma funcional y esa es la diferencia central frente al promedio simple no ponderado de una muestra [@cochran1977sampling]. \n\nPara ilustrar el impacto del diseño, supóngase que la población anterior se encuentra particionada en $N_I$ unidades primarias de muestreo (UPM). De esta forma, se asume que la UPM $i$ tiene tamaño $N_i$, total $t_{y_i}=\\sum_{k \\in U_i}y_{ik}$ y media $\\bar{y}_i=t_{y_i}/N_i$. Bajo un diseño de tamaño fijo que asigna probabilidades de inclusión de primer orden proporcionales a $N_i$, siempre que todas sean postivas y menores o iguales que uno. Estas probabilidades toman la siguiente forma:\n\n$$\n\\pi_{Ii} = \\frac{n_I N_i}{N}\n$$\n\nCuando todos los miembros de las UPM seleccionadas son observados, el estimador de Horvitz–Thompson de la media poblacional es exactamente insesgado bajo las probabilidades de inclusión anteriores y puede escribirse como\n\n$$\n\\hat{\\bar{y}}\n= \\frac{1}{N}\\sum_{i \\in S_I}\\frac{t_{y_i}}{\\pi_{Ii}}\n= \\frac{1}{N}\\sum_{i \\in S_I}\\frac{N_i\\bar{y}_i}{n_I N_i/N}\n= \\frac{1}{n_I}\\sum_{i \\in S_I}\\bar{y}_i.\n$$\n\nEsta expresión ejemplifica por qué, bajo este diseño específico de selección proporcional al tamaño, el promedio de las medias de los conglomerados brinda insesgamiento. En contraste, el promedio simple de las personas observadas en las UPMs seleccionadas, sería:\n\n$$\n\\bar{y}_s =\n\\frac{\\sum_{i \\in S_I}t_{y_i}}\n     {\\sum_{i \\in S_I}N_i},\n$$\n\nel cual trata la muestra como si fuera autoponderada. Este estimador es sesgado cuando las probabilidades de selección son desiguales, especialmente si el tamaño del conglomerado se relaciona con la variable de interés. \n\nLa siguiente simulación fija una población finita y repite muchas veces la selección de hogares con probabilidades proporcionales al tamaño mediante `S.piPS()` del paquete `TeachingSampling`. En cada muestra se calculan dos estimadores: `design_estimates`, que corresponde a $\\hat{\\bar{y}}$, y `simple_estimates`, que corresponde al promedio simple de las personas observadas en las UPMs seleccionadas, $\\bar{y}_s$. Además, estos estimadores se comparan con el parámetro del modelo `theta_population`, correspondiente a $\\theta = 0.3$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(TeachingSampling)\n\nset.seed(2026)\npopulation_size <- 100\ntheta <- 0.3\nn_sim_sampling <- 1000\ndesign_estimates <- simple_estimates <- rep(NA, n_sim_sampling)\n\ncluster_size <- rep(2:6, each = 5)\nn_clusters <- length(cluster_size)\ncluster_id <- rep(seq_len(n_clusters), cluster_size)\nsize_center <- weighted.mean(cluster_size, cluster_size)\nprob_person <- theta + rep((cluster_size - size_center) / 12, cluster_size)\noutcome <- rbinom(population_size, 1, prob_person)\ntheta_population <- mean(outcome)\ncluster_totals <- tapply(outcome, cluster_id, sum)\ncluster_means <- tapply(outcome, cluster_id, mean)\n\nsampled_cluster_count <- floor(n_clusters * 0.3)\nfor (sim in seq_len(n_sim_sampling)) {\n  pps_sample <- S.piPS(sampled_cluster_count, cluster_size)\n  sampled_clusters <- pps_sample[, 1]\n  sampled_cluster_size <- cluster_size[sampled_clusters]\n  sampled_cluster_total <- cluster_totals[sampled_clusters]\n  sampled_cluster_mean <- cluster_means[sampled_clusters]\n  design_estimates[sim] <- mean(sampled_cluster_mean)\n  simple_estimates[sim] <-\n    sum(sampled_cluster_total) / sum(sampled_cluster_size)\n}\n\ncbind(\n  theta_population,\n  expected_pps = mean(design_estimates),\n  bias_pps = mean(design_estimates) - theta_population,\n  expected_simple = mean(simple_estimates),\n  bias_simple = mean(simple_estimates) - theta_population\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     theta_population expected_pps bias_pps expected_simple bias_simple\n[1,]              0.3        0.304  0.00368           0.358      0.0585\n```\n\n\n:::\n:::\n\n\nEl primer bloque del código genera hogares de tamaños desiguales, entre 2 y 6 personas. Para hacer visible el efecto del diseño, la probabilidad individual de desempleo varía ligeramente con el tamaño del hogar, pero se centra de manera que el promedio esperado de la población siga siendo cercano a `theta`. Luego se calcula `theta_population`, que es la proporción real de desempleo en esa población específica. En cada repetición, `S.piPS()` selecciona UPMs con probabilidades proporcionales al tamaño; después se calculan la media de las medias de las UPMs seleccionadas y el promedio simple de las personas observadas. La salida compara ambos estimadores con `theta_population`. El sesgo de Monte Carlo de `expected_pps` es cercano a cero, mientras que el de `expected_simple` no lo es, mostrando resultado de ignorar el diseño en este ejercicio.\n\nLa simulación muestra que el estimador que toma en cuenta el diseño de muestreo recupera adecuadamente el valor poblacional. La proporción verdadera en la población es 0.3, mientras que el promedio de las estimaciones obtenidas en las 1.000 muestras es 0.304, una pequeña diferencia atribuible a la variabilidad de Monte Carlo. En consecuencia, el estimador basado en la media de los conglomerados seleccionados bajo PPS presenta un comportamiento aproximadamente insesgado.\n\nEn contraste, el estimador que calcula la proporción directamente a partir del total de personas observadas en los conglomerados seleccionados alcanza un valor esperado de 0.358, con un sesgo positivo de 0.0585. Esto ocurre porque los conglomerados de mayor tamaño tienen una mayor probabilidad de ser seleccionados y, además, en la simulación presentan mayores probabilidades de ocurrencia del evento de interés. Al calcular la estimación sin corregir este efecto del diseño, los conglomerados grandes reciben una influencia excesiva, produciendo una sobreestimación sistemática de la proporción poblacional.\n\n\n## La integración de ambas inferencias {#la-integracion-de-ambas-inferencias}\n\nNo obstante, en muchas aplicaciones ambos marcos inferenciales no se presentan como enfoques excluyentes, sino como componentes complementarios de un mismo problema. En particular, puede considerarse que la muestra ha sido obtenida mediante un diseño probabilístico complejo y que, al mismo tiempo, los valores de la variable de interés responden a un modelo de superpoblación. @binder2011estimating plantea esta formulación como un esquema de inferencia doble, en el cual la incertidumbre no proviene de una única fuente, sino de la combinación entre el mecanismo que genera los valores poblacionales (modelo de superpoblación) y el mecanismo que determina qué unidades son observadas (diseño de muestreo).\n\nFormalmente, intervienen dos medidas de probabilidad: $\\xi$, asociada al proceso generador de los valores $Y_k$, y $p(\\cdot)$, asociada al diseño muestral que selecciona la muestra $s$. Por tanto, las propiedades de los estimadores deben evaluarse considerando simultáneamente ambas fuentes de variación. Bajo este marco, la esperanza combinada puede expresarse como\n\n$$\nE_{\\xi p}(\\hat{\\theta})\n= E_{\\xi}\\{E_p(\\hat{\\theta}\\mid U)\\},\n$$\n\nDonde primero se evalúa el comportamiento del estimador bajo el diseño, condicionado a la población finita generada, y luego se promedia sobre el modelo de superpoblación. En este contexto, la verosimilitud conjunta completa puede resultar intratable, especialmente cuando las probabilidades de inclusión dependen de variables relacionadas con la respuesta. Las ecuaciones de estimación ponderadas de @binder1983variances fundamentan la máxima pseudo-verosimilitud (MPV), que pondera las contribuciones de cada unidad por el inverso de su probabilidad de inclusión; @pfeffermann1993role examina las condiciones y los objetivos bajo los cuales resulta pertinente incorporar esos pesos en modelos para datos de encuestas.\n\n### Método de la máxima verosimilitud {#sec-mv}\n\nEl método de máxima verosimilitud [@CasellaBerger2002], parte de una población $Y_1,\\ldots,Y_N$ generada por un modelo $\\xi$, que asume una distribución con densidad o función de probabilidad $f(Y;\\theta)$. Si las observaciones son independientes e idénticamente distribuidas (IID), la función de verosimilitud se define como\n\n$$\nL(\\theta)\n= \\prod_{k=1}^{N} f(Y_k;\\theta).\n$$\n\nComo los productos pueden ser difíciles de manipular, se utiliza la log-verosimilitud:\n\n$$\n\\ell(\\theta)\n= \\sum_{k=1}^{N}\\log f(Y_k;\\theta)\n$$\n\nEl estimador de máxima verosimilitud $\\hat{\\theta}$ es el valor de $\\theta$ que maximiza $\\ell(\\theta)$. Si la función es diferenciable, este valor satisface las ecuaciones de score:\n\n$$\nU(\\theta)\n= \\frac{\\partial \\ \\ell(\\theta)}{\\partial \\ \\theta}\n= \\sum_{k=1}^{N} u_k(\\theta)\n= 0\n$$\n\ndonde $u_k(\\theta) = \\frac{\\partial}{\\partial\\theta}\\log f(Y_k;\\theta)$ es la contribución de la unidad $k$ al score total. En particular, para una distribución Bernoulli con parámetro $\\theta$, la función de probabilidad es $f(Y_k;\\theta) = \\theta^{Y_k}(1-\\theta)^{1-Y_k}$, para $Y_k \\in \\{0,1\\}$. La log-verosimilitud es\n\n$$\n\\ell(\\theta)\n= \\sum_{k=1}^{N}\n\\left[\nY_k\\log(\\theta)\n+(1-Y_k)\\log(1-\\theta)\n\\right]\n$$\n\nAl derivar e igualar a cero y despejar, se obtiene el estimador MV, definido por:\n\n$$\n\\hat{\\theta}_{MV}\n= \\frac{1}{N}\\sum_{k=1}^{N}Y_k\n$$\n\nPor ende, la proporción poblacional es el estimador natural del parámetro $\\theta$ en una distribución Bernoulli. El punto clave es que este resultado depende del supuesto de que las observaciones tienen igual distribución y no provienen de un diseño con probabilidades desiguales.\n\nPor otro lado, en un modelo de regresión lineal múltiple con errores normales, se tiene que $\\mathbf{Y} \\sim N(\\mathbf{X}\\boldsymbol{\\beta},\\sigma^2 I)$. En este caso, la log-verosimilitud, omitiendo constantes, puede escribirse como\n\n$$\n\\ell(\\boldsymbol{\\beta},\\sigma^2) = -\\frac{N}{2}\\log(\\sigma^2) -\\frac{1}{2\\sigma^2}(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta})'(\\mathbf{Y}-\\mathbf{X}\\boldsymbol{\\beta})\n$$\n\nMaximizar esta expresión respecto de $\\beta$ equivale a minimizar la suma de cuadrados de los residuos. Por ello, el estimador de máxima verosimilitud de $\\beta$ coincide con el estimador de mínimos cuadrados ordinarios $\\hat{\\boldsymbol{\\beta}}_{MV} = (\\mathbf{X}'\\mathbf{X})^{-1}\\mathbf{X}'\\mathbf{Y}$. Este resultado es importante porque muestra que muchos procedimientos estadísticos usuales pueden interpretarse como máxima verosimilitud bajo supuestos de modelo específicos. Sin embargo, si los datos provienen de una encuesta compleja, la matriz $\\mathbf{X}'\\mathbf{X}$ no refleja por sí sola el mecanismo de selección de la muestra.\n\n### Método de máxima pseudo-verosimilitud {#sec-mpv-formal}\n\nCuando el diseño muestral es complejo, los datos observados no satisfacen necesariamente los supuestos de independencia e idéntica distribución. Algunas unidades pueden representar a muchas personas de la población y otras a pocas. Además, dos unidades seleccionadas dentro del mismo conglomerado pueden estar correlacionadas. En este contexto, usar directamente la log-verosimilitud ordinaria puede producir estimaciones que describen la muestra, pero no la población objetivo.\n\nLa máxima pseudo-verosimilitud, desarrollada a partir de los resultados de @binder1983variances, incorpora los pesos de muestreo en la log-verosimilitud. Para las unidades observadas en la muestra $k \\in s$, se define la log-verosimiliutd ponderada:\n\n$$\n\\ell_p(\\theta)\n= \\sum_{k \\in s} w_k \\log f(y_k;\\theta)\n$$\n\nEn donde el peso $w_k=1/\\pi_k$ indica cuántas unidades de la población representa la observación $y_k$. Por eso, la contribución de una unidad con baja probabilidad de inclusión se amplifica en la pseudo-verosimilitud. Las ecuaciones de estimación resultantes son\n\n$$\nU_p(\\theta)\n= \\sum_{k \\in s} w_k \\ u_k(\\theta)\n= 0\n$$\n\n\nLa estimación MPV conserva la lógica de máxima verosimilitud, pero reemplaza el *score* ordinario por un *score* ponderado. La solución $\\hat{\\theta}_{MPV}$ es el valor que hace que la suma ponderada de contribuciones individuales sea igual a cero. Para una distribución Bernoulli, la pseudo-log-verosimilitud es\n\n$$\n\\ell_p(\\theta)\n= \\sum_{k \\in s} w_k\n\\left[\ny_k\\log(\\theta)\n+(1-y_k)\\log(1-\\theta)\n\\right].\n$$\n\nAl derivar e igualar a cero, se obtiene que:\n\n$$\n\\frac{\\partial \\ell_p(\\theta)}{\\partial \\theta}\n=\n\\sum_{k \\in s} w_k\n\\left[\n\\frac{y_k}{\\theta}\n-\\frac{1-y_k}{1-\\theta}\n\\right]\n=0\n$$\n\nCuya solución es:\n\n$$\n\\hat{\\theta}_{MPV}\n=\n\\frac{\\sum_{k \\in s}w_k y_k}\n     {\\sum_{k \\in s}w_k}\n= \\hat{p}_d\n$$\n\nPor tanto, para una variable binaria, la MPV conduce al estimador ponderado de la proporción, equivalente al estimador de Hájek. Este resultado conecta directamente la teoría de pseudo-verosimilitud con los estimadores de proporciones presentados en los capítulos de variables categóricas.\n\nAsimismo, para un modelo de regresión lineal múltiple, la pseudo-log-verosimilitud ponderada implica minimizar una suma de cuadrados ponderada:\n\n$$\n(\\mathbf{y}-\\mathbf{X}\\boldsymbol{\\beta})'\\mathbf{W}(\\mathbf{y}-\\mathbf{X}\\boldsymbol{\\beta}),\n$$\n\ndonde\n\n$$\n\\mathbf{W}=\n\\begin{pmatrix}\nw_1 & 0 & \\cdots & 0\\\\\n0 & w_2 & \\cdots & 0\\\\\n\\vdots & \\vdots & \\ddots & \\vdots\\\\\n0 & 0 & \\cdots & w_n\n\\end{pmatrix}.\n$$\n\nLa solución es el estimador de mínimos cuadrados ponderados:\n\n$$\n\\hat{\\boldsymbol{\\beta}}_{MPV}\n= (\\mathbf{X}'\\mathbf{W}\\mathbf{X})^{-1}\\mathbf{X}'\\mathbf{W}\\mathbf{y}\n$$\n\nDe acuerdo con @HeeringaWestBerglund2017, este resultado extiende de manera natural el estimador ordinario al contexto de encuestas complejas: cada observación contribuye al ajuste del modelo en proporción a su peso muestral. No obstante, para la inferencia no basta con ponderar la estimación puntual; también se requiere estimar correctamente la varianza considerando estratos, conglomerados y pesos.\n\nLa siguiente simulación de Monte Carlo anidada ilustra la inferencia doble. En el ciclo externo se genera una nueva población bajo el modelo Bernoulli. En el ciclo interno se seleccionan muchas muestras por diseño y se comparan el estimador que incorpora el diseño y el promedio simple de la muestra.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2026)\npopulation_size <- 100\ntheta <- 0.3\nn_sim_population <- 100\nexpected_design_estimates <- \n  expected_simple_estimates <- \n  population_means <-\n  rep(NA, n_sim_population)\n\ncluster_size <- rep(2:6, each = 5)\nn_clusters <- length(cluster_size)\ncluster_id <- rep(seq_len(n_clusters), cluster_size)\nsize_center <- weighted.mean(cluster_size, cluster_size)\nprob_person <- theta + rep((cluster_size - size_center) / 12, cluster_size)\nsampled_cluster_count <- floor(n_clusters * 0.3)\n\nfor (population_sim in seq_len(n_sim_population)) {\n  outcome <- rbinom(population_size, 1, prob_person)\n  population_means[population_sim] <- mean(outcome)\n  cluster_totals <- tapply(outcome, cluster_id, sum)\n  cluster_means <- tapply(outcome, cluster_id, mean)\n  \n  design_estimates <- simple_estimates <- rep(NA, 100)\n  for (sample_sim in seq_len(100)) {\n    pps_sample <- S.piPS(sampled_cluster_count, cluster_size)\n    sampled_clusters <- pps_sample[, 1]\n    sampled_cluster_size <- cluster_size[sampled_clusters]\n    sampled_cluster_total <- cluster_totals[sampled_clusters]\n    sampled_cluster_mean <- cluster_means[sampled_clusters]\n    design_estimates[sample_sim] <- mean(sampled_cluster_mean)\n    simple_estimates[sample_sim] <-\n      sum(sampled_cluster_total) / sum(sampled_cluster_size)\n  }\n  expected_design_estimates[population_sim] <- mean(design_estimates)\n  expected_simple_estimates[population_sim] <- mean(simple_estimates)\n}\n\ncbind(\n  theta,\n  mean_population = mean(population_means),\n  expected_pps = mean(expected_design_estimates),\n  bias_pps = mean(expected_design_estimates) - theta,\n  expected_simple = mean(expected_simple_estimates),\n  bias_simple = mean(expected_simple_estimates) - theta\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     theta mean_population expected_pps bias_pps expected_simple bias_simple\n[1,]   0.3           0.304        0.302  0.00248           0.332      0.0317\n```\n\n\n:::\n:::\n\n\nEl código reproduce las dos fuentes de aleatoriedad. El ciclo externo representa el modelo $\\xi$, porque genera nuevas poblaciones finitas con `rbinom()`. El ciclo interno representa el diseño $p$, porque para cada población se seleccionan múltiples muestras con `S.piPS()`. La salida incluye `mean_population`, que es el promedio de las medias poblacionales generadas; `expected_pps`, que resume el comportamiento del estimador que incorpora el diseño; y `expected_simple`, que resume el promedio simple de la muestra seleccionada. Cuando el diseño se incorpora correctamente, el sesgo Monte Carlo respecto de `theta` debe ser pequeño. La comparación con `expected_simple` muestra por qué la inferencia basada en encuestas requiere pesos y varianzas de diseño, incluso cuando se parte de un modelo estadístico sencillo.\n\nLos resultados de la simulación muestran con claridad el efecto de respetar (o ignorar) el diseño complejo cuando el tamaño del conglomerado está relacionado con la variable de interés. En la simulación, el parámetro poblacional se fija en `theta = 0.3` y la media observada entre las 100 poblaciones simuladas es `0.304`, una pequeña diferencia atribuible a la variabilidad de Monte Carlo. El estimador basado en el promedio simple de las medias de los conglomerados seleccionados alcanza `0.302`. Esto ocurre porque la probabilidad de seleccionar cada conglomerado es proporcional a su tamaño: al promediar las medias de los conglomerados seleccionados, la selección introduce precisamente la ponderación por tamaño necesaria para recuperar la media a nivel de personas. Por ello, el sesgo reportado es prácticamente nulo (`0.00248`).\n\nEn contraste, el estimador que combina todos los individuos pertenecientes a los conglomerados seleccionados como si constituyeran una muestra simple, tiene una media de `0.332` presentando un sesgo positivo (`0.0317`). El problema es que los conglomerados grandes ya tienen una probabilidad mayor de ser seleccionados por el diseño y, posteriormente, al calcular la media agrupando todos sus individuos, vuelven a recibir mayor peso debido a que contienen más personas. Se produce así una especie de doble ponderación por tamaño. El ejercicio ilustra, por tanto, que ignorar las probabilidades de selección puede producir sesgo cuando el diseño es informativo.\n\nEn síntesis, como explica @pfeffermann1993role, la máxima verosimilitud es adecuada cuando las observaciones pueden tratarse como IID bajo un modelo probabilístico. En encuestas complejas, la máxima pseudo-verosimilitud ofrece una extensión natural: conserva la estructura de las ecuaciones de estimación, pero pondera cada contribución individual por su peso muestral. La ponderación protege frente a ciertos diseños informativos o a determinadas especificaciones incorrectas, pero su necesidad y sus propiedades dependen del diseño y del modelo. Así, los modelos estadísticos se ajustan de manera más coherente con la población que la encuesta busca representar.\n\n",
    "supporting": [
      "A2-MPVbinder_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}