{
  "hash": "ac96e98851376291a951379a7d1f3d9a",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n# Análisis de variables categóricas  {#cap4}\n\nEn el análisis de encuestas de hogares, uno de los productos más habituales es la estimación de parámetros descriptivos asociados a variables categóricas, los cuales permiten sintetizar las principales características de la población. Estas medidas facilitan una representación clara y comprensible de fenómenos sociales a partir de información recolectada mediante muestras probabilísticas [@CEPAL2023Diseno].\n\nComo explica @Agresti2019Intro, las frecuencias y las proporciones se encuentran entre los indicadores descriptivos más utilizados para analizar variables categóricas. Las frecuencias representan el número de personas u hogares que pertenecen a cada categoría, como la cantidad de personas en condición de pobreza, mientras que las proporciones expresan el peso relativo de cada categoría dentro de la población, como el porcentaje de hogares en situación de hacinamiento. Aunque el análisis descriptivo de este tipo de variables se apoya principalmente en estos parámetros, también puede complementarse con medidas derivadas de variables numéricas, como los cuantiles y los indicadores de desigualdad abordados en el capítulo anterior.\n\nPara estimar correctamente estas medidas a partir de una encuesta de hogares, es necesario comenzar por definir el diseño de muestreo. Este paso permite incorporar las características de la encuesta, incluidos los factores de expansión, las unidades primarias de muestreo y los estratos de selección. La adecuada especificación de estos elementos es fundamental para que las frecuencias, las proporciones y las demás estadísticas estimadas representen apropiadamente a la población objetivo y para que sus medidas de precisión reflejen la variabilidad introducida por el diseño muestral.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(survey)\nlibrary(srvyr)\n\nsurvey_data <- readRDS(\"../Data/encuesta.rds\")\noptions(survey.lonely.psu = \"adjust\")\n\nsurvey_design <- survey_data %>%\n  as_survey_design(\n    strata = Stratum,\n    ids = PSU,\n    weights = wk,\n    nest = TRUE\n  )\n```\n:::\n\n\nA partir de la información original de la encuesta, se construyen algunas variables categóricas que serán utilizadas en los ejercicios desarrollados a lo largo de este capítulo. En particular, se define una variable dicotómica que identifica si una persona se encuentra o no en condición de pobreza, considerando como pobres a quienes pertenecen a cualquiera de las categorías de pobreza registradas en la encuesta. Asimismo, se crea una variable que permite distinguir a las personas desempleadas del resto de la población y otra que clasifica a las personas en dos grupos de edad: menores de 18 años y personas de 18 años o más. Estas variables facilitarán la desagregación de los resultados y la comparación de indicadores entre distintos grupos de la población:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design <- survey_design %>%\n  mutate(\n    poor = ifelse(Poverty != \"NotPoor\", 1, 0),\n    unemployed = ifelse(Employment == \"Unemployed\", 1, 0),\n    age_18 = case_when(\n      Age < 18 ~ \"< 18 years\",\n      TRUE ~ \">= 18 years\"\n    )\n  )\n```\n:::\n\n\nEn el código anterior se crean nuevas variables derivadas utilizando la función `mutate()` del paquete `dplyr`. Las variables `poor` y `unemployed` se construyen mediante la función `ifelse()`, que evalúa una condición lógica y asigna un valor dependiendo de si esta se cumple o no. En este caso, las variables toman el valor `1` cuando la persona se encuentra en condición de pobreza o desempleo, respectivamente, y `0` en caso contrario. Por su parte, la variable `age_18` se genera mediante la función `case_when()`, la cual permite definir categorías a partir de una o varias condiciones de forma más clara y flexible que `ifelse()`. Esta función resulta especialmente útil cuando se requiere construir variables categóricas con múltiples niveles. En el ejemplo, las personas menores de 18 años se clasifican en la categoría `\"< 18 years\"`, mientras que el resto se agrupa en la categoría `\">= 18 years\"`.\n\nAdemás de las variables categóricas definidas previamente, es necesario establecer subpoblaciones que permitan obtener estimaciones desagregadas y comparar los indicadores entre distintos grupos. Para los ejemplos desarrollados en este capítulo, se consideran cuatro subpoblaciones definidas según la zona de residencia y el sexo: población urbana, población rural, mujeres y hombres.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nurban_subset <- survey_design %>%\n  filter(Zone == \"Urban\")\n\nrural_subset <- survey_design %>%\n  filter(Zone == \"Rural\")\n\nfemale_subset <- survey_design %>%\n  filter(Sex == \"Female\")\n\nmale_subset <- survey_design %>%\n  filter(Sex == \"Male\")\n```\n:::\n\n\n## Estimación del tamaño poblacional {#estimacion-del-tamano-poblacional}\n\nEn el análisis de encuestas de hogares, es fundamental estimar el tamaño de las distintas subpoblaciones y la proporción que cada una representa dentro de la población total [@CEPAL2023Diseno]. Estas estimaciones permiten cuantificar grupos definidos por características demográficas o socioeconómicas y describir su importancia relativa. Por ejemplo, conocer el número y la proporción de personas que se encuentran por debajo de la línea de pobreza, están desempleadas o han alcanzado un determinado nivel educativo contribuye a identificar brechas entre grupos, evaluar sus condiciones de bienestar y generar información relevante para el diseño de políticas públicas.\n\nLas subpoblaciones se definen mediante variables categóricas que clasifican a las unidades de la población finita en grupos mutuamente excluyentes, como las distintas condiciones de actividad económica o los niveles educativos alcanzados. El tamaño de una subpoblación corresponde al número total de personas u hogares de la población que pertenecen a una categoría determinada. Para estimarlo a partir de una encuesta, se suman los pesos muestrales de las unidades clasificadas en esa categoría, dado que cada peso indica cuántas personas u hogares de la población representa la unidad observada en la muestra. A partir de estas estimaciones también puede calcularse la proporción que cada subpoblación representa respecto del total poblacional. Por ende, el estimador del tamaño de la población [@sarndal2003model], se define como:\n\n$$\n\\hat{N} = \\sum_{h} \\sum_{i} \\sum_{k} w_{hik}\n$$\n\nEn donde, $w_{hik}$ es el peso o factor de expansión de la unidad $k$ en la UPM $i$ del estrato $h$. \n\nAsimismo, la estimación del tamaño de una subpoblación sigue el mismo principio que la estimación del tamaño total, pero se restringe a las unidades que presentan una característica determinada. Para estimar cuántas personas u hogares pertenecen a una categoría específica $d$, se identifica en la muestra a las unidades que cumplen dicha condición y se suman sus pesos muestrales. De esta manera, cada unidad contribuye a la estimación de acuerdo con el número de unidades de la población que representa:\n\n$$\n\\hat{N}_d\n=\n\\sum_{h}\n\\sum_{i}\n\\sum_{k}\nw_{hik} \\ \nI(y_{hik}=d)\n$$\n\ndonde $\\hat{N}_d$ representa el tamaño estimado de la subpoblación perteneciente a la categoría $d$. Por su parte, $I(y_{hik}=d)$ es una variable binaria que toma el valor de 1 si la unidad $k$ de la UPM $i$ en el estrato $h$ pertenece a la categoría $d$ de la variable de interés $y$, y 0 en caso contrario. Nótese además que, si $d$ fue utilizada en la calibración de los pesos, el valor de $\\hat{N}_d$ coincidirá con el control externo aplicado y por ende su error estándar será nulo [@Gutierrez2016].\n\nEn `R`, utilizando el diseño muestral definido previamente, es posible, generar resúmenes de la información de la encuesta para cada categoría de la variable `Zone`. Para ello, los datos se agrupan según la zona geográfica, lo que permite obtener resultados independientes para cada uno de estos dominios de estudio. A partir de este procedimiento se producen dos tipos principales de resultados. En primer lugar, se calcula el número de observaciones efectivamente recolectadas en la muestra, sin considerar los factores de expansión, usando la función `unweighted()`. En segundo lugar, se estima el tamaño poblacional asociado a cada dominio incorporando la información del diseño de muestreo. Junto con las estimaciones poblacionales también se obtienen medidas de precisión, como el error estándar y el intervalo de confianza. Los resultados se presentan en la @tbl-tamano-zona. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(\n    n = unweighted(n()),\n    size = survey_total(vartype = c(\"se\", \"ci\"))\n  )\n```\n:::\n\n\n\n::: {#tbl-tamano-zona .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por zona geográfica'}\n::: {.cell-output-display}\n\n\n|Zone  |    n|  size| size_se| size_low| size_upp|\n|:-----|----:|-----:|-------:|--------:|--------:|\n|Rural | 1297| 72102|    3062|    66039|    78165|\n|Urban | 1308| 78164|    2847|    72526|    83802|\n\n\n:::\n:::\n\n\n\nEn efecto, el tamaño de muestra fue de 1297 personas en la zona rural y de 1308 en la zona urbana. A partir de estas muestras se estimó una población de 72,102 personas para la zona rural, con un error estándar de 3,062, y de 78,164 personas para la zona urbana, con un error estándar de 2,847. Considerando un nivel de confianza del 95%, los intervalos de confianza para las estimaciones poblacionales fueron de 66,038.5 a 78,165.4 personas en la zona rural y de 72,526.2 a 83,801.7 personas en la zona urbana. De manera análoga, también es posible estimar el número de personas según los distintos niveles de pobreza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Poverty) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-tamano-pobreza .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Poverty  |  size| size_se| size_low| size_upp|\n|:--------|-----:|-------:|--------:|--------:|\n|NotPoor  | 91398|    4395|    82696|   100101|\n|Extreme  | 21519|    4949|    11719|    31319|\n|Relative | 37349|    3695|    30032|    44666|\n\n\n:::\n:::\n\n\nLa @tbl-tamano-pobreza refelja una población en la que la mayoría de las personas no vive en pobreza, pero en la que esa aparente normalidad convive con una fractura difícil de considerar marginal: cerca de 58.868 personas se encuentran en pobreza relativa o extrema. De ellas, 21.519 padecen las privaciones más severas y 37.349 permanecen por debajo de los niveles de vida socialmente aceptables.\n\nOtra variable categórica relevante en las encuestas de hogares es el estado de ocupación. En este caso, la información se agrupa según las categorías de la variable `Employment`, lo que permite obtener estimaciones separadas para cada condición de actividad laboral de la población. Mediante el uso de la función `group_by()` es posible desagregar las estimaciones en niveles más detallados, facilitando el análisis comparativo entre los distintos grupos ocupacionales. En primer lugar, se excluyen los registros con valores faltantes en la variable de empleo, garantizando que los resultados se calculen únicamente con personas activas en la fuerza de trabajo. Posteriormente, para cada categoría de ocupación se estima el tamaño poblacional, junto con el error estándar y los intervalos de confianza. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  filter(!is.na(Employment)) %>%\n  group_by(Employment) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-tamano-empleo .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por estado de ocupación'}\n::: {.cell-output-display}\n\n\n|Employment |  size| size_se| size_low| size_upp|\n|:----------|-----:|-------:|--------:|--------:|\n|Unemployed |  4635|     761|     3129|     6141|\n|Inactive   | 41465|    2163|    37183|    45748|\n|Employed   | 61877|    2540|    56847|    66907|\n\n\n:::\n:::\n\n\nA partir de los resultados presentados en la @tbl-tamano-empleo, se estima que la población ocupada asciende a 61.877 personas. Por su parte, la población inactiva se estima en 41.465 personas, mientras que cerca de 4.635 personas se encontrarían desempleadas. En conjunto, las estimaciones muestran que los desempleados representan el grupo de menor tamaño, aunque la amplitud relativa de su intervalo de confianza indica una mayor incertidumbre en comparación con las estimaciones de la población ocupada e inactiva.\n\nFinalmente, las estimaciones también pueden desagregarse simultáneamente por más de una variable categórica. Por ejemplo, es posible analizar el estado ocupacional según el nivel de pobreza, cuyos resultados se presentan en la @tbl-tamano-empleo-pobreza, de donde se puede concluir que el empleo constituye una protección importante frente a la pobreza. Entre las 61.877 personas ocupadas, 17.277 continúan en situación de pobreza, de las cuales 5.128 se encuentran en pobreza extrema y 12.149 en pobreza relativa. La vulnerabilidad es aún más visible entre las 41.465 personas inactivas, pues 17.119 viven en pobreza, mientras que entre las 4.635 personas desempleadas apenas 1.768 son clasificadas como no pobres y 2.866 padecen pobreza extrema o relativa. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  filter(!is.na(Employment)) %>%\n  group_by(Employment, Poverty) %>%\n  cascade(\n    size = survey_total(vartype = c(\"se\", \"ci\")),\n    .fill = \"Total\"\n  )\n```\n:::\n\n\n::: {#tbl-tamano-empleo-pobreza .cell layout-align=\"center\" tbl-cap='Tamaño poblacional estimado por estado de ocupación y condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Employment |Poverty  |   size| size_se| size_low| size_upp|\n|:----------|:--------|------:|-------:|--------:|--------:|\n|Unemployed |NotPoor  |   1768|     405|      966|     2571|\n|Unemployed |Extreme  |   1169|     348|      480|     1859|\n|Unemployed |Relative |   1697|     458|      791|     2604|\n|Unemployed |Total    |   4635|     761|     3129|     6141|\n|Inactive   |NotPoor  |  24346|    1736|    20908|    27784|\n|Inactive   |Extreme  |   6422|    1321|     3807|     9037|\n|Inactive   |Relative |  10697|    1460|     7806|    13589|\n|Inactive   |Total    |  41465|    2163|    37183|    45748|\n|Employed   |NotPoor  |  44600|    2596|    39460|    49741|\n|Employed   |Extreme  |   5128|    1122|     2907|     7349|\n|Employed   |Relative |  12149|    1347|     9483|    14816|\n|Employed   |Total    |  61877|    2540|    56847|    66907|\n|Total      |Total    | 107977|    3466|   101115|   114839|\n\n\n:::\n:::\n\n\n\n## Estimación de proporciones {#estimacion-de-proporciones}\n\nLas proporciones permiten expresar el peso relativo que tienen determinados grupos dentro de la población. Por ejemplo, conocer el porcentaje de hogares que se encuentran por debajo de la línea de pobreza es esencial para evaluar desigualdades y caracterizar condiciones de bienestar. Para obtener este tipo de estimaciones, se calcula el promedio ponderado de la variable dicotómica, lo que asegura que la estimación represente adecuadamente la distribución poblacional. Al convertir las categorías originales en variables indicadoras, la proporción estimada se calcula como:\n\n$$\n\\hat{p}_d = \\frac{\\hat{N}_d}{\\hat{N}} = \\frac{\\displaystyle\\sum_{h} \\sum_{i} \\sum_{k} w_{hik} \\ I(y_{hik}=d)} {\\displaystyle\\sum_{h} \\sum_{i} \\sum_{k} w_{hik}}\n$$\n\nComo explica @Gutierrez2016, si bien este estimador es conceptualmente sencillo, corresponde a una función no lineal de los totales poblacionales. Por esta razón, para derivar sus propiedades estadísticas, particularmente su varianza y error estándar, es necesario recurrir a métodos de aproximación como la linealización de Taylor. En este contexto, se utiliza la función $z_{hik}=I(y_{hik}=d)-\\hat{p}_d$. En la práctica, los programas estadísticos implementan automáticamente estos procedimientos y generan las estimaciones de proporciones junto con sus respectivos errores estándar e intervalos de confianza.\n\nCuando las proporciones estimadas toman valores cercanos a 0 o a 1, su precisión puede disminuir y las aproximaciones estadísticas tradicionales pueden resultar poco adecuadas. En estos casos, suele ser necesario disponer de tamaños de muestra mayores para obtener estimaciones suficientemente estables. Este problema adquiere especial importancia al analizar fenómenos poco frecuentes o muy concentrados, ya que pequeñas variaciones en la composición de la muestra pueden ocasionar cambios sustanciales en las proporciones estimadas [@KornGraubard1999].\n\nEsta dificultad también afecta la construcción de los intervalos de confianza. Como señala @Agresti2019Intro, los intervalos basados directamente en la aproximación normal pueden producir límites inferiores menores que 0 o límites superiores mayores que 1, resultados incompatibles con el rango de una proporción. Una alternativa consiste en construir el intervalo en la escala logit y transformarlo posteriormente a la escala original. Para una proporción estimada $\\hat{p}_d$, el intervalo de confianza con nivel $1-\\alpha$ puede expresarse como\n\n$$\nCI(\\hat{p}_d;1-\\alpha)\n=\n\\left[\n\\frac{\\exp(L_d)}{1+\\exp(L_d)},\n\\frac{\\exp(U_d)}{1+\\exp(U_d)}\n\\right],\n$$\n\nEn donde\n\n$$\nL_d\n=\n\\log\\left(\\frac{\\hat{p}_d}{1-\\hat{p}_d}\\right)\nt_{1-\\alpha/2, df}\n\\frac{\\widehat{SE}(\\hat{p}_d)}\n{\\hat{p}_d(1-\\hat{p}_d)}\n$$\n\ny\n\n$$\nU_d\n=\n\\log\\left(\\frac{\\hat{p}_d}{1-\\hat{p}_d}\\right)\n+\nt_{1-\\alpha/2, df}\n\\frac{\\widehat{SE}(\\hat{p}_d)}\n{\\hat{p}_d(1-\\hat{p}_d)}.\n$$\n\nAl aplicar la transformación inversa del logit a los límites $L_d$ y $U_d$, se garantiza que el intervalo resultante permanezca dentro del rango válido entre 0 y 1. Nótese que el término $t_{1-\\alpha/2, df}$ representa el percentil asociado al nivel de confianza seleccionado, considerando $df$ grados de libertad. Como se advirtió anteriormente, en el contexto de encuestas complejas, estos grados de libertad suelen definirse como la diferencia entre el número de unidades primarias de muestreo (UPM) y el número de estratos presentes en el subgrupo o dominio de análisis.\n\nA diferencia de otros programas estadísticos que presentan los resultados en porcentaje, `R` reporta las proporciones en la escala [0,1]. Las funciones utilizadas permiten calcular directamente las estimaciones, sus errores estándar e intervalos de confianza, lo que facilita el análisis de variables categóricas en encuestas de hogares. A continuación se ilustra cómo obtener la proporción de personas por zona usando el diseño muestral previamente definido.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsurvey_design %>%\n  group_by(Zone) %>%\n  summarise(proportion = survey_mean(\n    vartype = c(\"se\", \"ci\"),\n    proportion = TRUE\n  ))\n```\n:::\n\n\n::: {#tbl-prop-zona .cell layout-align=\"center\" tbl-cap='Proporción de personas por zona geográfica'}\n::: {.cell-output-display}\n\n\n|Zone  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|----------:|-------------:|--------------:|--------------:|\n|Rural |       0.48|         0.014|          0.452|          0.508|\n|Urban |       0.52|         0.014|          0.492|          0.548|\n\n\n:::\n:::\n\n\n\nEn este ejemplo, la función `survey_mean()` se utiliza para calcular la estimación de proporciones poblacionales y, mediante el argumento `proportion = TRUE`, se especifica que el interés se centra en estimar la distribución relativa de la población entre las distintas categorías de la variable analizada. Los resultados presentados en la @tbl-prop-zona indican que aproximadamente el 48% de las personas reside en la zona rural, con un intervalo de confianza del 95% entre 45.2% y 50.8%, mientras que el 52% corresponde a población residente en la zona urbana, con un intervalo de confianza entre 49.2% y 54.8%.\n\nLa librería `srvyr` también dispone de la función `survey_prop()`, diseñada específicamente para la estimación de proporciones en encuestas complejas. Esta función produce resultados equivalentes a los obtenidos con `survey_mean()`, facilitando además una sintaxis más directa e intuitiva cuando el objetivo del análisis es exclusivamente el cálculo de proporciones. Además, si el interés se centra ahora en estimar proporciones para subpoblaciones específicas, por ejemplo, la proporción de hombres y mujeres que residen en la zona urbana, es necesario restringir el análisis a dicho dominio de estudio y posteriormente calcular las estimaciones correspondientes para cada categoría de sexo. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nurban_subset %>%\n  group_by(Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-sexo-urbano .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres en zona urbana'}\n::: {.cell-output-display}\n\n\n|Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:------|----------:|-------------:|--------------:|--------------:|\n|Female |      0.537|         0.013|          0.511|          0.563|\n|Male   |      0.463|         0.013|          0.437|          0.489|\n\n\n:::\n:::\n\n\nLa @tbl-prop-sexo-urbano muestra una leve mayoría femenina en la población urbana: las mujeres representan el 53,6%, con un intervalo de confianza entre 51,0% y 56,2%, frente al 46,4% de los hombres, cuyo intervalo se sitúa entre 43,7% y 48,9%. \n\nAhora bien, si el análisis se restringe únicamente a la población masculina incluida en la base de datos y el interés consiste en estimar la distribución porcentual de los hombres según la zona de residencia, es posible calcular la proporción de hombres que viven en áreas urbanas y rurales utilizando el diseño muestral previamente definido. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_subset %>%\n  group_by(Zone) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-zona-hombre .cell layout-align=\"center\" tbl-cap='Distribución por zona en la subpoblación masculina'}\n::: {.cell-output-display}\n\n\n|Zone  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|----------:|-------------:|--------------:|--------------:|\n|Rural |      0.491|         0.018|          0.455|          0.526|\n|Urban |      0.509|         0.018|          0.474|          0.545|\n\n\n:::\n:::\n\n\nLos resultados de la @tbl-prop-zona-hombre revelan una población masculina repartida casi por igual entre lo urbano y lo rural: el 50,9% reside en áreas urbanas, con un intervalo de confianza entre 47,4% y 54,5%, mientras que el 49,1% habita en zonas rurales, con un intervalo entre 45,5% y 52,6%. \n\nLa función `group_by()` permite generar distintos niveles de desagregación mediante la combinación de dos o más variables categóricas. Por ejemplo, es posible estimar la proporción de hombres según zona de residencia y condición de pobreza de manera simultánea. Este tipo de análisis permite caracterizar con mayor detalle las condiciones socioeconómicas de subpoblaciones específicas. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_subset %>%\n  group_by(Zone, Poverty) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-zona-pobreza-hombre .cell layout-align=\"center\" tbl-cap='Proporción de hombres por zona y condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Zone  |Poverty  | proportion| proportion_se| proportion_low| proportion_upp|\n|:-----|:--------|----------:|-------------:|--------------:|--------------:|\n|Rural |NotPoor  |      0.549|         0.063|          0.424|          0.668|\n|Rural |Extreme  |      0.198|         0.067|          0.096|          0.364|\n|Rural |Relative |      0.254|         0.037|          0.187|          0.334|\n|Urban |NotPoor  |      0.660|         0.037|          0.584|          0.728|\n|Urban |Extreme  |      0.113|         0.025|          0.073|          0.171|\n|Urban |Relative |      0.227|         0.026|          0.180|          0.283|\n\n\n:::\n:::\n\n\nLa @tbl-prop-zona-pobreza-hombre revela una geografía social particular. Mientras en las zonas urbanas el 66,0% de los hombres se encuentra fuera de la pobreza, en las rurales esta proporción desciende al 54,9%; mientras que la pobreza extrema aumenta del 11,3% al 19,8% al pasar de las zonas urbanas a las rurales. La pobreza relativa, en cambio, permanece más cercana entre ambos territorios. \n\nLas variables cuantitativas también pueden agruparse en categorías para facilitar su análisis conjunto con variables cualitativas. Por ejemplo, la edad puede clasificarse en rangos etarios y cruzarse posteriormente con la condición de actividad, lo que permite examinar cómo varía la participación laboral entre distintos grupos de población. En este caso, la población femenina se divide en dos categorías: mujeres de 18 a 35 años y mujeres pertenecientes a los demás grupos de edad. A partir de esta clasificación, se estima la distribución de la condición laboral en cada grupo etario. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfemale_subset %>%\n  filter(!is.na(Employment)) %>%\n  mutate(age_range = case_when(\n    Age >= 18 & Age <= 35 ~ \"18 - 35\",\n    TRUE ~ \"Other\"\n  )) %>%\n  group_by(age_range, Employment) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-prop-edad-rango-empleo-mujer .cell layout-align=\"center\" tbl-cap='Proporción de mujeres por rango de edad y estado de ocupación'}\n::: {.cell-output-display}\n\n\n|age_range |Employment | proportion| proportion_se| proportion_low| proportion_upp|\n|:---------|:----------|----------:|-------------:|--------------:|--------------:|\n|18 - 35   |Unemployed |      0.029|         0.009|          0.015|          0.054|\n|18 - 35   |Inactive   |      0.517|         0.038|          0.442|          0.591|\n|18 - 35   |Employed   |      0.455|         0.036|          0.385|          0.526|\n|Other     |Unemployed |      0.016|         0.007|          0.007|          0.036|\n|Other     |Inactive   |      0.571|         0.030|          0.511|          0.629|\n|Other     |Employed   |      0.413|         0.029|          0.356|          0.472|\n\n\n:::\n:::\n\n\nLa @tbl-prop-edad-rango-empleo-mujer muestra que la inactividad constituye la condición predominante entre las mujeres de ambos grupos de edad: alcanza el 51,7% entre aquellas de 18 a 35 años y el 57,1% entre las demás. Las mujeres más jóvenes presentan una mayor proporción de ocupación: 45,5%, frente a 41,3%, pero también un desempleo algo más elevado, de 2,9% frente a 1,6%. \n\n## Contrastes y diferencias de proporciones {#contrastes-y-diferencias-de-proporciones}\n\nCuando se analizan conjuntamente dos variables categóricas, es posible examinar cómo se distribuye una de ellas dentro de los grupos definidos por la otra. Por ejemplo, puede estudiarse la proporción de personas en situación de pobreza por sexo, zona de residencia o condición de actividad. Cada una de estas categorías define una subpoblación específica, para la cual pueden estimarse proporciones y sus correspondientes medidas de precisión [@KornGraubard1999; @HeeringaWestBerglund2017].\n\nSin embargo, la estimación separada de estas proporciones no siempre es suficiente. Con frecuencia, el interés principal consiste en determinar cuánto difieren dos grupos y si la brecha observada es suficientemente grande en relación con la incertidumbre asociada al muestreo. Para ello, pueden construirse contrastes lineales que expresen la diferencia entre dos proporciones estimadas y permitan obtener su error estándar, intervalo de confianza y, cuando corresponda, una prueba de significancia.\n\nSupóngase, por ejemplo, que se desea comparar la proporción de mujeres en situación de pobreza con la proporción correspondiente a los hombres. Este contraste puede expresarse como $\\hat{p}_F-\\hat{p}_M$, donde $\\hat{p}_F$ representa la proporción estimada de mujeres en pobreza y $\\hat{p}_M$ la proporción estimada de hombres en la misma condición. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_contrast <- svyby(\n  formula = ~poor,\n  by = ~Sex,\n  design = survey_design,\n  FUN = svymean,\n  na.rm = TRUE,\n  covmat = TRUE,\n  vartype = c(\"se\", \"ci\")\n)\n```\n:::\n\n\n\n::: {#tbl-svyby-pobreza-sexo2 .cell layout-align=\"center\" tbl-cap='Proporción en condición de pobreza por sexo'}\n::: {.cell-output-display}\n\n\n|       |Sex    |  poor|    se|  ci_l|  ci_u|\n|:------|:------|-----:|-----:|-----:|-----:|\n|Female |Female | 0.389| 0.032| 0.327| 0.451|\n|Male   |Male   | 0.395| 0.037| 0.323| 0.466|\n\n\n:::\n:::\n\n\nCon base en los resultados presentados en la @tbl-svyby-pobreza-sexo2, puede estimarse la diferencia entre las proporciones de mujeres y hombres en situación de pobreza, así como su correspondiente error estándar. Para ello, se resta la proporción estimada de hombres en pobreza de la proporción estimada de mujeres en la misma condición:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_estimate <- setNames(\n  as.numeric(sex_poverty_contrast[[\"poor\"]]),\n  sex_poverty_contrast[[\"Sex\"]]\n)\n\nsex_poverty_estimate[\"Female\"] - sex_poverty_estimate[\"Male\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Female \n-0.00532 \n```\n\n\n:::\n:::\n\n\nPara estimar correctamente la variabilidad asociada a esta diferencia debe incorporarse la covarianza entre ambas estimaciones, ya que estas no provienen de dos muestras independientes. En efecto, hombres y mujeres pueden pertenecer a los mismos hogares y, además, los hogares de ambos grupos son seleccionados dentro de las mismas unidades primarias de muestreo (UPM). Por consiguiente, las dos proporciones comparten la estructura de dependencia inducida por el diseño de muestreo. Esto implica que las variaciones observadas en una estimación pueden estar relacionadas con las de la otra y, por tanto, que su covarianza no puede suponerse igual a cero. En este contexto, el error estándar de la diferencia (contraste) debe calcularse aplicando las propiedades de la varianza e incorporando explícitamente dicha covarianza, de la siguiente forma:\n\n$$\n\\widehat{se}\\left(\\hat{p}_{F}-\\hat{p}_{M}\\right)\n=\n\\sqrt{\n\\widehat{Var}\\left(\\hat{p}_{F}\\right)\n+\n\\widehat{Var}\\left(\\hat{p}_{M}\\right)\n-\n2\\,\\widehat{Cov}\\left(\\hat{p}_{F},\\hat{p}_{M}\\right)\n}\n$$\n\n\nEn `R`, la matriz de varianzas y covarianzas puede obtenerse mediante la función `vcov`, cuyos resultados se presentan en la @tbl-vcov-sex-pobreza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_vcov <- vcov(sex_poverty_contrast)\n```\n:::\n\n\n\n::: {#tbl-vcov-sex-pobreza .cell layout-align=\"center\" tbl-cap='Matriz de varianzas y covarianzas de la proporción de pobreza por sexo'}\n::: {.cell-output-display}\n\n\n|       |   Female|     Male|\n|:------|--------:|--------:|\n|Female | 0.000998| 0.000918|\n|Male   | 0.000918| 0.001342|\n\n\n:::\n:::\n\n\nA partir de esta matriz, el error estándar de la diferencia de proporciones se estima, utilizando la expresión general para la varianza de una diferencia entre estimadores, la cual corresponde a la suma de las varianzas de cada estimación menos dos veces la covarianza entre ellas.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsqrt(\n  sex_poverty_vcov[\"Female\", \"Female\"] +\n    sex_poverty_vcov[\"Male\", \"Male\"] -\n    2 * sex_poverty_vcov[\"Female\", \"Male\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0224\n```\n\n\n:::\n:::\n\n\nNo obstante, el paquete `survey` permite realizar este procedimiento de forma directa mediante la función `svycontrast`, la cual calcula tanto el contraste lineal como su error estándar asociado. Para obtener la diferencia entre las proporciones de mujeres y hombres en condición de pobreza, se utiliza el siguiente código:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvycontrast(\n  stat = sex_poverty_contrast,\n  contrasts = list(sex_difference = c(1, -1))\n) %>%\n  data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               contrast sex_difference\nsex_difference -0.00532         0.0224\n```\n\n\n:::\n:::\n\n\nDe lo que se concluye que la diferencia estimada entre las proporciones de mujeres y hombres en estado de pobreza es -0.005 (-0.5%), con un error estándar de 0.022. Dada la magnitud del error estándar respecto de la diferencia, la estimación no debe interpretarse por sí sola como evidencia de una menor proporción de pobreza entre las mujeres.\n\nOtro ejercicio que puede desarrollarse a partir de una encuesta de hogares consiste en estimar la proporción de personas desempleadas según la región de residencia. Para ello, se estiman las proporciones de desempleo para cada una de las regiones consideradas en el análisis. Los resultados obtenidos se presentan en la @tbl-svyby-desempleo-region:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_unemployment_contrast <- svyby(\n  formula = ~ unemployed,\n  by = ~ Region,\n  design = survey_design %>%\n    filter(!is.na(unemployed)),\n  FUN = svymean,\n  na.rm = TRUE,\n  covmat = TRUE,\n  vartype = c(\"se\", \"ci\")\n)\n```\n:::\n\n\n\n::: {#tbl-svyby-desempleo-region .cell layout-align=\"center\" tbl-cap='Proporción en condición de desempleo por región'}\n::: {.cell-output-display}\n\n\n|          |Region    | unemployed|    se|  ci_l|  ci_u|\n|:---------|:---------|----------:|-----:|-----:|-----:|\n|Norte     |Norte     |      0.049| 0.020| 0.010| 0.088|\n|Sur       |Sur       |      0.066| 0.024| 0.019| 0.112|\n|Centro    |Centro    |      0.039| 0.012| 0.014| 0.063|\n|Occidente |Occidente |      0.040| 0.012| 0.016| 0.064|\n|Oriente   |Oriente   |      0.030| 0.013| 0.005| 0.054|\n\n\n:::\n:::\n\n\nUna vez estimadas las proporciones de desempleo por región, el siguiente paso consiste en evaluar si existen diferencias estadísticamente significativas entre algunas de estas proporciones mediante contrastes lineales. En particular, el interés se centra en comparar las diferencias entre las proporciones estimadas de desempleo de distintas regiones. Los contrastes considerados corresponden a $\\hat{p}_{Norte} - \\hat{p}_{Centro} = 0.01004$, $\\hat{p}_{Sur} - \\hat{p}_{Centro} = 0.02691$ y $\\hat{p}_{Occidente} - \\hat{p}_{Oriente} = 0.01046$. De manera matricial, estos contrastes entre regiones pueden escribirse así:\n\n$$\n\\left[\\begin{array}{ccccc}\n1 & 0 & -1 & 0 & 0\\\\\n0 & 1 & -1 & 0 & 0\\\\\n0 & 0 & 0 & 1 & -1\n\\end{array}\\right]\n$$\n\nPara calcular los errores estándar asociados a cada uno de los contrastes anteriores, es necesario considerar no solo las varianzas de las estimaciones regionales, sino también las covarianzas entre ellas. Esta información se resume en la matriz de varianzas y covarianzas de las proporciones estimadas de desempleo por región, presentada en la @tbl-vcov-desempleo-region:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_unemployment_vcov <- vcov(region_unemployment_contrast)\n```\n:::\n\n\n\n::: {#tbl-vcov-desempleo-region .cell layout-align=\"center\" tbl-cap='Matriz de varianzas y covarianzas de la proporción de desempleo por región'}\n::: {.cell-output-display}\n\n\n|          |    Norte|      Sur|   Centro| Occidente|  Oriente|\n|:---------|--------:|--------:|--------:|---------:|--------:|\n|Norte     | 0.000401| 0.000000| 0.000000|  0.000000| 0.000000|\n|Sur       | 0.000000| 0.000564| 0.000000|  0.000000| 0.000000|\n|Centro    | 0.000000| 0.000000| 0.000154|  0.000000| 0.000000|\n|Occidente | 0.000000| 0.000000| 0.000000|  0.000151| 0.000000|\n|Oriente   | 0.000000| 0.000000| 0.000000|  0.000000| 0.000158|\n\n\n:::\n:::\n\n\nNótese que, en este caso, las covarianzas entre las estimaciones regionales son iguales a cero debido a que las muestras seleccionadas en cada región son independientes entre sí. Por tanto, el error estándar de cada contraste se obtiene aplicando la expresión de la varianza para la diferencia entre dos estimadores. Para verificar los resultados sin introducir errores de redondeo, los cálculos siguientes toman las varianzas y covarianzas directamente de la matriz presentada en la @tbl-vcov-desempleo-region:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Norte - Centro\nsqrt(\n  region_unemployment_vcov[\"Norte\", \"Norte\"] +\n    region_unemployment_vcov[\"Centro\", \"Centro\"] -\n    2 * region_unemployment_vcov[\"Norte\", \"Centro\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0236\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sur - Centro\nsqrt(\n  region_unemployment_vcov[\"Sur\", \"Sur\"] +\n    region_unemployment_vcov[\"Centro\", \"Centro\"] -\n    2 * region_unemployment_vcov[\"Sur\", \"Centro\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0268\n```\n\n\n:::\n\n```{.r .cell-code}\n# Occidente - Oriente\nsqrt(\n  region_unemployment_vcov[\"Occidente\", \"Occidente\"] +\n    region_unemployment_vcov[\"Oriente\", \"Oriente\"] -\n    2 * region_unemployment_vcov[\"Occidente\", \"Oriente\"]\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0176\n```\n\n\n:::\n:::\n\n\n\nAlternativamente, el paquete `survey` permite calcular estos contrastes de manera directa mediante la función `svycontrast`, la cual obtiene tanto las diferencias estimadas entre proporciones como sus respectivos errores estándar. En este caso, la estimación de los contrastes definidos anteriormente se realiza de la siguiente manera:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvycontrast(\n  stat = region_unemployment_contrast,\n  contrasts = list(\n    north_center = c(1, 0, -1, 0, 0),\n    south_center = c(0, 1, -1, 0, 0),\n    west_east    = c(0, 0, 0, 1, -1)\n  )) %>%\n  data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             contrast     SE\nnorth_center   0.0100 0.0236\nsouth_center   0.0269 0.0268\nwest_east      0.0105 0.0176\n```\n\n\n:::\n:::\n\n\n## Pruebas de hipótesis sobre proporciones {#pruebas-de-hipotesis-sobre-proporciones}\n\nLas pruebas de hipótesis también permiten evaluar si las diferencias observadas entre proporciones estimadas para distintos grupos reflejan diferencias en la población o si pueden atribuirse al error de muestreo [@korn1995analysis]. En encuestas de hogares, estos contrastes deben incorporar las características del diseño muestral para estimar correctamente la variabilidad de las proporciones y realizar inferencias válidas.\n\nSupóngase que $p_H$ representa la proporción de hombres desocupados y $p_M$ la proporción de mujeres desocupadas dentro de la población económicamente activa. El parámetro de interés corresponde a la diferencia entre ambas proporciones:\n\n$$\n\\Delta_p = p_H - p_M.\n$$\n\nPara evaluar si las proporciones de desocupación de hombres y mujeres son diferentes, se plantea el siguiente sistema de hipótesis bilateral:\n\n$$\n\\begin{cases}\nH_{0}: & \\Delta_p = 0 \\quad (p_H = p_M) \\\\\nH_{1}: & \\Delta_p \\neq 0 \\quad (p_H \\neq p_M).\n\\end{cases}\n$$\n\nEl estimador muestral de esta diferencia se define como $\\hat{\\Delta}_p = \\hat{p}_H - \\hat{p}_M$. Su error estándar debe considerar tanto las varianzas de las proporciones estimadas como la covarianza entre ellas:\n\n$$\n\\widehat{se}(\\hat{\\Delta}_p) =\n\\sqrt{\n\\widehat{Var}(\\hat{p}_H)\n+\n\\widehat{Var}(\\hat{p}_M)\n-\n2\\widehat{Cov}(\\hat{p}_H,\\hat{p}_M)\n}.\n$$\n\nA partir de estas cantidades, el estadístico de prueba se expresa como:\n\n$$\nt =\n\\frac{\\hat{\\Delta}_p}\n{\\widehat{se}(\\hat{\\Delta}_p)} \\sim t_{df},\n$$\n\nel cual sigue aproximadamente una distribución $t$ de Student con los grados de libertad determinados por el diseño muestral. Bajo la hipótesis nula, valores absolutos elevados del estadístico $t$ proporcionan evidencia en contra de la igualdad de las proporciones.\n\nPara implementar esta prueba, la condición de desocupación se representa mediante una variable indicadora que toma el valor uno para las personas desocupadas y cero para las ocupadas. La media de esta variable dentro de cada grupo corresponde a la proporción de personas desocupadas. Además, el análisis debe restringirse a la población económicamente activa, por lo que se excluyen las personas inactivas y las observaciones con valores perdidos en `Employment`.\n\nEn `R`, la función `svyttest()` del paquete `survey` permite contrastar la diferencia entre las medias de esta variable binaria y, por tanto, la diferencia entre las proporciones de desocupación de hombres y mujeres, incorporando los ajustes asociados al diseño muestral. El procedimiento y sus resultados se presentan en la Tabla \\@ref(tab:tab-ttest-desempleo-sexo).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npea_design <- survey_design %>%\n  filter(\n    !is.na(Employment),\n    Employment %in% c(\"Employed\", \"Unemployed\")\n  )\n\nttest_unemployment_sex <- svyttest(\n  unemployed ~ Sex,\n  design = pea_design,\n  level = 0.95\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Prueba de diferencia de proporciones de desocupación por sexo (población económicamente activa)\n\n| statistic| p_value|  gl| ci_lower| ci_upper| estimated_difference|\n|---------:|-------:|---:|--------:|--------:|--------------------:|\n|      2.18|   0.031| 118|    0.003|    0.068|                0.036|\n\n\n:::\n:::\n\n\nLa diferencia estimada entre la proporción de hombres desocupados y la proporción de mujeres desocupadas es de 0.0359, es decir, la proporción correspondiente a los hombres es 3.59 puntos porcentuales mayor. El estadístico obtenido es $t = 2.182$, con 118 grados de libertad y un valor-*p* de 0.031. Dado que el valor-*p* es inferior al nivel de significancia del 5%, se rechaza la hipótesis nula de igualdad de proporciones. Por tanto, existe evidencia estadística suficiente para afirmar que, dentro de la población económicamente activa, la proporción de desocupados es diferente entre hombres y mujeres.\n\n\n\n## Tablas cruzadas {#tablas-cruzadas}\n\nDe acuerdo con @HeeringaWestBerglund2017 y @Agresti2019Intro, además de analizar cada variable de manera individual, resulta especialmente relevante estudiar si existe asociación entre dos variables categóricas. Este tipo de análisis permite identificar patrones y relaciones que aportan información valiosa para la toma de decisiones y la comprensión de fenómenos sociales. Por ejemplo, en el ámbito de las políticas públicas es posible relacionar educación y empleo para diseñar estrategias orientadas al mercado laboral; en la evaluación de programas sociales, analizar diferencias en el acceso a servicios de salud según el nivel de ingresos; y en investigación social, estudiar cómo variables demográficas y condiciones de vida se relacionan entre sí para comprender dinámicas y tendencias de la población.\n\nFormalmente, sean $x$ y $y$ dos variables categóricas con $R$ categorías para las filas y $C$ categorías para las columnas, respectivamente. En el contexto de encuestas por muestreo, el interés suele centrarse en estimar la distribución conjunta de ambas variables, es decir, la proporción de unidades poblacionales que pertenecen simultáneamente a cada combinación posible de categorías. Para ello, las entradas de una tabla cruzada, también conocida como tabla de contingencia, se estiman mediante frecuencias ponderadas obtenidas a partir de los factores de expansión y del diseño muestral. La estimación del total poblacional asociado a cada celda $(r,c)$ se define como:\n\n$$\n\\hat{N}_{rc} = \\sum_{h} \\sum_{i} \\sum_{k} w_{hik} \\ I(x_{hik}=r,\\ y_{hik}=c),\n$$\n\ndonde $w_{hik}$ representa el factor de expansión asociado al elemento $k$ de la UPM $i$ perteneciente al estrato $h$, mientras que $I(x_{hik}=r,\\ y_{hik}=c)$ corresponde a una función indicadora que toma el valor de uno cuando la unidad observada pertenece simultáneamente a la categoría $r$ de la variable $x$ y a la categoría $c$ de la variable $y$, y toma el valor de cero en cualquier otro caso.\n\nAdemás de las frecuencias conjuntas, también es posible estimar los tamaños marginales por filas y columnas, definidos respectivamente como $\\hat{N}_{r+} = \\sum_{c=1}^{C} \\hat{N}_{rc}$ y $\\hat{N}_{+c} = \\sum_{r=1}^{R} \\hat{N}_{rc}$. Mientras que el total general se expresa como $\\hat{N}_{++} = \\sum_{r=1}^{R}\\sum_{c=1}^{C} \\hat{N}_{rc}$. La estructura general de una tabla de contingencia con $R$ filas y $C$ columnas se presenta en la @tbl-estructura-contingencia:\n\n| Variable 2        | Variable 1 |               | $\\cdots$ |               | Marginal fila |\n|-------------------|-------------|---------------|-----------|---------------|----------------|\n|                   | $1$         | $2$           | $\\cdots$  | $C$           |                |\n| $1$               | $\\hat{N}_{11}$ | $\\hat{N}_{12}$ | $\\cdots$ | $\\hat{N}_{1C}$ | $\\hat{N}_{1+}$ |\n| $2$               | $\\hat{N}_{21}$ | $\\hat{N}_{22}$ | $\\cdots$ | $\\hat{N}_{2C}$ | $\\hat{N}_{2+}$ |\n| $\\vdots$          | $\\vdots$    | $\\vdots$      | $\\ddots$ | $\\vdots$      | $\\vdots$       |\n| $R$               | $\\hat{N}_{R1}$ | $\\hat{N}_{R2}$ | $\\cdots$ | $\\hat{N}_{RC}$ | $\\hat{N}_{R+}$ |\n| Marginal columna  | $\\hat{N}_{+1}$ | $\\hat{N}_{+2}$ | $\\cdots$ | $\\hat{N}_{+C}$ | $\\hat{N}_{++}$ |\n\n: Estructura general de una tabla de contingencia con $R$ filas y $C$ columnas {#tbl-estructura-contingencia}\n\nDe manera tradicional, las tablas de contingencia suelen representarse como arreglos bidimensionales de dimensión $R \\times C$. Sin embargo, también pueden extenderse para incorporar una o más variables adicionales, generando subconjuntos o subtablas que permiten estudiar relaciones más complejas entre variables categóricas. A partir de los tamaños estimados, también pueden estimarse proporciones para cada celda de la tabla de contingencia, de la siguiente manera:\n\n$$\n\\hat{p}_{rc}=\\frac{\\hat{N}_{rc}}{\\hat{N}_{++}}\n$$\n\n\nA continuación, y siguiendo con la base de datos de ejemplo, se estima la distribución porcentual de hombres y mujeres según su condición de pobreza, incorporando además sus respectivos errores estándar e intervalos de confianza. Los resultados se presentan en la @tbl-contingencia-pobreza-sexo. Este tipo de análisis permite describir la composición de la población pobre según sexo y evaluar la precisión de las estimaciones obtenidas a partir del diseño muestral.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_design <- survey_design %>%\n  mutate(poor = factor(\n    poor,\n    levels = 0:1,\n    labels = c(\"Not poor\", \"Poor\")\n  ))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_design %>%\n  group_by(poor, Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n::: {#tbl-contingencia-pobreza-sexo .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres en condición de pobreza y no pobreza'}\n::: {.cell-output-display}\n\n\n|poor     |Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:--------|:------|----------:|-------------:|--------------:|--------------:|\n|Not poor |Female |      0.529|         0.012|          0.505|          0.554|\n|Not poor |Male   |      0.471|         0.012|          0.446|          0.495|\n|Poor     |Female |      0.524|         0.016|          0.492|          0.555|\n|Poor     |Male   |      0.476|         0.016|          0.445|          0.508|\n\n\n:::\n:::\n\n\nLos resultados indican que el 52.3% de la población en condición de pobreza corresponde a mujeres, mientras que el 47.6% corresponde a hombres. Para las mujeres, el intervalo de confianza al 95% se encuentra entre 49.2% y 55.5%, mientras que para los hombres el intervalo correspondiente se ubica entre 44.5% y 50.7%. Estas estimaciones permiten observar la distribución relativa de la pobreza según sexo, considerando además la incertidumbre inherente al proceso de muestreo.\n\nCon el mismo enfoque de `srvyr` también puede estimarse la tabla de contingencia mediante `group_by()` y `summarise()`. En el siguiente ejemplo se estima la distribución de la condición de pobreza según sexo, obteniendo además medidas de precisión como errores estándar e intervalos de confianza. El código correspondiente y sus resultados se presentan en la @tbl-svyby-pobreza-sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_poverty_proportion <- poverty_design %>%\n  group_by(poor, Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-svyby-pobreza-sexo .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres por condición de pobreza '}\n::: {.cell-output-display}\n\n\n|poor     |Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:--------|:------|----------:|-------------:|--------------:|--------------:|\n|Not poor |Female |      0.529|         0.012|          0.505|          0.554|\n|Not poor |Male   |      0.471|         0.012|          0.446|          0.495|\n|Poor     |Female |      0.524|         0.016|          0.492|          0.555|\n|Poor     |Male   |      0.476|         0.016|          0.445|          0.508|\n\n\n:::\n:::\n\n\nLos intervalos de confianza ya fueron calculados por `survey_prop(vartype = c(\"se\", \"ci\"))`. El siguiente código no vuelve a estimarlos mediante `confint()`; utiliza `select()` para extraer las columnas que contienen sus límites inferior y superior. Los resultados se presentan en la @tbl-confint-sexo-pobreza y coinciden, por construcción, con los generados anteriormente.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_poverty_proportion %>%\n  dplyr::select(poor, Sex, proportion_low, proportion_upp)\n```\n:::\n\n\n\n::: {#tbl-confint-sexo-pobreza .cell layout-align=\"center\" tbl-cap='Intervalos de confianza para la proporción por sexo y pobreza'}\n::: {.cell-output-display}\n\n\n|poor     |Sex    | proportion_low| proportion_upp|\n|:--------|:------|--------------:|--------------:|\n|Not poor |Female |          0.505|          0.554|\n|Not poor |Male   |          0.446|          0.495|\n|Poor     |Female |          0.492|          0.555|\n|Poor     |Male   |          0.445|          0.508|\n\n\n:::\n:::\n\n\nOtro análisis de interés relacionado con tablas de doble entrada en encuestas de hogares consiste en estimar el porcentaje de personas desempleadas según sexo. El procedimiento correspondiente y sus resultados se presentan en la @tbl-svyby-empleo-sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_employment_proportion <- survey_design %>%\n  filter(!is.na(Employment)) %>%\n  group_by(Employment, Sex) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-svyby-empleo-sexo .cell layout-align=\"center\" tbl-cap='Proporción de hombres y mujeres por estado de ocupación '}\n::: {.cell-output-display}\n\n\n|Employment |Sex    | proportion| proportion_se| proportion_low| proportion_upp|\n|:----------|:------|----------:|-------------:|--------------:|--------------:|\n|Unemployed |Female |      0.273|         0.054|          0.180|          0.390|\n|Unemployed |Male   |      0.727|         0.054|          0.610|          0.820|\n|Inactive   |Female |      0.770|         0.023|          0.721|          0.813|\n|Inactive   |Male   |      0.230|         0.023|          0.187|          0.279|\n|Employed   |Female |      0.405|         0.019|          0.369|          0.442|\n|Employed   |Male   |      0.595|         0.019|          0.558|          0.631|\n\n\n:::\n:::\n\n\nDe la anterior salida se puede observar que el 27.2% de las personas desempleadas son mujeres y el 72.7% son hombres, con errores estándar de 5.3 puntos porcentuales para ambas estimaciones. Los intervalos de confianza correspondientes se presentan en la @tbl-confint-empleo-sexo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_by_employment_proportion %>%\n  dplyr::select(Employment, Sex, proportion_low, proportion_upp)\n```\n:::\n\n\n::: {#tbl-confint-empleo-sexo .cell layout-align=\"center\" tbl-cap='Intervalos de confianza para la proporción por sexo y ocupación'}\n::: {.cell-output-display}\n\n\n|Employment |Sex    | proportion_low| proportion_upp|\n|:----------|:------|--------------:|--------------:|\n|Unemployed |Female |          0.180|          0.390|\n|Unemployed |Male   |          0.610|          0.820|\n|Inactive   |Female |          0.721|          0.813|\n|Inactive   |Male   |          0.187|          0.279|\n|Employed   |Female |          0.369|          0.442|\n|Employed   |Male   |          0.558|          0.631|\n\n\n:::\n:::\n\n\n\nSi ahora el objetivo es estimar la pobreza por región, se utiliza la variable numérica `poor` dentro de un flujo `srvyr`, como se muestra en la @tbl-svyby-region-pobreza.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_poverty_proportion <- survey_design %>%\n  group_by(Region, poor) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n```\n:::\n\n\n\n::: {#tbl-svyby-region-pobreza .cell layout-align=\"center\" tbl-cap='Proporción en condición de pobreza por región'}\n::: {.cell-output-display}\n\n\n|Region    | poor| proportion| proportion_se| proportion_low| proportion_upp|\n|:---------|----:|----------:|-------------:|--------------:|--------------:|\n|Norte     |    0|      0.641|         0.055|          0.526|          0.742|\n|Norte     |    1|      0.359|         0.055|          0.258|          0.474|\n|Sur       |    0|      0.656|         0.043|          0.566|          0.737|\n|Sur       |    1|      0.344|         0.043|          0.263|          0.434|\n|Centro    |    0|      0.635|         0.079|          0.470|          0.773|\n|Centro    |    1|      0.365|         0.079|          0.227|          0.530|\n|Occidente |    0|      0.599|         0.047|          0.504|          0.687|\n|Occidente |    1|      0.401|         0.047|          0.313|          0.496|\n|Oriente   |    0|      0.548|         0.088|          0.374|          0.711|\n|Oriente   |    1|      0.452|         0.088|          0.289|          0.626|\n\n\n:::\n:::\n\n\nDe lo anterior se puede concluir que, en la región Norte, el 35% de las personas están en estado de pobreza, mientras que en el Sur la proporción es del 34%. La proporción estimada más alta se observa en la región Oriente, con un 45%. Los errores estándar reportados permiten evaluar la precisión de estas estimaciones.\n\n## La razón de *odds* {#la-razon-de-odds}\n\nDe acuerdo con @DiazMoralesLeon2018 y @Agresti2019Intro, la razón de *odds* es una medida ampliamente utilizada para estudiar la asociación entre dos variables categóricas, especialmente cuando el interés se centra en comparar la probabilidad de ocurrencia de un evento entre distintos grupos poblacionales. Su interpretación se basa en comparar las ventajas relativas (*odds*) de ocurrencia de un evento entre dos categorías de análisis.\n\nComo explican @HeeringaWestBerglund2017, en este sentido, este parámetro permite evaluar cómo cambia dicha ventaja entre diferentes grupos de interés y constituye una herramienta fundamental en estudios sociales, económicos y de salud; además, esta medida también puede utilizarse para cuantificar la relación entre los niveles de una variable y un factor categórico, comparando las ventajas relativas de ocurrencia del evento en cada grupo.\n\nPor ejemplo, suponga que se desea estudiar la asociación entre el sexo de las personas y la condición de pobreza. En particular, interesa evaluar si la ventaja relativa de pertenecer al grupo de personas no pobres frente al grupo de personas pobres es diferente entre mujeres y hombres. Para ello, puede expresarse la siguiente razón de *odds*:\n\n$$\n\\mathit{OR} =\n\\frac{\nP(\\text{pobreza}=0 \\mid \\text{Sex}=\\text{Female})\n\\big/\nP(\\text{pobreza}=1 \\mid \\text{Sex}=\\text{Female})\n}{\nP(\\text{pobreza}=0 \\mid \\text{Sex}=\\text{Male})\n\\big/\nP(\\text{pobreza}=1 \\mid \\text{Sex}=\\text{Male})\n}\n$$\n\nLa expresión del numerador representa, entre las mujeres, la ventaja relativa de encontrarse en condición de no pobreza respecto de encontrarse en pobreza. De manera análoga, el denominador representa esa misma ventaja entre los hombres. Por tanto, la razón de odds compara ambas ventajas relativas y permite cuantificar si la asociación entre sexo y pobreza favorece más a un grupo que a otro.\n\nUn valor igual a uno indicaría ausencia de asociación entre las variables, es decir, que la relación entre sexo y condición de pobreza es similar para hombres y mujeres. Valores superiores a uno indicarían una mayor ventaja relativa para las mujeres en comparación con los hombres, mientras que valores inferiores a uno sugerirían una mayor ventaja relativa para los hombres. En el contexto de encuestas de hogares, este tipo de medidas resulta especialmente útil para estudiar desigualdades sociodemográficas y brechas en condiciones de bienestar entre distintos grupos poblacionales.\n\nEl procedimiento para realizarlo en `R` sería primero estimar las proporciones de la tabla cruzada entre las variables sexo y pobreza, presentada en la @tbl-interaccion-sexo-pobreza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsex_poverty_interaction_proportion <- survey_design %>%\n  group_by(Sex, poor) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n\nsex_poverty_odds_contrast <- svymean(x = ~interaction(Sex, poor),\n                                     design = survey_design,\n                                     se = TRUE, na.rm = TRUE, ci = TRUE,\n                                     keep.vars = TRUE)\n```\n:::\n\n\n\n::: {#tbl-interaccion-sexo-pobreza .cell layout-align=\"center\" tbl-cap='Proporciones conjuntas de sexo y condición de pobreza'}\n::: {.cell-output-display}\n\n\n|Sex    | poor| proportion| proportion_se| proportion_low| proportion_upp|\n|:------|----:|----------:|-------------:|--------------:|--------------:|\n|Female |    0|      0.611|         0.032|          0.547|          0.671|\n|Female |    1|      0.389|         0.032|          0.329|          0.453|\n|Male   |    0|      0.605|         0.037|          0.531|          0.675|\n|Male   |    1|      0.395|         0.037|          0.325|          0.469|\n\n\n:::\n:::\n\n\nLuego, la función `svycontrast()` realiza el contraste dividiendo cada uno de los elementos de la expresión mostrada anteriormente:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nodds_ratio <- quote(\n (`interaction(Sex, poor)Female.0` /\n  `interaction(Sex, poor)Female.1`) /\n (`interaction(Sex, poor)Male.0` /\n  `interaction(Sex, poor)Male.1`)\n)\n\nsvycontrast(\n  stat = sex_poverty_odds_contrast,\n  contrasts = odds_ratio\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         nlcon  SE\ncontrast  1.02 0.1\n```\n\n\n:::\n:::\n\n\nObteniendo que el *odds* estimado de que una mujer no se encuentre en situación de pobreza, en comparación con un hombre, es igual a 1.02. Esto significa que, sin considerar otras variables de la encuesta, las mujeres presentan una razón de probabilidades de no estar en pobreza aproximadamente 2% mayor que la observada en los hombres. En otras palabras, la probabilidad relativa de no encontrarse en condición de pobreza es ligeramente superior para las mujeres respecto a los hombres.\n\n## Prueba de independencia $\\chi^{2}$ {#prueba-de-independencia-chi}\n\nComo explica @Agresti2019Intro, y como se introdujo en los capítulos anteriores, una prueba de hipótesis es un procedimiento estadístico utilizado para evaluar si la evidencia observada en una muestra es compatible con una afirmación acerca de la población. En el contexto de tablas de contingencia, las pruebas de independencia permiten analizar si existe asociación entre dos variables categóricas.\n\nDe acuerdo con @HeeringaWestBerglund2017, en este caso, la hipótesis nula ($H_{0}$) establece que ambas variables son independientes; es decir, que la distribución de una variable no depende de las categorías de la otra. Bajo este supuesto, las diferencias observadas en la muestra se atribuyen únicamente a la variabilidad muestral y no a una relación real entre las variables en la población. Matemáticamente, esta hipótesis puede expresarse como:\n\n$$\nH_0: p_{rc}^0 = p_{r+} \\times p_{+c}, \\quad \\text{para todo } r = 1,\\ldots,R \\text{ y } c = 1,\\ldots,C\n$$\n\nEn donde $p_{rc}^0$ representa la proporción esperada en la celda $(r,c)$ bajo el supuesto de independencia, mientras que $P_{r+}$ y $P_{+c}$ corresponden a las proporciones marginales de las filas y columnas, respectivamente. Bajo esta formulación, la hipótesis de independencia implica que la probabilidad conjunta de cada celda puede expresarse como el producto de sus probabilidades marginales.\n\nEn consecuencia, la prueba de independencia consiste en comparar las proporciones observadas o estimadas $\\hat{p}_{rc}$ con las proporciones esperadas $p_{rc}^0$ bajo la hipótesis nula. Cuando las diferencias entre ambas son pequeñas, la evidencia empírica resulta consistente con el supuesto de independencia. Por el contrario, discrepancias suficientemente grandes sugieren la existencia de asociación entre las variables y conducen al rechazo de $H_0$.\n\nComo explican @RaoScott1981, en las encuestas de hogares, características propias del diseño muestral complejo, como la estratificación, la selección por conglomerados y el uso de factores de expansión, afectan la variabilidad de los estimadores en comparación con la que se obtendría bajo un muestreo aleatorio simple. Como consecuencia, la prueba clásica de independencia $\\chi^2$ de Pearson no resulta adecuada para analizar tablas de contingencia provenientes de este tipo de diseños, ya que puede subestimar o sobreestimar la variabilidad real de las estimaciones.\n\nCon el propósito de corregir este problema, @fay1979contingency, @fellegi1980approximate y @thomas1987chisquare propusieron los primeros ajustes al estadístico chi-cuadrado de Pearson, basados en el efecto de diseño generalizado ($GDEFF$). Posteriormente, @rao1984chisquare amplió y formalizó el marco teórico de estas correcciones, dando origen a lo que actualmente se conoce como la prueba de Rao-Scott, considerada el procedimiento de referencia para el análisis de datos categóricos obtenidos mediante encuestas complejas.\n\nLa idea central del ajuste de primer orden consiste en adaptar la prueba clásica de independencia mediante la incorporación del efecto de diseño generalizado, obteniendo así un estadístico robusto frente a las complejidades del diseño muestral:\n\n$$\n\\chi_{RS}^2 = \\frac{n_{++}}{GDEFF} \\sum_r \\sum_c \\frac{(\\hat{p}_{rc} - p_{rc}^0)^2}{p_{rc}^0}\n$$\n\nComo explica @Lumley2026, esta expresión resume la corrección de primer orden. La opción `statistic = \"F\"` utilizada más adelante en `svychisq()` corresponde a la corrección de segundo orden de Rao-Scott expresada mediante una aproximación basada en la distribución $F$; por ello, no debe interpretarse como una aplicación numéricamente idéntica de la fórmula anterior.\n\ndonde $n_{++}$ representa el tamaño total de la muestra, $\\hat{p}_{rc}$ corresponde a la proporción estimada en la celda $(r,c)$ de la tabla de contingencia y $p_{rc}^0$ denota la proporción esperada bajo la hipótesis nula de independencia, calculada a partir del producto de las proporciones marginales de filas y columnas.\n\nEl término $GDEFF$ representa el efecto de diseño generalizado y mide cuánto se incrementa o disminuye la variabilidad de las estimaciones como consecuencia del diseño complejo de la encuesta respecto a la variabilidad que se observaría bajo un muestreo aleatorio simple. De esta manera, el ajuste de Rao--Scott permite que las inferencias derivadas de la prueba de independencia reflejen adecuadamente la estructura del diseño muestral.\n\nBajo la hipótesis nula $H_0$, el estadístico $\\chi_{RS}^2$ sigue aproximadamente una distribución $\\chi^2$ con $(R-1)(C-1)$ grados de libertad, donde $R$ y $C$ corresponden al número de categorías de las filas y columnas, respectivamente. En situaciones de muestras pequeñas o con pocos grados de libertad, es frecuente utilizar ajustes basados en la distribución $F$, los cuales mejoran la precisión de la inferencia estadística. Las pruebas de Rao-Scott constituyen el estándar para el análisis de asociación entre variables categóricas en encuestas complejas.\n\nEl paquete `survey` en `R` implementa este tipo de pruebas mediante la función `svychisq()`, la cual incorpora automáticamente los ajustes de Rao-Scott para tener en cuenta las características del diseño muestral complejo. Esta función permite evaluar la existencia de asociación entre dos variables categóricas utilizando tablas de contingencia ponderadas y corrigiendo adecuadamente la variabilidad de los estimadores. A modo de ejemplo, para evaluar si la condición de pobreza es independiente del sexo, se ejecuta el siguiente código:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvychisq(formula = ~Sex + poor, design = survey_design, statistic = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's X^2: Rao & Scott adjustment\n\ndata:  NextMethod()\nF = 0.06, ndf = 1, ddf = 119, p-value = 0.8\n```\n\n\n:::\n:::\n\n\nEn este caso, el argumento `formula` especifica las dos variables categóricas cuya independencia se desea evaluar; `design` corresponde al diseño muestral previamente definido; y `statistic = \"F\"` indica que la prueba se realizará utilizando la versión ajustada basada en la distribución $F$. Si el valor-*p* es superior al 5%, no se rechaza la hipótesis nula $H_0$, concluyendo que no existe evidencia estadística suficiente para afirmar que pobreza y sexo están asociadas. Por el contrario, si el valor-*p* es inferior al 5%, se rechaza $H_0$, lo que sugiere la existencia de dependencia o asociación entre ambas variables categóricas. De manera similar, se pueden evaluar otras relaciones, como desempleo y sexo o pobreza y región.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvychisq(formula = ~Sex + Employment, design = survey_design, statistic = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's X^2: Rao & Scott adjustment\n\ndata:  NextMethod()\nF = 62, ndf = 2, ddf = 201, p-value <0.0000000000000002\n```\n\n\n:::\n:::\n\n\nEn este primer caso, para el contraste de independencia entre las variables `Sex` y `Employment`, el estadístico obtenido fue $F = 62.251$, con un valor-$p$ menor que $2.2\\times10^{-16}$, lo que proporciona evidencia estadísticamente significativa para rechazar la hipótesis nula de independencia entre ambas variables. En consecuencia, los resultados sugieren que existe una asociación significativa entre el sexo y la condición de empleo en la población de estudio.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsvychisq(formula = ~Region + poor, design = survey_design, statistic = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's X^2: Rao & Scott adjustment\n\ndata:  NextMethod()\nF = 0.5, ndf = 3, ddf = 358, p-value = 0.7\n```\n\n\n:::\n:::\n\n\nPor otro lado, esta prueba de independencia entre las variables `Region` y `poor`, da como resultado $F = 0.48794$, con un valor-$p = 0.6914$. Dado que este valor-$p$ es considerablemente mayor que niveles de significancia convencionales, no existe evidencia suficiente para rechazar la hipótesis nula de independencia. Por tanto, los resultados sugieren que, bajo el diseño muestral considerado, no se observa una asociación estadísticamente significativa entre la región y la condición de pobreza.\n\n## Visualización de variables categóricas {#viz-categoricas}\n\nDe acuerdo con @Wickham2016ggplot2 y @HeeringaWestBerglund2017, la visualización de variables categóricas es fundamental en el análisis de encuestas de hogares, ya que permite comunicar de manera clara la distribución de grupos poblacionales y las comparaciones entre ellos. Al igual que en el análisis de variables continuas, los gráficos deben incorporar los pesos muestrales para que la representación visual corresponda a estimaciones válidas a nivel poblacional. Cuando la precisión estadística es relevante, es recomendable acompañar las barras con intervalos de confianza, que comunican tanto el valor central como la incertidumbre asociada al proceso de estimación.\n\nEn esta sección se utiliza el paquete `ggplot2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n```\n:::\n\n\n### Gráficos de barras {#graficos-de-barras}\n\nLa construcción de gráficos de barras en `R` requiere, como paso previo, obtener las estimaciones que se desean representar visualmente. En el contexto de encuestas complejas, estas estimaciones pueden calcularse mediante las funciones `survey_total()` o `survey_prop()` del paquete `srvyr`, dependiendo de si el interés se centra en totales poblacionales o proporciones.\n\nA continuación, se ilustra este procedimiento utilizando el tamaño poblacional estimado por zona de residencia. Los resultados gráficos correspondientes se presentan en la @fig-barras-zona:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nzone_size <- survey_design %>%\n  group_by(Zone) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n\nzone_colors <- c(Urban = \"#48C9B0\", Rural = \"#117864\")\n\nggplot(\n  data = zone_size,\n  aes(\n    x = Zone, y = size,\n    ymax = size_upp, ymin = size_low,\n    fill = Zone\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  scale_fill_manual(values = zone_colors) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barras del tamaño poblacional por zona geográfica](../figures/fig-barras-zona-1.png){#fig-barras-zona fig-align='center' width=70%}\n:::\n:::\n\n\nEl procedimiento anterior también puede aplicarse a variables con más de dos categorías. En estos casos, el gráfico de barras permite comparar de manera sencilla las estimaciones asociadas a cada categoría de la variable de interés. Por ejemplo, a continuación se presenta la distribución estimada de la población según la condición de pobreza, cuyos resultados gráficos se muestran en la @fig-barras-pobreza.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_size <- survey_design %>%\n  group_by(Poverty) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\")))\n\nggplot(\n  data = poverty_size,\n  aes(\n    x = Poverty, y = size,\n    ymax = size_upp, ymin = size_low,\n    fill = Poverty\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barras del tamaño poblacional por condición de pobreza](../figures/fig-barras-pobreza-1.png){#fig-barras-pobreza fig-align='center' width=70%}\n:::\n:::\n\n\nUna de las ventajas de los gráficos de barras es que pueden extenderse fácilmente a comparaciones entre dos variables categóricas. Por ejemplo, se puede analizar el tamaño poblacional por nivel de pobreza cruzado con el estado de ocupación, presentada en la @fig-barras-empleo-pobreza:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemployment_poverty_size <- survey_design %>%\n  group_by(unemployed, Poverty) %>%\n  summarise(size = survey_total(vartype = c(\"se\", \"ci\"))) %>%\n  as.data.frame() %>%\n  mutate(\n    unemployed = case_when(\n      unemployed == 0 ~ \"Occupied\",\n      unemployed == 1 ~ \"Unemployed\",\n      is.na(unemployed) ~ \"Not in the Labour Force\"\n    )\n  )\n\nggplot(\n  data = employment_poverty_size,\n  aes(\n    x = Poverty, y = size,\n    ymax = size_upp, ymin = size_low,\n    fill = as.factor(unemployed)\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barras del tamaño poblacional por estado de ocupación y pobreza](../figures/fig-barras-empleo-pobreza-1.png){#fig-barras-empleo-pobreza fig-align='center' width=80%}\n:::\n:::\n\n\nEste tipo de análisis gráfico resulta especialmente útil para identificar intersecciones de vulnerabilidad, al mostrar de manera simultánea dos o más características poblacionales. También es posible presentar proporciones en lugar de conteos. Por ejemplo, la proporción de hombres en condición de pobreza por zona, presentada en la @fig-barras-prop-zona-hombre:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_zone_poverty_proportion <- male_subset %>%\n  group_by(Zone, Poverty) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\")))\n\nggplot(\n  data = male_zone_poverty_proportion,\n  aes(\n    x = Poverty, y = proportion,\n    ymax = proportion_upp, ymin = proportion_low,\n    fill = Zone\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  scale_fill_manual(values = zone_colors) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Proporción de hombres en condición de pobreza por zona geográfica](../figures/fig-barras-prop-zona-hombre-1.png){#fig-barras-prop-zona-hombre fig-align='center' width=70%}\n:::\n:::\n\n\nDe forma análoga, se puede graficar la proporción de hombres en condición de pobreza desagregada por región, presentada en la @fig-barras-prop-region-hombre:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmale_region_poverty_proportion <- male_subset %>%\n  group_by(Region, poor) %>%\n  summarise(proportion = survey_prop(vartype = c(\"se\", \"ci\"))) %>%\n  data.frame()\n\nggplot(\n  data = male_region_poverty_proportion,\n  aes(\n    x = Region, y = proportion,\n    ymax = proportion_upp, ymin = proportion_low,\n    fill = as.factor(poor)\n  )\n) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3) +\n  theme_bw() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![Proporción de hombres en condición de pobreza por región](../figures/fig-barras-prop-region-hombre-1.png){#fig-barras-prop-region-hombre fig-align='center' width=75%}\n:::\n:::\n\n\nEn síntesis, los gráficos de barras junto con sus correspondientes errores estándar o intervalos de confianza permiten una descripción clara de los patrones de pobreza, empleo u otras variables categóricas en la población y, cuando se aplican correctamente, constituyen una herramienta poderosa para comunicar hallazgos de encuestas de hogares manteniendo el rigor estadístico en la representación de los resultados.\n\n\n### Mapas {#viz-mapas}\n\nComo explica @Tennekes2018tmap, los mapas temáticos constituyen una herramienta de visualización especialmente útil en el análisis de encuestas de hogares, ya que permiten representar la distribución territorial de indicadores sociales y demográficos. En este contexto, las estimaciones de proporciones calculadas en secciones anteriores —como el porcentaje de pobreza o desempleo por región— pueden proyectarse directamente sobre unidades geográficas, facilitando así la identificación de patrones espaciales y desigualdades regionales.\n\nDe acuerdo con @sf2026, @tmap2026 y @Pebesma2018sf, para construir este tipo de mapas en `R` se requiere información geoespacial en formato *shapefile*, la cual contiene los polígonos asociados a cada unidad geográfica de análisis. En este capítulo se utiliza el archivo `shapeBigCity/BigCity.shp`, cuyas regiones corresponden a las definidas en la base de datos `BigCity`. Los paquetes `sf` y `tmap` permiten cargar, manipular y visualizar esta información geográfica de manera integrada con los resultados obtenidos a partir de la encuesta.\n\nEl siguiente código carga los paquetes necesarios para trabajar con información geoespacial y visualización cartográfica en `R`. La librería `sf` permite leer y manipular objetos espaciales modernos, mientras que `tmap` proporciona herramientas para elaborar mapas temáticos. La instrucción `tmap_mode(\"plot\")` establece el modo de visualización estática de los mapas, apropiado para documentos y reportes. Finalmente, la función `read_sf()` importa el archivo geográfico `BigCity.shp`, almacenándolo en el objeto `bigcity_shape`, el cual contiene los polígonos correspondientes a las regiones de análisis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(tmap)\ntmap_mode(\"plot\")\nbigcity_shape <- read_sf(\"../Data/shapeBigCity/BigCity.shp\")\n```\n:::\n\n\nCon el shapefile cargado, se puede generar un mapa de las regiones usando `tm_shape()` y `tm_polygons()`, como se muestra en la @fig-mapa-regiones:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntm_shape(bigcity_shape) +\n  tm_polygons(col = \"Region\")\n```\n\n::: {.cell-output-display}\n![Mapa de regiones geográficas de BigCity](../figures/fig-mapa-regiones-1.png){#fig-mapa-regiones fig-align='center' width=70%}\n:::\n:::\n\n\nPor ejemplo, si se desea representar geográficamente la proporción de hombres en condición de pobreza por región, estimada previamente en la @fig-barras-prop-region-hombre, es necesario integrar las estimaciones obtenidas con la información espacial del shapefile. Para ello, el objeto `male_region_poverty_proportion`, que contiene las proporciones estimadas para cada región, se vincula con el archivo geográfico mediante la función `left_join()`. Posteriormente, se filtran únicamente las observaciones correspondientes a la categoría de pobreza (`poor == 1`), de manera que el mapa represente exclusivamente la distribución espacial de la población masculina en condición de pobreza.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshape_region_map <- tm_shape(\n  bigcity_shape %>%\n    left_join(\n      male_region_poverty_proportion %>%\n        filter(poor == 1),\n      by = \"Region\"\n    )\n)\n```\n:::\n\n\nUna vez construido el objeto espacial con las estimaciones de interés, el argumento `breaks` ayuda a definir los puntos de corte que determinarán los intervalos de la escala de color utilizada en el mapa. Posteriormente, se genera el mapa temático, permitiendo visualizar la distribución regional de la proporción de hombres en condición de pobreza, como se presenta en la @fig-mapa-pobreza-hombre.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npoverty_breaks <- c(0, 0.2, 0.4, 0.6, 0.8, 1)\nshape_region_map +\n  tm_polygons(\n    col = \"proportion\",\n    breaks = poverty_breaks,\n    title = \"Poverty proportion\",\n    palette = \"YlOrRd\"\n  )\n```\n\n::: {.cell-output-display}\n![Proporción de hombres en condición de pobreza por región](../figures/fig-mapa-pobreza-hombre-1.png){#fig-mapa-pobreza-hombre fig-align='center' width=70%}\n:::\n:::\n\n\nOtro uso de los mapas en encuestas, señalado por @CEPAL2023Diseno, es la visualización de la precisión de las estimaciones. Por ejemplo, usando el coeficiente de variación del ingreso medio por región es posible identificar las áreas donde las estimaciones son menos confiables, como se muestra en la @fig-mapa-cv-ingreso.\n\nEl siguiente código calcula y representa geográficamente el coeficiente de variación del ingreso medio por región. En primer lugar, se estima el ingreso promedio para cada región. El argumento `vartype = \"cv\"` solicita el cálculo del coeficiente de variación de cada estimación. Posteriormente, se definen los intervalos de clasificación de la escala de color mediante el objeto `cv_breaks`, y las estimaciones se integran con la información geográfica del shapefile usando `left_join()`. Finalmente, mediante las funciones `tm_shape()` y `tm_polygons()` del paquete `tmap`, se construye el mapa que representa espacialmente los coeficientes de variación utilizando una escala de colores en blanco y negro y ajustando la proporción del mapa con `tm_layout(asp = 0)`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_mean <- survey_design %>%\n  group_by(Region) %>%\n  summarise(mean = survey_mean(Income,\n                               na.rm = TRUE,\n                               vartype = c(\"cv\")))\n\ncv_breaks <- c(0, 0.1, 0.2, 1)\nshape_cv_map <- tm_shape(\n  bigcity_shape %>%\n    left_join(region_mean, by = \"Region\")\n)\n\nshape_cv_map +\n  tm_polygons(\n    \"mean_cv\",\n    breaks = cv_breaks,\n    title = \"Mean income CV\",\n    palette = c(\"#FFFFFF\", \"#000000\")\n  ) +\n  tm_layout(asp = 0)\n```\n\n::: {.cell-output-display}\n![Coeficiente de variación del ingreso medio por región](../figures/fig-mapa-cv-ingreso-1.png){#fig-mapa-cv-ingreso fig-align='center' width=70%}\n:::\n:::\n\n\nLos polígonos con tonos más oscuros corresponden a regiones donde la estimación del ingreso presenta mayor variabilidad relativa. Un coeficiente de variación elevado indica menor precisión relativa, pero no permite atribuirla únicamente a un tamaño muestral insuficiente, pues también puede reflejar la ponderación y otras características del diseño.\n\nDe acuerdo con @biscale2025 y @cowplot2025, cuando se desea representar simultáneamente dos variables —por ejemplo, la proporción de pobreza y su coeficiente de variación— es posible construir un mapa bivariante utilizando `ggplot2` junto con los paquetes `biscale` y `cowplot`. Este tipo de visualización permite identificar regiones con alta pobreza y alta incertidumbre en la estimación de forma conjunta, como se presenta en la @fig-mapa-bivariante. El siguiente código estima la proporción de mujeres en condición de pobreza en zonas rurales para cada región, incorporando además el cálculo del coeficiente de variación de las estimaciones, generando así una base de datos lista para la construcción de un mapa bivariado.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nregion_sex_poverty_proportion <- survey_design %>%\n  group_by(Region, Zone, Sex, poor) %>%\n  summarise(proportion = survey_mean(vartype = \"cv\")) %>%\n  filter(poor == 1, Zone == \"Rural\", Sex == \"Female\")\n```\n:::\n\n\n\nEl siguiente código construye un mapa bivariado que permite visualizar simultáneamente la proporción de pobreza femenina rural y el coeficiente de variación asociado a dicha estimación por región. En primer lugar, se integran las estimaciones contenidas en `region_sex_poverty_proportion` con la información geográfica del shapefile mediante `left_join()`. Posteriormente, la función `bi_class()` del paquete `biscale` clasifica conjuntamente las variables `proportion` y `proportion_cv` en una cuadrícula de \\(3 \\times 3\\) categorías (`dim = 3`), empleando el método de clasificación de Fisher (`style = \"fisher\"`). Luego, con `ggplot2` y `geom_sf()`, se genera el mapa temático utilizando colores bivariados definidos por `bi_scale_fill()`, mientras que `bi_theme()` aplica un estilo minimalista y se elimina la leyenda predeterminada.\n\nA continuación, la función `bi_legend()` crea una leyenda especializada que permite interpretar simultáneamente ambas dimensiones del mapa: el coeficiente de variación y la pobreza femenina rural. Finalmente, mediante las funciones `ggdraw()` y `draw_plot()` del paquete `cowplot`, se combinan el mapa y la leyenda en una única visualización.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(biscale)\nlibrary(cowplot)\n\nbivariate_shape <- bigcity_shape %>%\n  left_join(region_sex_poverty_proportion, by = \"Region\")\n\nk <- 3\nbivariate_data <- bi_class(\n  bivariate_shape,\n  y = proportion,\n  x = proportion_cv,\n  dim = k,\n  style = \"fisher\"\n)\n\nbivariate_map <- ggplot() +\n  geom_sf(\n    data = bivariate_data,\n    aes(fill = bi_class, geometry = geometry),\n    colour = \"white\",\n    size = 0.1\n  ) +\n  bi_scale_fill(pal = \"GrPink\", dim = k) +\n  bi_theme() +\n  theme(legend.position = \"none\")\n\nbivariate_legend <- bi_legend(\n  pal = \"GrPink\",\n  dim = k,\n  xlab = \"Coefficient of variation\",\n  ylab = \"Rural female poverty\",\n  size = 8\n)\n\nggdraw() +\n  draw_plot(bivariate_map, 0, 0, 1, scale = 0.7) +\n  draw_plot(bivariate_legend, 0.75, 0.4, 0.2, 0.2)\n```\n\n::: {.cell-output-display}\n![Mapa bivariante: proporción de pobreza femenina rural y su coeficiente de variación por región](../figures/fig-mapa-bivariante-1.png){#fig-mapa-bivariante fig-align='center' width=80%}\n:::\n:::\n\n\nEn este mapa, cada celda de la leyenda combina un tono de la proporción de pobreza (eje vertical) con un tono del coeficiente de variación (eje horizontal), permitiendo identificar simultáneamente regiones con alta pobreza y alta incertidumbre en la estimación. Este tipo de representación puede ayudar a priorizar una evaluación del diseño y de la precisión en zonas geográficas específicas; por sí solo, sin embargo, no determina automáticamente que deba ampliarse el tamaño muestral.\n",
    "supporting": [
      "04-Categoricas_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}